/**
 * BASH44 Data Fabric Engine
 *
 * Enterprise data foundation covering the full data lifecycle:
 *
 *   1. ConnectorRegistry    — data source connectors (DB, API, webhook, stream, file)
 *   2. IngestionEngine      — batch / incremental / CDC / streaming / webhook
 *   3. DatasetRegistry      — raw / staging / curated / ontology / realtime zones
 *   4. CanonicalModel       — unified field mapping across sources
 *   5. IdentityResolution   — resolve "the same thing" across sources
 *   6. PipelineEngine       — DAG execution of transforms
 *   7. LineageEngine        — upstream/downstream provenance
 *   8. QualityEngine        — rules, scoring, blocking
 *   9. FreshnessTracker     — SLA monitoring
 *  10. SchemaEvolution      — schema drift detection
 *  11. WriteBackEngine      — outbound actions to source systems
 *  12. DataProductRegistry  — productized datasets with owner, SLA, consumers
 *
 * Every ingestion publishes to the real-time event bus, so the Command Center
 * sees data flowing in real time.
 */

import { realtimePlatform, type ModuleKey } from "./realtime-platform-engine";

// ════════════════════════════════════════════════════════════════
// TYPES
// ════════════════════════════════════════════════════════════════

export type SourceType =
  | "postgres" | "mysql" | "mssql" | "oracle" | "mongodb"
  | "rest_api" | "graphql" | "webhook" | "file_drop" | "sftp"
  | "s3" | "gcs" | "kafka" | "kinesis" | "pubsub"
  | "iot" | "plc" | "spreadsheet" | "erp_legacy" | "crm" | "third_party";

export type IngestionMode = "batch" | "incremental" | "cdc" | "streaming" | "webhook" | "file_drop";
export type DatasetZone = "raw" | "staging" | "curated" | "ontology" | "realtime" | "historical" | "event_store";
export type QualityStatus = "pass" | "warn" | "fail" | "error";
export type FreshnessStatus = "fresh" | "warning" | "stale" | "missing";

export interface DataSource {
  id: number;
  sourceKey: string;
  name: string;
  description?: string;
  sourceType: SourceType;
  category?: string;
  vendor?: string;
  connectionConfig?: Record<string, unknown>;
  status: "configured" | "testing" | "active" | "paused" | "failed" | "archived";
  healthScore?: number;
  lastTestedAt?: Date;
  lastSyncAt?: Date;
  sensitivityLevel?: "public" | "internal" | "confidential" | "restricted" | "pii";
  tags?: string[];
}

export interface IngestionJob {
  id: number;
  jobKey: string;
  name: string;
  sourceId: number;
  mode: IngestionMode;
  targetDatasetKey: string;
  targetZone: DatasetZone;
  schedule?: string;
  enabled: boolean;
  lastRunAt?: Date;
  lastSuccessAt?: Date;
  lastRowsIngested?: number;
  totalRowsIngested?: number;
}

export interface IngestionRun {
  id: number;
  jobId: number;
  status: "queued" | "running" | "success" | "failed" | "partial" | "cancelled";
  startedAt?: Date;
  finishedAt?: Date;
  durationMs?: number;
  rowsRead: number;
  rowsWritten: number;
  rowsSkipped: number;
  rowsFailed: number;
  errorMessage?: string;
  watermarkEnd?: string;
}

export interface FabricDataset {
  id: number;
  datasetKey: string;
  name: string;
  description?: string;
  zone: DatasetZone;
  domain?: string;
  storageType?: string;
  location?: string;
  format?: string;
  schemaVersion: number;
  schemaDefinition?: Array<{ name: string; type: string; nullable?: boolean; pii?: boolean }>;
  rowCount?: number;
  sizeBytes?: number;
  qualityScore?: number;
  refreshMode?: string;
  lastRefreshedAt?: Date;
  freshnessSlaMinutes?: number;
  containsPii?: boolean;
  lifecycleState?: "draft" | "active" | "deprecated" | "archived";
}

export interface DataProduct {
  id: number;
  productKey: string;
  name: string;
  description?: string;
  domain?: string;
  ownerId?: number;
  teamName?: string;
  primaryDatasetKey?: string;
  relatedDatasetKeys?: string[];
  ontologyObjectTypes?: string[];
  freshnessSla?: string;
  availabilitySla?: number;
  qualitySla?: number;
  consumers?: string[];
  status: "draft" | "beta" | "ga" | "deprecated";
  version?: string;
  tags?: string[];
}

export interface CanonicalMapping {
  id: number;
  sourceId: number;
  sourceField: string;
  canonicalEntity: string;
  canonicalField: string;
  transformExpression?: string;
  dataType?: string;
  confidence: number;
  autoGenerated?: boolean;
}

export interface CanonicalEntity {
  id: number;
  entityKey: string;
  name: string;
  description?: string;
  pluralName?: string;
  domain?: string;
  fields: Array<{
    name: string;
    type: string;
    description?: string;
    required?: boolean;
    semanticType?: string;
  }>;
  primaryKey?: string;
  identityFields: string[];
  ontologyObjectType?: string;
}

export interface IdentityCluster {
  id: number;
  canonicalEntity: string;
  canonicalId: string;
  canonicalAttributes: Record<string, unknown>;
  sourceCount: number;
  confidence?: number;
  resolutionMethod?: "exact" | "fuzzy" | "ml" | "manual" | "rule";
  manuallyVerified?: boolean;
  links: Array<{
    sourceId: number;
    sourceRecordId: string;
    sourceAttributes?: Record<string, unknown>;
    matchScore?: number;
  }>;
}

export interface FabricPipeline {
  id: number;
  pipelineKey: string;
  name: string;
  description?: string;
  domain?: string;
  dag?: {
    nodes: Array<{ id: string; type: string; name: string; params: Record<string, unknown> }>;
    edges: Array<{ from: string; to: string }>;
  };
  schedule?: string;
  triggerType?: "schedule" | "event" | "manual" | "dataset_ready" | "webhook";
  inputDatasetKeys?: string[];
  outputDatasetKeys?: string[];
  status: "active" | "paused" | "archived";
  lastRunAt?: Date;
  lastSuccessAt?: Date;
  successRate?: number;
  avgDurationMs?: number;
}

export interface LineageEdge {
  id: number;
  fromType: "source" | "dataset" | "pipeline" | "transform" | "product" | "ontology" | "dashboard" | "model";
  fromId: string;
  fromLabel?: string;
  toType: "source" | "dataset" | "pipeline" | "transform" | "product" | "ontology" | "dashboard" | "model";
  toId: string;
  toLabel?: string;
  relationship: "produces" | "consumes" | "derives_from" | "joins_with" | "uses" | "feeds" | "depends_on";
  pipelineId?: number;
  observedAt: Date;
}

export interface QualityRule {
  id: number;
  ruleKey: string;
  name: string;
  description?: string;
  datasetKey?: string;
  fieldName?: string;
  ruleType:
    | "not_null" | "unique" | "range" | "pattern" | "lookup" | "custom"
    | "schema_match" | "row_count" | "freshness" | "referential_integrity"
    | "distribution" | "anomaly";
  expression?: string;
  parameters?: Record<string, unknown>;
  severity: "info" | "warning" | "error" | "critical" | "blocking";
  onFailure: "log" | "alert" | "block" | "quarantine";
  enabled: boolean;
}

export interface QualityResult {
  id: number;
  ruleId: number;
  datasetKey: string;
  status: QualityStatus;
  rowsChecked?: number;
  rowsFailed?: number;
  failurePercent?: number;
  message?: string;
  executedAt: Date;
}

export interface FreshnessMeasurement {
  datasetKey: string;
  slaMinutes?: number;
  actualLagSeconds?: number;
  status: FreshnessStatus;
  measuredAt: Date;
}

export interface WriteBackAction {
  id: number;
  targetSourceId: number;
  targetSourceKey: string;
  actionType: "update_record" | "insert_record" | "call_endpoint" | "trigger_workflow" | "send_message";
  targetEntity?: string;
  targetRecordId?: string;
  payload?: Record<string, unknown>;
  requiresApproval: boolean;
  approvedBy?: number;
  approvedAt?: Date;
  status: "queued" | "running" | "success" | "failed" | "rolled_back";
  executedAt?: Date;
  result?: unknown;
  errorMessage?: string;
  canRollback: boolean;
  createdAt: Date;
}

export interface ChangeEvent {
  id: number;
  sourceId: number;
  sourceKey: string;
  datasetKey?: string;
  operation: "insert" | "update" | "delete" | "upsert" | "truncate";
  recordId?: string;
  beforeValues?: Record<string, unknown>;
  afterValues?: Record<string, unknown>;
  changedFields?: string[];
  sourceTimestamp?: Date;
  receivedAt: Date;
  processedAt?: Date;
}

// ════════════════════════════════════════════════════════════════
// IN-MEMORY STORE
// ════════════════════════════════════════════════════════════════

class FabricStore {
  sources = new Map<number, DataSource>();
  sourcesByKey = new Map<string, DataSource>();
  nextSourceId = 1;

  ingestionJobs = new Map<number, IngestionJob>();
  nextJobId = 1;

  ingestionRuns: IngestionRun[] = [];
  nextRunId = 1;
  maxRuns = 2000;

  datasets = new Map<string, FabricDataset>();
  nextDatasetId = 1;

  products = new Map<number, DataProduct>();
  productsByKey = new Map<string, DataProduct>();
  nextProductId = 1;

  canonicalEntities = new Map<string, CanonicalEntity>();
  nextCanonicalEntityId = 1;

  canonicalMappings: CanonicalMapping[] = [];
  nextMappingId = 1;

  identityClusters = new Map<string, IdentityCluster>();
  nextClusterId = 1;

  pipelines = new Map<number, FabricPipeline>();
  pipelinesByKey = new Map<string, FabricPipeline>();
  nextPipelineId = 1;

  lineage: LineageEdge[] = [];
  nextLineageId = 1;

  qualityRules = new Map<number, QualityRule>();
  nextQualityRuleId = 1;

  qualityResults: QualityResult[] = [];
  nextQualityResultId = 1;
  maxQualityResults = 2000;

  freshnessMeasurements = new Map<string, FreshnessMeasurement>();

  writeBackActions: WriteBackAction[] = [];
  nextWriteBackId = 1;

  changeEvents: ChangeEvent[] = [];
  nextChangeId = 1;
  maxChangeEvents = 5000;
}

// ════════════════════════════════════════════════════════════════
// CONNECTOR REGISTRY
// ════════════════════════════════════════════════════════════════

class ConnectorRegistry {
  constructor(private store: FabricStore) {}

  register(source: Omit<DataSource, "id">): DataSource {
    const id = this.store.nextSourceId++;
    const record: DataSource = { id, ...source };
    this.store.sources.set(id, record);
    this.store.sourcesByKey.set(source.sourceKey, record);
    return record;
  }

  get(idOrKey: number | string): DataSource | undefined {
    if (typeof idOrKey === "number") return this.store.sources.get(idOrKey);
    return this.store.sourcesByKey.get(idOrKey);
  }

  all(): DataSource[] {
    return Array.from(this.store.sources.values());
  }

  byType(type: SourceType): DataSource[] {
    return this.all().filter(s => s.sourceType === type);
  }

  byCategory(category: string): DataSource[] {
    return this.all().filter(s => s.category === category);
  }

  updateStatus(id: number, status: DataSource["status"], healthScore?: number) {
    const s = this.store.sources.get(id);
    if (s) {
      s.status = status;
      if (healthScore != null) s.healthScore = healthScore;
      s.lastSyncAt = new Date();
    }
  }

  health(): { total: number; active: number; failed: number; paused: number; avgHealth: number } {
    const sources = this.all();
    const active = sources.filter(s => s.status === "active").length;
    const failed = sources.filter(s => s.status === "failed").length;
    const paused = sources.filter(s => s.status === "paused").length;
    const withHealth = sources.filter(s => s.healthScore != null);
    const avgHealth = withHealth.length > 0
      ? withHealth.reduce((sum, s) => sum + (s.healthScore ?? 0), 0) / withHealth.length
      : 100;
    return { total: sources.length, active, failed, paused, avgHealth };
  }
}

// ════════════════════════════════════════════════════════════════
// INGESTION ENGINE
// ════════════════════════════════════════════════════════════════

class IngestionEngine {
  constructor(private store: FabricStore) {}

  registerJob(job: Omit<IngestionJob, "id">): IngestionJob {
    const id = this.store.nextJobId++;
    const record: IngestionJob = { id, totalRowsIngested: 0, ...job };
    this.store.ingestionJobs.set(id, record);
    return record;
  }

  allJobs(): IngestionJob[] {
    return Array.from(this.store.ingestionJobs.values());
  }

  getJob(id: number): IngestionJob | undefined {
    return this.store.ingestionJobs.get(id);
  }

  jobsByMode(mode: IngestionMode): IngestionJob[] {
    return this.allJobs().filter(j => j.mode === mode);
  }

  async runJob(jobId: number): Promise<IngestionRun> {
    const job = this.store.ingestionJobs.get(jobId);
    if (!job) throw new Error(`Job ${jobId} not found`);

    const runId = this.store.nextRunId++;
    const run: IngestionRun = {
      id: runId,
      jobId,
      status: "running",
      startedAt: new Date(),
      rowsRead: 0,
      rowsWritten: 0,
      rowsSkipped: 0,
      rowsFailed: 0,
    };
    this.store.ingestionRuns.push(run);
    if (this.store.ingestionRuns.length > this.store.maxRuns) this.store.ingestionRuns.shift();

    // Publish ingestion started event
    realtimePlatform.publish({
      eventType: "ingestion.started",
      sourceModule: "ai",
      entityType: "ingestion_job",
      entityId: String(jobId),
      entityLabel: job.name,
      severity: "info",
      metadata: { mode: job.mode, zone: job.targetZone },
    });

    // Simulate execution
    await new Promise(r => setTimeout(r, 20));
    const rowsRead = Math.floor(Math.random() * 1000) + 100;
    const rowsWritten = Math.floor(rowsRead * 0.95);
    const rowsFailed = rowsRead - rowsWritten;
    run.finishedAt = new Date();
    run.durationMs = run.finishedAt.getTime() - (run.startedAt?.getTime() ?? 0);
    run.status = "success";
    run.rowsRead = rowsRead;
    run.rowsWritten = rowsWritten;
    run.rowsFailed = rowsFailed;
    run.watermarkEnd = new Date().toISOString();

    job.lastRunAt = run.finishedAt;
    job.lastSuccessAt = run.finishedAt;
    job.lastRowsIngested = rowsWritten;
    job.totalRowsIngested = (job.totalRowsIngested ?? 0) + rowsWritten;

    // Publish completion event
    realtimePlatform.publish({
      eventType: "ingestion.success",
      sourceModule: "ai",
      entityType: "ingestion_job",
      entityId: String(jobId),
      entityLabel: job.name,
      severity: "success",
      newState: { status: "success", rowsWritten, durationMs: run.durationMs },
      metadata: { runId, targetZone: job.targetZone },
    });

    return run;
  }

  recentRuns(limit = 100): IngestionRun[] {
    return this.store.ingestionRuns.slice(-limit).reverse();
  }

  runsByJob(jobId: number, limit = 50): IngestionRun[] {
    return this.store.ingestionRuns.filter(r => r.jobId === jobId).slice(-limit).reverse();
  }

  stats() {
    const runs = this.store.ingestionRuns;
    const total = runs.length;
    const success = runs.filter(r => r.status === "success").length;
    const failed = runs.filter(r => r.status === "failed").length;
    const running = runs.filter(r => r.status === "running").length;
    return {
      total,
      success,
      failed,
      running,
      successRate: total > 0 ? (success / total) * 100 : 0,
      totalRowsIngested: runs.reduce((sum, r) => sum + r.rowsWritten, 0),
    };
  }
}

// ════════════════════════════════════════════════════════════════
// DATASET REGISTRY
// ════════════════════════════════════════════════════════════════

class DatasetRegistry {
  constructor(private store: FabricStore) {}

  register(dataset: Omit<FabricDataset, "id">): FabricDataset {
    const id = this.store.nextDatasetId++;
    const record: FabricDataset = { id, ...dataset };
    this.store.datasets.set(dataset.datasetKey, record);
    return record;
  }

  get(key: string): FabricDataset | undefined {
    return this.store.datasets.get(key);
  }

  all(): FabricDataset[] {
    return Array.from(this.store.datasets.values());
  }

  byZone(zone: DatasetZone): FabricDataset[] {
    return this.all().filter(d => d.zone === zone);
  }

  byDomain(domain: string): FabricDataset[] {
    return this.all().filter(d => d.domain === domain);
  }

  updateRefresh(key: string, rowCount?: number) {
    const d = this.store.datasets.get(key);
    if (d) {
      d.lastRefreshedAt = new Date();
      if (rowCount != null) d.rowCount = rowCount;
    }
  }

  summary() {
    const datasets = this.all();
    const byZone: Record<string, number> = {};
    for (const d of datasets) {
      byZone[d.zone] = (byZone[d.zone] ?? 0) + 1;
    }
    return {
      total: datasets.length,
      byZone,
      totalRows: datasets.reduce((sum, d) => sum + (d.rowCount ?? 0), 0),
      avgQuality: datasets.filter(d => d.qualityScore != null).reduce((sum, d) => sum + (d.qualityScore ?? 0), 0) / Math.max(1, datasets.filter(d => d.qualityScore != null).length),
      containsPii: datasets.filter(d => d.containsPii).length,
    };
  }
}

// ════════════════════════════════════════════════════════════════
// CANONICAL MODEL + IDENTITY RESOLUTION
// ════════════════════════════════════════════════════════════════

class CanonicalModel {
  constructor(private store: FabricStore) {}

  registerEntity(entity: Omit<CanonicalEntity, "id">): CanonicalEntity {
    const id = this.store.nextCanonicalEntityId++;
    const record: CanonicalEntity = { id, ...entity };
    this.store.canonicalEntities.set(entity.entityKey, record);
    return record;
  }

  allEntities(): CanonicalEntity[] {
    return Array.from(this.store.canonicalEntities.values());
  }

  getEntity(key: string): CanonicalEntity | undefined {
    return this.store.canonicalEntities.get(key);
  }

  registerMapping(mapping: Omit<CanonicalMapping, "id">): CanonicalMapping {
    const id = this.store.nextMappingId++;
    const record: CanonicalMapping = { id, ...mapping };
    this.store.canonicalMappings.push(record);
    return record;
  }

  mappingsForSource(sourceId: number): CanonicalMapping[] {
    return this.store.canonicalMappings.filter(m => m.sourceId === sourceId);
  }

  mappingsForEntity(entityKey: string): CanonicalMapping[] {
    return this.store.canonicalMappings.filter(m => m.canonicalEntity === entityKey);
  }
}

class IdentityResolutionEngine {
  constructor(private store: FabricStore) {}

  /**
   * Register a record from a source and find-or-create its canonical cluster.
   * Uses exact match on identity fields, then fuzzy fallback.
   */
  resolve(
    canonicalEntity: string,
    sourceId: number,
    sourceRecordId: string,
    attributes: Record<string, unknown>,
    identityFields: string[]
  ): IdentityCluster {
    // Try to find an existing cluster by identity fields
    let match: IdentityCluster | undefined;
    let bestScore = 0;

    for (const cluster of this.store.identityClusters.values()) {
      if (cluster.canonicalEntity !== canonicalEntity) continue;
      const score = this.similarityScore(cluster.canonicalAttributes, attributes, identityFields);
      if (score > bestScore && score >= 0.8) {
        match = cluster;
        bestScore = score;
      }
    }

    if (match) {
      // Add the link
      match.sourceCount++;
      match.links.push({
        sourceId,
        sourceRecordId,
        sourceAttributes: attributes,
        matchScore: bestScore,
      });
      if (match.confidence) {
        match.confidence = (match.confidence + bestScore) / 2;
      } else {
        match.confidence = bestScore;
      }
      return match;
    }

    // Create new cluster
    const id = this.store.nextClusterId++;
    const canonicalId = `${canonicalEntity}-${id}`;
    const newCluster: IdentityCluster = {
      id,
      canonicalEntity,
      canonicalId,
      canonicalAttributes: { ...attributes },
      sourceCount: 1,
      confidence: 1,
      resolutionMethod: "exact",
      links: [{ sourceId, sourceRecordId, sourceAttributes: attributes, matchScore: 1 }],
    };
    this.store.identityClusters.set(`${canonicalEntity}:${canonicalId}`, newCluster);
    return newCluster;
  }

  private similarityScore(
    a: Record<string, unknown>,
    b: Record<string, unknown>,
    fields: string[]
  ): number {
    if (fields.length === 0) return 0;
    let matches = 0;
    for (const field of fields) {
      const va = this.normalize(a[field]);
      const vb = this.normalize(b[field]);
      if (va && vb && va === vb) matches++;
      else if (va && vb && this.levenshteinSimilarity(va, vb) > 0.85) matches += 0.85;
    }
    return matches / fields.length;
  }

  private normalize(v: unknown): string {
    if (v == null) return "";
    return String(v).toLowerCase().trim().replace(/\s+/g, " ");
  }

  private levenshteinSimilarity(a: string, b: string): number {
    if (a === b) return 1;
    const maxLen = Math.max(a.length, b.length);
    if (maxLen === 0) return 1;
    const dist = this.levenshteinDistance(a, b);
    return 1 - dist / maxLen;
  }

  private levenshteinDistance(a: string, b: string): number {
    const dp = Array.from({ length: a.length + 1 }, () => new Array(b.length + 1).fill(0));
    for (let i = 0; i <= a.length; i++) dp[i]![0] = i;
    for (let j = 0; j <= b.length; j++) dp[0]![j] = j;
    for (let i = 1; i <= a.length; i++) {
      for (let j = 1; j <= b.length; j++) {
        const cost = a[i - 1] === b[j - 1] ? 0 : 1;
        dp[i]![j] = Math.min(
          dp[i - 1]![j]! + 1,
          dp[i]![j - 1]! + 1,
          dp[i - 1]![j - 1]! + cost
        );
      }
    }
    return dp[a.length]![b.length]!;
  }

  allClusters(): IdentityCluster[] {
    return Array.from(this.store.identityClusters.values());
  }

  clustersForEntity(entityKey: string): IdentityCluster[] {
    return this.allClusters().filter(c => c.canonicalEntity === entityKey);
  }

  stats() {
    const clusters = this.allClusters();
    return {
      totalClusters: clusters.length,
      totalLinks: clusters.reduce((sum, c) => sum + c.links.length, 0),
      multiSourceClusters: clusters.filter(c => c.sourceCount > 1).length,
      avgConfidence: clusters.length > 0
        ? clusters.reduce((sum, c) => sum + (c.confidence ?? 0), 0) / clusters.length
        : 0,
    };
  }
}

// ════════════════════════════════════════════════════════════════
// PIPELINE ENGINE
// ════════════════════════════════════════════════════════════════

class PipelineEngine {
  constructor(private store: FabricStore) {}

  register(pipeline: Omit<FabricPipeline, "id">): FabricPipeline {
    const id = this.store.nextPipelineId++;
    const record: FabricPipeline = { id, ...pipeline };
    this.store.pipelines.set(id, record);
    this.store.pipelinesByKey.set(pipeline.pipelineKey, record);
    return record;
  }

  get(idOrKey: number | string): FabricPipeline | undefined {
    if (typeof idOrKey === "number") return this.store.pipelines.get(idOrKey);
    return this.store.pipelinesByKey.get(idOrKey);
  }

  all(): FabricPipeline[] {
    return Array.from(this.store.pipelines.values());
  }

  async run(pipelineId: number): Promise<{ success: boolean; durationMs: number; nodesExecuted: number }> {
    const p = this.store.pipelines.get(pipelineId);
    if (!p) throw new Error(`Pipeline ${pipelineId} not found`);

    const start = Date.now();
    realtimePlatform.publish({
      eventType: "pipeline.started",
      sourceModule: "ai",
      entityType: "pipeline",
      entityId: String(pipelineId),
      entityLabel: p.name,
      severity: "info",
    });

    // Topological execution (simulated)
    const nodes = p.dag?.nodes ?? [];
    await new Promise(r => setTimeout(r, 30));
    const durationMs = Date.now() - start;

    p.lastRunAt = new Date();
    p.lastSuccessAt = new Date();
    p.avgDurationMs = p.avgDurationMs ? (p.avgDurationMs + durationMs) / 2 : durationMs;
    p.successRate = 100;

    realtimePlatform.publish({
      eventType: "pipeline.success",
      sourceModule: "ai",
      entityType: "pipeline",
      entityId: String(pipelineId),
      entityLabel: p.name,
      severity: "success",
      newState: { status: "success", durationMs, nodesExecuted: nodes.length },
    });

    return { success: true, durationMs, nodesExecuted: nodes.length };
  }
}

// ════════════════════════════════════════════════════════════════
// LINEAGE ENGINE
// ════════════════════════════════════════════════════════════════

class LineageEngine {
  constructor(private store: FabricStore) {}

  addEdge(edge: Omit<LineageEdge, "id" | "observedAt"> & { observedAt?: Date }): LineageEdge {
    const id = this.store.nextLineageId++;
    const record: LineageEdge = {
      id,
      ...edge,
      observedAt: edge.observedAt ?? new Date(),
    };
    this.store.lineage.push(record);
    return record;
  }

  downstream(fromType: string, fromId: string, maxDepth = 5): LineageEdge[] {
    const visited = new Set<string>();
    const result: LineageEdge[] = [];
    const queue: Array<{ type: string; id: string; depth: number }> = [
      { type: fromType, id: fromId, depth: 0 },
    ];
    visited.add(`${fromType}:${fromId}`);

    while (queue.length > 0) {
      const cur = queue.shift()!;
      if (cur.depth >= maxDepth) continue;
      const edges = this.store.lineage.filter(
        e => e.fromType === cur.type && e.fromId === cur.id
      );
      for (const edge of edges) {
        const key = `${edge.toType}:${edge.toId}`;
        if (visited.has(key)) continue;
        visited.add(key);
        result.push(edge);
        queue.push({ type: edge.toType, id: edge.toId, depth: cur.depth + 1 });
      }
    }
    return result;
  }

  upstream(toType: string, toId: string, maxDepth = 5): LineageEdge[] {
    const visited = new Set<string>();
    const result: LineageEdge[] = [];
    const queue: Array<{ type: string; id: string; depth: number }> = [
      { type: toType, id: toId, depth: 0 },
    ];
    visited.add(`${toType}:${toId}`);

    while (queue.length > 0) {
      const cur = queue.shift()!;
      if (cur.depth >= maxDepth) continue;
      const edges = this.store.lineage.filter(
        e => e.toType === cur.type && e.toId === cur.id
      );
      for (const edge of edges) {
        const key = `${edge.fromType}:${edge.fromId}`;
        if (visited.has(key)) continue;
        visited.add(key);
        result.push(edge);
        queue.push({ type: edge.fromType, id: edge.fromId, depth: cur.depth + 1 });
      }
    }
    return result;
  }

  allEdges(): LineageEdge[] {
    return this.store.lineage.slice();
  }

  graphSummary() {
    const nodeSet = new Set<string>();
    for (const e of this.store.lineage) {
      nodeSet.add(`${e.fromType}:${e.fromId}`);
      nodeSet.add(`${e.toType}:${e.toId}`);
    }
    return { nodes: nodeSet.size, edges: this.store.lineage.length };
  }
}

// ════════════════════════════════════════════════════════════════
// QUALITY ENGINE
// ════════════════════════════════════════════════════════════════

class QualityEngine {
  constructor(private store: FabricStore) {}

  registerRule(rule: Omit<QualityRule, "id">): QualityRule {
    const id = this.store.nextQualityRuleId++;
    const record: QualityRule = { id, ...rule };
    this.store.qualityRules.set(id, record);
    return record;
  }

  allRules(): QualityRule[] {
    return Array.from(this.store.qualityRules.values());
  }

  rulesForDataset(datasetKey: string): QualityRule[] {
    return this.allRules().filter(r => r.datasetKey === datasetKey);
  }

  recordResult(result: Omit<QualityResult, "id" | "executedAt"> & { executedAt?: Date }): QualityResult {
    const id = this.store.nextQualityResultId++;
    const record: QualityResult = {
      id,
      ...result,
      executedAt: result.executedAt ?? new Date(),
    };
    this.store.qualityResults.push(record);
    if (this.store.qualityResults.length > this.store.maxQualityResults) {
      this.store.qualityResults.shift();
    }
    // Publish quality event if fail
    if (result.status === "fail" || result.status === "error") {
      const rule = this.store.qualityRules.get(result.ruleId);
      realtimePlatform.publish({
        eventType: "data_quality.failed",
        sourceModule: "ai",
        entityType: "quality_rule",
        entityId: String(result.ruleId),
        entityLabel: rule?.name ?? `rule-${result.ruleId}`,
        severity: rule?.severity === "critical" || rule?.severity === "blocking" ? "critical" : "warning",
        newState: { status: result.status, rowsFailed: result.rowsFailed },
      });
    }
    return record;
  }

  recentResults(limit = 100): QualityResult[] {
    return this.store.qualityResults.slice(-limit).reverse();
  }

  datasetScore(datasetKey: string): number {
    const results = this.store.qualityResults.filter(r => r.datasetKey === datasetKey).slice(-20);
    if (results.length === 0) return 100;
    const passRate = results.filter(r => r.status === "pass").length / results.length;
    return passRate * 100;
  }

  summary() {
    const results = this.store.qualityResults;
    const pass = results.filter(r => r.status === "pass").length;
    const warn = results.filter(r => r.status === "warn").length;
    const fail = results.filter(r => r.status === "fail").length;
    const error = results.filter(r => r.status === "error").length;
    return {
      totalChecks: results.length,
      pass,
      warn,
      fail,
      error,
      passRate: results.length > 0 ? (pass / results.length) * 100 : 0,
      activeRules: this.allRules().filter(r => r.enabled).length,
    };
  }
}

// ════════════════════════════════════════════════════════════════
// FRESHNESS TRACKER
// ════════════════════════════════════════════════════════════════

class FreshnessTracker {
  constructor(private store: FabricStore) {}

  measure(datasetKey: string): FreshnessMeasurement {
    const dataset = this.store.datasets.get(datasetKey);
    const now = Date.now();
    const lastRefresh = dataset?.lastRefreshedAt?.getTime() ?? 0;
    const actualLagSeconds = Math.floor((now - lastRefresh) / 1000);
    const slaMinutes = dataset?.freshnessSlaMinutes ?? 60;
    const slaSeconds = slaMinutes * 60;
    let status: FreshnessStatus = "fresh";
    if (!lastRefresh) status = "missing";
    else if (actualLagSeconds > slaSeconds * 2) status = "stale";
    else if (actualLagSeconds > slaSeconds) status = "warning";

    const measurement: FreshnessMeasurement = {
      datasetKey,
      slaMinutes,
      actualLagSeconds,
      status,
      measuredAt: new Date(),
    };
    this.store.freshnessMeasurements.set(datasetKey, measurement);
    return measurement;
  }

  current(datasetKey: string): FreshnessMeasurement | undefined {
    return this.store.freshnessMeasurements.get(datasetKey);
  }

  all(): FreshnessMeasurement[] {
    return Array.from(this.store.freshnessMeasurements.values());
  }

  scanAll(): FreshnessMeasurement[] {
    return Array.from(this.store.datasets.keys()).map(key => this.measure(key));
  }

  summary() {
    const measurements = this.all();
    const fresh = measurements.filter(m => m.status === "fresh").length;
    const warning = measurements.filter(m => m.status === "warning").length;
    const stale = measurements.filter(m => m.status === "stale").length;
    const missing = measurements.filter(m => m.status === "missing").length;
    return { total: measurements.length, fresh, warning, stale, missing };
  }
}

// ════════════════════════════════════════════════════════════════
// WRITE-BACK ENGINE
// ════════════════════════════════════════════════════════════════

class WriteBackEngine {
  constructor(private store: FabricStore) {}

  queue(action: Omit<WriteBackAction, "id" | "status" | "createdAt">): WriteBackAction {
    const id = this.store.nextWriteBackId++;
    const record: WriteBackAction = {
      id,
      ...action,
      status: action.requiresApproval ? "queued" : "queued",
      createdAt: new Date(),
    };
    this.store.writeBackActions.push(record);
    return record;
  }

  async execute(actionId: number): Promise<WriteBackAction> {
    const action = this.store.writeBackActions.find(a => a.id === actionId);
    if (!action) throw new Error(`Action ${actionId} not found`);

    if (action.requiresApproval && !action.approvedBy) {
      action.status = "failed";
      action.errorMessage = "Approval required";
      return action;
    }

    action.status = "running";
    action.executedAt = new Date();

    // Simulate execution
    await new Promise(r => setTimeout(r, 20));

    action.status = "success";
    action.result = { success: true, actionType: action.actionType };

    realtimePlatform.publish({
      eventType: "write_back.executed",
      sourceModule: "ai",
      entityType: "write_back",
      entityId: String(actionId),
      entityLabel: `${action.actionType} → source ${action.targetSourceKey}`,
      severity: "success",
      newState: { status: "success" },
    });

    return action;
  }

  approve(actionId: number, userId: number) {
    const action = this.store.writeBackActions.find(a => a.id === actionId);
    if (action) {
      action.approvedBy = userId;
      action.approvedAt = new Date();
    }
    return action;
  }

  recent(limit = 100): WriteBackAction[] {
    return this.store.writeBackActions.slice(-limit).reverse();
  }

  pending(): WriteBackAction[] {
    return this.store.writeBackActions.filter(a => a.status === "queued" && a.requiresApproval && !a.approvedBy);
  }
}

// ════════════════════════════════════════════════════════════════
// CHANGE EVENT STORE — generic CDC
// ════════════════════════════════════════════════════════════════

class ChangeEventStore {
  constructor(private store: FabricStore) {}

  record(event: Omit<ChangeEvent, "id" | "receivedAt">): ChangeEvent {
    const id = this.store.nextChangeId++;
    const record: ChangeEvent = {
      id,
      ...event,
      receivedAt: new Date(),
    };
    this.store.changeEvents.push(record);
    if (this.store.changeEvents.length > this.store.maxChangeEvents) {
      this.store.changeEvents.shift();
    }
    return record;
  }

  recent(limit = 100): ChangeEvent[] {
    return this.store.changeEvents.slice(-limit).reverse();
  }

  bySource(sourceId: number, limit = 100): ChangeEvent[] {
    return this.store.changeEvents.filter(e => e.sourceId === sourceId).slice(-limit).reverse();
  }

  byDataset(datasetKey: string, limit = 100): ChangeEvent[] {
    return this.store.changeEvents.filter(e => e.datasetKey === datasetKey).slice(-limit).reverse();
  }

  stats() {
    const events = this.store.changeEvents;
    const byOp: Record<string, number> = {};
    for (const e of events) byOp[e.operation] = (byOp[e.operation] ?? 0) + 1;
    return { total: events.length, byOperation: byOp };
  }
}

// ════════════════════════════════════════════════════════════════
// DATA PRODUCT REGISTRY
// ════════════════════════════════════════════════════════════════

class DataProductRegistry {
  constructor(private store: FabricStore) {}

  register(product: Omit<DataProduct, "id">): DataProduct {
    const id = this.store.nextProductId++;
    const record: DataProduct = { id, ...product };
    this.store.products.set(id, record);
    this.store.productsByKey.set(product.productKey, record);
    return record;
  }

  get(idOrKey: number | string): DataProduct | undefined {
    if (typeof idOrKey === "number") return this.store.products.get(idOrKey);
    return this.store.productsByKey.get(idOrKey);
  }

  all(): DataProduct[] {
    return Array.from(this.store.products.values());
  }

  byDomain(domain: string): DataProduct[] {
    return this.all().filter(p => p.domain === domain);
  }

  byStatus(status: DataProduct["status"]): DataProduct[] {
    return this.all().filter(p => p.status === status);
  }
}

// ════════════════════════════════════════════════════════════════
// DATA FABRIC ORCHESTRATOR
// ════════════════════════════════════════════════════════════════

export class DataFabricPlatform {
  private store = new FabricStore();

  connectors = new ConnectorRegistry(this.store);
  ingestion = new IngestionEngine(this.store);
  datasets = new DatasetRegistry(this.store);
  canonical = new CanonicalModel(this.store);
  identity = new IdentityResolutionEngine(this.store);
  pipelines = new PipelineEngine(this.store);
  lineage = new LineageEngine(this.store);
  quality = new QualityEngine(this.store);
  freshness = new FreshnessTracker(this.store);
  writeBack = new WriteBackEngine(this.store);
  changeEvents = new ChangeEventStore(this.store);
  products = new DataProductRegistry(this.store);

  overview() {
    return {
      connectors: this.connectors.health(),
      ingestion: this.ingestion.stats(),
      datasets: this.datasets.summary(),
      identity: this.identity.stats(),
      lineage: this.lineage.graphSummary(),
      quality: this.quality.summary(),
      freshness: this.freshness.summary(),
      changeEvents: this.changeEvents.stats(),
      products: {
        total: this.products.all().length,
        ga: this.products.byStatus("ga").length,
        beta: this.products.byStatus("beta").length,
      },
    };
  }
}

export const dataFabric = new DataFabricPlatform();
