// Lazy re-exports for governance pages (admin-only surfaces)
export { default as UsersPage } from "./UsersPage";
export { default as RolesPage } from "./RolesPage";
export { default as PermissionsPage } from "./PermissionsPage";
export { default as AuditLogsPage } from "./AuditLogsPage";
export { default as StateHistoryPage } from "./StateHistoryPage";
export { default as DomainEventsPage } from "./DomainEventsPage";
export { default as WebhooksPage } from "./WebhooksPage";
export { default as WebhookDeliveriesPage } from "./WebhookDeliveriesPage";
export { default as IntegrationsPage } from "./IntegrationsPage";
export { default as IntegrationSyncLogsPage } from "./IntegrationSyncLogsPage";
export { default as FeatureFlagsPage } from "./FeatureFlagsPage";
export { default as HealthChecksPage } from "./HealthChecksPage";
export { default as ValidationsLogPage } from "./ValidationsLogPage";
export { default as ConfigEntriesPage } from "./ConfigEntriesPage";
export { default as QueueJobsPage } from "./QueueJobsPage";
export { default as SLATimersPage } from "./SLATimersPage";
export { default as EscalationRulesPage } from "./EscalationRulesPage";
export { default as SecurityEventsPage } from "./SecurityEventsPage";
