import React from "react";
import {
  Plug, Globe, Phone, MessageSquare, Mail, Facebook, Smartphone, Link2,
  ArrowLeftRight,
  Zap, Code2, CreditCard, BarChart3, Bot, Calendar, FileSignature,
  Video, Webhook, ShoppingCart, FileSpreadsheet, Package, Send, Activity,
  FileCode, Key, Layers, Database, Cloud, Cpu, GitBranch, Monitor, Users,
  TrendingUp, Bell, MessageCircle, Headphones, Megaphone, Share2,
} from "lucide-react";

export interface IntegrationCategory {
  id: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
}

export interface IntegrationCard {
  slug: string;
  name: string;
  nameEn: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  bgColor: string;
  category: string;
  description: string;
  features: string[];
  tier: "free" | "pro" | "enterprise";
  defaultBaseUrl: string;
  defaultAuthMethod: string;
  docUrl?: string;
  fields: IntegrationField[];
  status?: "available" | "requires_backend_setup";
  statusNote?: string;
}

export interface IntegrationField {
  key: string;
  label: string;
  type: "text" | "password" | "url" | "email" | "select" | "textarea";
  placeholder?: string;
  required?: boolean;
  options?: { value: string; label: string }[];
  configPath: "authConfig" | "defaultHeaders" | "root";
  helpText?: string;
}

export const TIER_LABELS: Record<string, { label: string; color: string }> = {
  free: { label: "Free", color: "bg-green-500/10 text-green-400 border-green-500/20" },
  pro: { label: "Pro", color: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  enterprise: { label: "Enterprise", color: "bg-purple-500/10 text-purple-400 border-purple-500/20" },
};

export const CATEGORIES: IntegrationCategory[] = [
  { id: "all", label: "הכל", icon: Layers, color: "text-foreground" },
  { id: "communication", label: "תקשורת", icon: MessageSquare, color: "text-green-400" },
  { id: "payments", label: "תשלומים", icon: CreditCard, color: "text-blue-400" },
  { id: "productivity", label: "פרודוקטיביות", icon: Zap, color: "text-yellow-400" },
  { id: "marketing", label: "שיווק", icon: Megaphone, color: "text-purple-400" },
  { id: "ai", label: "בינה מלאכותית", icon: Bot, color: "text-cyan-400" },
  { id: "development", label: "פיתוח ו-API", icon: Code2, color: "text-orange-400" },
];

export const INTEGRATIONS: IntegrationCard[] = [
  {
    slug: "whatsapp",
    name: "WhatsApp Business",
    nameEn: "WhatsApp Business API",
    icon: MessageSquare,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    category: "communication",
    description: "שליחת הודעות WhatsApp ללקוחות וספקים עם Bot 24/7 חכם, תבניות מאושרות Meta, ומעקב קריאות",
    features: ["Bot אוטומטי 24/7", "תבניות Meta מאושרות", "מעקב משלוחים", "הודעות קבוצתיות"],
    tier: "pro",
    defaultBaseUrl: "https://graph.facebook.com/v18.0",
    defaultAuthMethod: "bearer",
    docUrl: "https://developers.facebook.com/docs/whatsapp",
    fields: [
      { key: "token", label: "WhatsApp Business API Token", type: "password", required: true, configPath: "authConfig", helpText: "Token מ-Meta Business Manager" },
      { key: "phoneNumberId", label: "Phone Number ID", type: "text", required: true, configPath: "authConfig" },
      { key: "businessAccountId", label: "Business Account ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "whatsapp-api",
    name: "WhatsApp API (צד שלישי)",
    nameEn: "WhatsApp Third-party API",
    icon: Smartphone,
    color: "text-green-600",
    bgColor: "bg-green-600/10",
    category: "communication",
    description: "חיבור דרך ספק צד שלישי — Green API, Twilio, 360dialog עם קלות הגדרה",
    features: ["Green API", "Twilio", "360dialog", "ללא אישור Meta"],
    tier: "free",
    defaultBaseUrl: "https://api.green-api.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "מפתח API", type: "password", required: true, configPath: "authConfig" },
      { key: "instanceId", label: "Instance ID", type: "text", required: true, configPath: "authConfig" },
      { key: "headerName", label: "שם Header", type: "text", placeholder: "Authorization", configPath: "authConfig" },
    ],
  },
  {
    slug: "facebook",
    name: "Facebook & Instagram",
    nameEn: "Facebook & Instagram",
    icon: Facebook,
    color: "text-blue-600",
    bgColor: "bg-blue-600/10",
    category: "communication",
    description: "Lead Ads API, DM Leads בזמן אמת, ניהול הודעות דירקט מ-Instagram ו-Facebook",
    features: ["Lead Ads API", "DM Leads", "Real-time Webhooks", "Instagram DM"],
    tier: "pro",
    defaultBaseUrl: "https://graph.facebook.com/v18.0",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Page Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "pageId", label: "Page ID", type: "text", required: true, configPath: "authConfig" },
      { key: "appSecret", label: "App Secret (לאימות Webhook)", type: "password", configPath: "authConfig" },
    ],
  },
  {
    slug: "gmail",
    name: "Gmail",
    nameEn: "Gmail OAuth2",
    icon: Mail,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    category: "communication",
    description: "OAuth2, קריאת תיבת דואר, סנכרון מלא, שליחת חשבוניות והצעות מחיר אוטומטית",
    features: ["OAuth2", "סנכרון תיבת דואר", "שליחה אוטומטית", "תיוג חכם"],
    tier: "free",
    defaultBaseUrl: "https://smtp.gmail.com",
    defaultAuthMethod: "basic",
    fields: [
      { key: "username", label: "כתובת Gmail", type: "email", placeholder: "user@gmail.com", required: true, configPath: "authConfig" },
      { key: "password", label: "סיסמת אפליקציה (App Password)", type: "password", placeholder: "xxxx xxxx xxxx xxxx", required: true, configPath: "authConfig", helpText: "צור ב-Google Account > Security > App Passwords" },
      { key: "fromName", label: "שם השולח", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "outlook",
    name: "Outlook / Microsoft 365",
    nameEn: "Microsoft Outlook",
    icon: Mail,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "communication",
    description: "חיבור לחשבון Microsoft 365 — שליחה וקבלת מיילים, סנכרון קלנדר, תזמון פגישות",
    features: ["Microsoft Graph API", "OAuth2", "סנכרון קלנדר", "Teams Integration"],
    tier: "pro",
    defaultBaseUrl: "https://graph.microsoft.com/v1.0",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig", helpText: "Token מ-Azure Active Directory" },
      { key: "tenantId", label: "Tenant ID", type: "text", configPath: "authConfig" },
      { key: "clientId", label: "Client ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "telephony",
    name: "טלפוניה VoIP",
    nameEn: "VoIP Telephony",
    icon: Phone,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    category: "communication",
    description: "חיבור למרכזייה טלפונית — זיהוי שיחות נכנסות, יומן שיחות, הקלטות, CTI",
    features: ["זיהוי שיחות", "יומן שיחות", "הקלטות", "Click-to-call"],
    tier: "enterprise",
    defaultBaseUrl: "https://api.voicenter.co.il",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "מפתח API", type: "password", required: true, configPath: "authConfig" },
      { key: "headerName", label: "שם Header", type: "text", placeholder: "X-API-Key", configPath: "authConfig" },
      { key: "accountId", label: "מזהה חשבון", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "slack",
    name: "Slack",
    nameEn: "Slack",
    icon: MessageCircle,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    category: "communication",
    description: "התראות Real-time, Notifications, חגיגות עסקאות, חיבור ל-Channels וצוותים",
    features: ["Real-time Alerts", "Bot Messages", "Slash Commands", "Webhooks"],
    tier: "free",
    defaultBaseUrl: "https://hooks.slack.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Bot Token / Webhook URL", type: "password", required: true, configPath: "authConfig", helpText: "xoxb-... token מ-Slack App Settings" },
      { key: "channel", label: "ערוץ ברירת מחדל", type: "text", placeholder: "#general", configPath: "authConfig" },
    ],
  },
  {
    slug: "zoom",
    name: "Zoom",
    nameEn: "Zoom",
    icon: Video,
    color: "text-blue-400",
    bgColor: "bg-blue-400/10",
    category: "communication",
    description: "תזמון פגישות Zoom אוטומטי, שליחת לינקים, שילוב הקלטות עם CRM",
    features: ["Meeting Scheduling", "Auto-links", "הקלטות", "Calendar Sync"],
    tier: "pro",
    defaultBaseUrl: "https://api.zoom.us/v2",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "JWT Token / OAuth Token", type: "password", required: true, configPath: "authConfig" },
      { key: "accountId", label: "Account ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "stripe",
    name: "Stripe",
    nameEn: "Stripe Payments",
    icon: CreditCard,
    color: "text-violet-500",
    bgColor: "bg-violet-500/10",
    category: "payments",
    description: "Payments, Invoice, Recurring billing — חיוב בינלאומי עם כל כרטיסי אשראי",
    features: ["One-time Payments", "Subscriptions", "Invoices", "Webhooks"],
    tier: "pro",
    defaultBaseUrl: "https://api.stripe.com/v1",
    defaultAuthMethod: "bearer",
    docUrl: "https://stripe.com/docs/api",
    status: "requires_backend_setup",
    statusNote: "לא מוגדר — נדרש הגדרת Stripe Secret Key בצד השרת. לא זמין לחיבור ישיר.",
    fields: [
      { key: "token", label: "Secret Key", type: "password", required: true, configPath: "authConfig", helpText: "sk_live_... מ-Stripe Dashboard" },
      { key: "webhookSecret", label: "Webhook Secret", type: "password", configPath: "authConfig", helpText: "whsec_... לאימות Webhooks" },
    ],
  },
  {
    slug: "cardcom",
    name: "Cardcom",
    nameEn: "Cardcom (Israel)",
    icon: CreditCard,
    color: "text-blue-600",
    bgColor: "bg-blue-600/10",
    category: "payments",
    description: "סליקת אשראי ישראלית — חיוב, תשלומים, חשבוניות דיגיטליות מאושרות מס הכנסה",
    features: ["סליקה מקומית", "חשבוניות מאושרות", "תשלומים", "Recurring"],
    tier: "pro",
    defaultBaseUrl: "https://secure.cardcom.solutions",
    defaultAuthMethod: "api_key",
    status: "requires_backend_setup",
    statusNote: "לא מוגדר — נדרשת הגדרה בצד השרת. יש לפנות לצוות הפיתוח להטמעת Cardcom API.",
    fields: [
      { key: "apiKey", label: "Terminal Number", type: "text", required: true, configPath: "authConfig" },
      { key: "token", label: "API Password", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "paypal",
    name: "PayPal",
    nameEn: "PayPal",
    icon: Zap,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "payments",
    description: "תשלומים בינלאומיים דרך PayPal — חיוב, החזרות, Recurring Payments",
    features: ["International Payments", "Refunds", "Subscriptions", "Webhooks"],
    tier: "pro",
    defaultBaseUrl: "https://api-m.paypal.com",
    defaultAuthMethod: "bearer",
    status: "requires_backend_setup",
    statusNote: "לא מוגדר — נדרשת הגדרה בצד השרת. PayPal דורש OAuth2 Client Credentials ב-backend.",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "clientId", label: "Client ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "rivhit",
    name: "רווחית",
    nameEn: "Rivhit",
    icon: ArrowLeftRight,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    category: "payments",
    description: "חיבור למערכת רווחית — סנכרון חשבוניות, לקוחות, פריטים, ניהול עסקאות",
    features: ["חשבוניות", "לקוחות", "עסקאות", "סנכרון מלא"],
    tier: "pro",
    defaultBaseUrl: "https://api.rivhit.co.il/online/RivhitOnlineAPI.svc",
    defaultAuthMethod: "api_key",
    status: "requires_backend_setup",
    statusNote: "לא מוגדר — נדרשת הגדרה בצד השרת. יש לפנות לצוות הפיתוח להטמעת Rivhit API.",
    fields: [
      { key: "apiKey", label: "מפתח API רווחית", type: "password", required: true, configPath: "authConfig" },
      { key: "companyId", label: "מזהה חברה", type: "text", required: true, configPath: "authConfig" },
      { key: "headerName", label: "שם Header", type: "text", placeholder: "X-API-Key", configPath: "authConfig" },
    ],
  },
  {
    slug: "google-calendar",
    name: "Google Calendar",
    nameEn: "Google Calendar",
    icon: Calendar,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "productivity",
    description: "סנכרון דו-כיווני, תזמון Meetings, Scheduling Links — כל הפגישות בלוח שנה אחד",
    features: ["סנכרון דו-כיווני", "Meeting Scheduling", "Reminders", "Team Calendar"],
    tier: "free",
    defaultBaseUrl: "https://www.googleapis.com/calendar/v3",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "OAuth Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "calendarId", label: "Calendar ID", type: "text", placeholder: "primary", configPath: "authConfig" },
    ],
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    nameEn: "Google Sheets",
    icon: FileSpreadsheet,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    category: "productivity",
    description: "ייבוא וייצוא נתונים מגיליונות Google — דוחות אוטומטיים, עדכון נתונים בזמן אמת",
    features: ["ייצוא דוחות", "ייבוא נתונים", "עדכון אוטומטי", "Service Account"],
    tier: "free",
    defaultBaseUrl: "https://sheets.googleapis.com/v4/spreadsheets",
    defaultAuthMethod: "bearer",
    status: "requires_backend_setup",
    statusNote: "לא מוגדר — נדרש Service Account של Google או OAuth2 בצד השרת. לא זמין לחיבור ישיר.",
    fields: [
      { key: "token", label: "Access Token / Service Account Key", type: "password", required: true, configPath: "authConfig" },
      { key: "spreadsheetId", label: "מזהה גיליון", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "docusign",
    name: "DocuSign",
    nameEn: "DocuSign",
    icon: FileSignature,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    category: "productivity",
    description: "E-Signature, חוזים דיגיטליים, חתימה מרחוק — ייעול תהליכי חתימת מסמכים",
    features: ["E-Signature", "Digital Contracts", "Templates", "Audit Trail"],
    tier: "enterprise",
    defaultBaseUrl: "https://www.docusign.net/restapi",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "accountId", label: "Account ID", type: "text", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "zapier",
    name: "Zapier",
    nameEn: "Zapier",
    icon: Zap,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    category: "productivity",
    description: "No-code Automation, 5000+ אינטגרציות, חיבור בין כל האפליקציות ללא קוד",
    features: ["5000+ Apps", "No-code", "Triggers & Actions", "Multi-step Zaps"],
    tier: "pro",
    defaultBaseUrl: "https://hooks.zapier.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "webhookUrl", label: "Webhook URL", type: "url", configPath: "authConfig", helpText: "URL מה-Zap שלך ב-Zapier" },
    ],
  },
  {
    slug: "make",
    name: "Make (Integromat)",
    nameEn: "Make",
    icon: GitBranch,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    category: "productivity",
    description: "No-code Automation מתקדם, תזרים נתונים חזותי, 1000+ מודולים מוכנים",
    features: ["Visual Builder", "1000+ Modules", "Error Handling", "Scheduling"],
    tier: "pro",
    defaultBaseUrl: "https://hook.eu1.make.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "webhookUrl", label: "Webhook URL", type: "url", configPath: "authConfig" },
    ],
  },
  {
    slug: "google-ads",
    name: "Google Ads",
    nameEn: "Google Ads",
    icon: Globe,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    category: "marketing",
    description: "חיבור לחשבון Google Ads — קמפיינים, דוחות ביצועים, Conversion Tracking",
    features: ["קמפיינים", "דוחות ביצועים", "Conversion Tracking", "Keywords"],
    tier: "pro",
    defaultBaseUrl: "https://googleads.googleapis.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "customerId", label: "Customer ID", type: "text", placeholder: "123-456-7890", required: true, configPath: "authConfig" },
      { key: "developerToken", label: "Developer Token", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "google-analytics",
    name: "Google Analytics GA4",
    nameEn: "Google Analytics 4",
    icon: BarChart3,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    category: "marketing",
    description: "Conversion Tracking, Goals, מדידת קמפיינים, דוחות ROI בזמן אמת",
    features: ["Conversion Tracking", "Goals", "Audiences", "Real-time Reports"],
    tier: "free",
    defaultBaseUrl: "https://analyticsdata.googleapis.com/v1beta",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "propertyId", label: "Property ID (GA4)", type: "text", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    nameEn: "Mailchimp",
    icon: Mail,
    color: "text-yellow-600",
    bgColor: "bg-yellow-600/10",
    category: "marketing",
    description: "קמפייני אימייל מרקטינג, רשימות תפוצה, Automations, ניתוח פתיחות",
    features: ["Email Campaigns", "Automations", "Segmentation", "Analytics"],
    tier: "free",
    defaultBaseUrl: "https://us1.api.mailchimp.com/3.0",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig", helpText: "מ-Mailchimp > Account > Extras > API Keys" },
      { key: "listId", label: "Audience/List ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    nameEn: "HubSpot CRM",
    icon: TrendingUp,
    color: "text-orange-600",
    bgColor: "bg-orange-600/10",
    category: "marketing",
    description: "CRM מרקטינג — Contacts, Deals, Email Marketing, Landing Pages, Analytics",
    features: ["CRM", "Email Marketing", "Landing Pages", "Lead Scoring"],
    tier: "pro",
    defaultBaseUrl: "https://api.hubapi.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Private App Token", type: "password", required: true, configPath: "authConfig" },
      { key: "portalId", label: "Portal ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    nameEn: "SendGrid",
    icon: Send,
    color: "text-blue-400",
    bgColor: "bg-blue-400/10",
    category: "marketing",
    description: "שליחת אימיילים transactional ומסיביים — חשבוניות, ניוזלטרים, התראות",
    features: ["Transactional Emails", "Newsletters", "Templates", "Analytics"],
    tier: "free",
    defaultBaseUrl: "https://api.sendgrid.com/v3",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "API Key", type: "password", required: true, configPath: "authConfig", helpText: "SG.xxx מ-SendGrid Dashboard" },
      { key: "fromEmail", label: "From Email", type: "email", configPath: "authConfig" },
    ],
  },
  {
    slug: "kimi-ai",
    name: "Kimi 2 (Moonshot AI)",
    nameEn: "Kimi AI",
    icon: Bot,
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    category: "ai",
    description: "AI Scoring ללידים, NLP, Chatbot חכם, ניסוח הצעות מחיר, ניתוח נתונים — מנוע Kimi 2",
    features: ["Kimi 2", "AI Scoring", "Chatbot", "Text Analysis"],
    tier: "pro",
    defaultBaseUrl: "https://api.moonshot.cn/v1",
    defaultAuthMethod: "bearer",
    docUrl: "https://platform.moonshot.cn/docs",
    fields: [
      { key: "token", label: "API Key", type: "password", required: true, configPath: "authConfig", helpText: "Moonshot API Key" },
      { key: "model", label: "מודל ברירת מחדל", type: "text", placeholder: "moonshot-v1-128k", configPath: "authConfig" },
    ],
  },
  {
    slug: "claude-ai",
    name: "Anthropic Claude",
    nameEn: "Claude AI",
    icon: Bot,
    color: "text-purple-400",
    bgColor: "bg-purple-400/10",
    category: "ai",
    description: "Claude AI לניתוח מסמכים, ניסוח חוזים, תגובות ללקוחות, ניתוח נתונים ארוכים",
    features: ["Claude 3.5", "Long Context", "Document Analysis", "Code Generation"],
    tier: "pro",
    defaultBaseUrl: "https://api.anthropic.com/v1",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "headerName", label: "Header Name", type: "text", placeholder: "x-api-key", configPath: "authConfig" },
    ],
  },
  {
    slug: "gemini-ai",
    name: "Google Gemini",
    nameEn: "Google Gemini",
    icon: Cpu,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "ai",
    description: "Gemini Pro לתרגום, ניתוח תמונות, יצירת תוכן, עיבוד מסמכים",
    features: ["Gemini Pro", "Vision", "Multilingual", "Code Generation"],
    tier: "pro",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "mobile-sdk-ios",
    name: "Mobile SDK iOS",
    nameEn: "iOS Mobile SDK",
    icon: Monitor,
    color: "text-muted-foreground",
    bgColor: "bg-gray-400/10",
    category: "development",
    description: "Native iOS SDK — Push Notifications, Analytics, In-App Messaging, Crash Reporting",
    features: ["Push Notifications", "Analytics", "In-App Messages", "Crash Reports"],
    tier: "enterprise",
    defaultBaseUrl: "https://sdk.technokoluzi.com/ios",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "SDK API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "bundleId", label: "Bundle ID", type: "text", placeholder: "com.company.app", configPath: "authConfig" },
    ],
  },
  {
    slug: "mobile-sdk-android",
    name: "Mobile SDK Android",
    nameEn: "Android Mobile SDK",
    icon: Smartphone,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    category: "development",
    description: "Native Android SDK — Push Notifications, Firebase, Analytics, Deep Linking",
    features: ["Push Notifications", "Firebase", "Deep Linking", "Analytics"],
    tier: "enterprise",
    defaultBaseUrl: "https://sdk.technokoluzi.com/android",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "SDK API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "packageName", label: "Package Name", type: "text", placeholder: "com.company.app", configPath: "authConfig" },
    ],
  },
  {
    slug: "rest-api-v2",
    name: "REST API v2",
    nameEn: "REST API",
    icon: Code2,
    color: "text-primary",
    bgColor: "bg-primary/10",
    category: "development",
    description: "Full API Access, JWT Auth, Rate Limiting — גישה מלאה לכל הנתונים דרך API",
    features: ["Full Access", "JWT Auth", "Rate Limiting", "OpenAPI Docs"],
    tier: "enterprise",
    defaultBaseUrl: "https://api.technokoluzi.com/v2",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "JWT Token", type: "password", required: true, configPath: "authConfig" },
      { key: "clientId", label: "Client ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "webhooks",
    name: "Webhooks",
    nameEn: "Custom Webhooks",
    icon: Webhook,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    category: "development",
    description: "הגדרת Webhooks לאירועים — לידים חדשים, שינוי סטטוס, תשלומים, חשבוניות",
    features: ["Real-time Events", "HMAC Signing", "Retry Logic", "Event Filtering"],
    tier: "pro",
    defaultBaseUrl: "https://your-server.com/webhook",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "webhookUrl", label: "Webhook URL", type: "url", required: true, configPath: "authConfig" },
      { key: "apiKey", label: "Secret Key לאימות", type: "password", configPath: "authConfig" },
    ],
  },
  {
    slug: "github",
    name: "GitHub",
    nameEn: "GitHub",
    icon: GitBranch,
    color: "text-foreground",
    bgColor: "bg-card/10",
    category: "development",
    description: "Issues, Pull Requests, Deployments — חיבור ל-Repositories לניהול פרויקטים טכניים",
    features: ["Issues", "PRs", "Actions", "Deployments"],
    tier: "free",
    defaultBaseUrl: "https://api.github.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Personal Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "owner", label: "Repository Owner", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "woocommerce",
    name: "WooCommerce",
    nameEn: "WooCommerce",
    icon: ShoppingCart,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    category: "development",
    description: "סנכרון מוצרים, הזמנות, לקוחות מחנות WooCommerce — ניהול מלאי אוטומטי",
    features: ["מוצרים", "הזמנות", "לקוחות", "מלאי"],
    tier: "pro",
    defaultBaseUrl: "https://your-store.com/wp-json/wc/v3",
    defaultAuthMethod: "basic",
    fields: [
      { key: "username", label: "Consumer Key", type: "text", required: true, configPath: "authConfig" },
      { key: "password", label: "Consumer Secret", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "shopify",
    name: "Shopify",
    nameEn: "Shopify",
    icon: ShoppingCart,
    color: "text-green-600",
    bgColor: "bg-green-600/10",
    category: "development",
    description: "חנות Shopify — הזמנות, מוצרים, לקוחות, Inventory, Shipping",
    features: ["Orders", "Products", "Inventory", "Fulfillment"],
    tier: "pro",
    defaultBaseUrl: "https://your-store.myshopify.com/admin/api/2024-01",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "shopDomain", label: "Shop Domain", type: "text", placeholder: "your-store.myshopify.com", configPath: "authConfig" },
    ],
  },
  {
    slug: "accounting",
    name: "הנהלת חשבונות",
    nameEn: "Accounting Software",
    icon: FileSpreadsheet,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
    category: "payments",
    description: "חיבור לתוכנת הנהלת חשבונות — חשבשבת, פריורטי, SAP — סנכרון מלא",
    features: ["חשבשבת", "פריורטי", "SAP", "ייצוא פקודות יומן"],
    tier: "enterprise",
    defaultBaseUrl: "https://api.hashavshevet.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "מפתח API", type: "password", required: true, configPath: "authConfig" },
      { key: "companyCode", label: "קוד חברה", type: "text", configPath: "authConfig" },
      {
        key: "provider", label: "ספק תוכנה", type: "select", configPath: "authConfig",
        options: [
          { value: "hashavshevet", label: "חשבשבת" },
          { value: "priority", label: "פריורטי" },
          { value: "sap", label: "SAP" },
          { value: "other", label: "אחר" },
        ],
      },
    ],
  },
  {
    slug: "jira",
    name: "Jira",
    nameEn: "Jira",
    icon: Layers,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "productivity",
    description: "ניהול פרויקטים ו-Issues — Tickets, Sprints, Epics — חיבור ל-Development",
    features: ["Issues", "Sprints", "Backlog", "Reporting"],
    tier: "pro",
    defaultBaseUrl: "https://your-domain.atlassian.net/rest/api/3",
    defaultAuthMethod: "basic",
    fields: [
      { key: "username", label: "Email / Username", type: "email", required: true, configPath: "authConfig" },
      { key: "password", label: "API Token", type: "password", required: true, configPath: "authConfig" },
      { key: "domain", label: "Atlassian Domain", type: "text", placeholder: "your-company", configPath: "authConfig" },
    ],
  },
  {
    slug: "notion",
    name: "Notion",
    nameEn: "Notion",
    icon: FileCode,
    color: "text-foreground",
    bgColor: "bg-card/10",
    category: "productivity",
    description: "ניהול מסמכים, Wiki, Databases — סנכרון מידע לצוות",
    features: ["Databases", "Pages", "Templates", "API Access"],
    tier: "free",
    defaultBaseUrl: "https://api.notion.com/v1",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Integration Token", type: "password", required: true, configPath: "authConfig" },
      { key: "databaseId", label: "Database ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "trello",
    name: "Trello",
    nameEn: "Trello",
    icon: Layers,
    color: "text-blue-400",
    bgColor: "bg-blue-400/10",
    category: "productivity",
    description: "ניהול משימות Kanban — Cards, Boards, Lists, Checklists לצוות",
    features: ["Boards", "Cards", "Checklists", "Automations"],
    tier: "free",
    defaultBaseUrl: "https://api.trello.com/1",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Key", type: "password", required: true, configPath: "authConfig" },
      { key: "token", label: "Token", type: "password", required: true, configPath: "authConfig" },
      { key: "boardId", label: "Board ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "twilio",
    name: "Twilio SMS",
    nameEn: "Twilio",
    icon: Phone,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    category: "communication",
    description: "שליחת SMS בינלאומית, WhatsApp, Voice Calls — תקשורת מרובת ערוצים",
    features: ["SMS", "WhatsApp", "Voice", "Video"],
    tier: "pro",
    defaultBaseUrl: "https://api.twilio.com/2010-04-01",
    defaultAuthMethod: "basic",
    fields: [
      { key: "username", label: "Account SID", type: "text", required: true, configPath: "authConfig" },
      { key: "password", label: "Auth Token", type: "password", required: true, configPath: "authConfig" },
      { key: "fromNumber", label: "Twilio Phone Number", type: "text", placeholder: "+1234567890", configPath: "authConfig" },
    ],
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    nameEn: "Salesforce CRM",
    icon: Cloud,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    category: "marketing",
    description: "CRM Enterprise — Contacts, Opportunities, Leads, Reports, Dashboards",
    features: ["CRM", "Opportunities", "Reports", "Workflows"],
    tier: "enterprise",
    defaultBaseUrl: "https://login.salesforce.com/services/oauth2",
    defaultAuthMethod: "oauth2",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "instanceUrl", label: "Instance URL", type: "url", configPath: "authConfig" },
    ],
  },
  {
    slug: "aws-s3",
    name: "AWS S3",
    nameEn: "Amazon S3",
    icon: Database,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    category: "development",
    description: "אחסון קבצים ב-S3 — מסמכים, תמונות, גיבויים, CDN",
    features: ["File Storage", "CDN", "Versioning", "Access Control"],
    tier: "pro",
    defaultBaseUrl: "https://s3.amazonaws.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "Access Key ID", type: "text", required: true, configPath: "authConfig" },
      { key: "token", label: "Secret Access Key", type: "password", required: true, configPath: "authConfig" },
      { key: "bucket", label: "Bucket Name", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "firebase",
    name: "Google Firebase",
    nameEn: "Firebase",
    icon: Cpu,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    category: "development",
    description: "Push Notifications, Realtime Database, Authentication, Analytics",
    features: ["Push Notifications", "Realtime DB", "Auth", "Analytics"],
    tier: "free",
    defaultBaseUrl: "https://fcm.googleapis.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Server Key / FCM Token", type: "password", required: true, configPath: "authConfig" },
      { key: "projectId", label: "Project ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "intercom",
    name: "Intercom",
    nameEn: "Intercom",
    icon: Headphones,
    color: "text-blue-400",
    bgColor: "bg-blue-400/10",
    category: "communication",
    description: "Customer Support Chat, Live Chat, Help Desk, Automated Responses",
    features: ["Live Chat", "Help Desk", "Bots", "Analytics"],
    tier: "pro",
    defaultBaseUrl: "https://api.intercom.io",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "Access Token", type: "password", required: true, configPath: "authConfig" },
      { key: "appId", label: "App ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "chrome-extension",
    name: "תוסף Chrome",
    nameEn: "Chrome Extension",
    icon: Globe,
    color: "text-red-400",
    bgColor: "bg-red-400/10",
    category: "development",
    description: "תוסף דפדפן לאיסוף לידים מאתרים, שמירה ישירה ל-CRM, Click-to-call",
    features: ["Lead Capture", "CRM Save", "Click-to-call", "Page Scraping"],
    tier: "enterprise",
    defaultBaseUrl: "https://chrome-ext.technokoluzi.com",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "מפתח תוסף", type: "password", required: true, configPath: "authConfig" },
      { key: "headerName", label: "שם Header", type: "text", placeholder: "X-Extension-Key", configPath: "authConfig" },
    ],
  },
  {
    slug: "monday",
    name: "Monday.com",
    nameEn: "Monday.com",
    icon: Layers,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    category: "productivity",
    description: "Work OS — ניהול פרויקטים, Tasks, Timelines, Automations",
    features: ["Boards", "Tasks", "Timelines", "Automations"],
    tier: "pro",
    defaultBaseUrl: "https://api.monday.com/v2",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "API Token", type: "password", required: true, configPath: "authConfig" },
      { key: "boardId", label: "Board ID", type: "text", configPath: "authConfig" },
    ],
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    nameEn: "Pipedrive CRM",
    icon: TrendingUp,
    color: "text-green-400",
    bgColor: "bg-green-400/10",
    category: "marketing",
    description: "Sales CRM — Pipeline, Deals, Contacts, Activities, Reports",
    features: ["Pipeline", "Deals", "Contacts", "Automation"],
    tier: "pro",
    defaultBaseUrl: "https://api.pipedrive.com/v1",
    defaultAuthMethod: "api_key",
    fields: [
      { key: "apiKey", label: "API Token", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "zendesk",
    name: "Zendesk",
    nameEn: "Zendesk Support",
    icon: Headphones,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    category: "communication",
    description: "Customer Support Tickets, Help Center, Live Chat, CSAT",
    features: ["Tickets", "Help Center", "Live Chat", "CSAT"],
    tier: "enterprise",
    defaultBaseUrl: "https://your-domain.zendesk.com/api/v2",
    defaultAuthMethod: "basic",
    fields: [
      { key: "username", label: "Email/token", type: "email", required: true, configPath: "authConfig" },
      { key: "password", label: "API Token", type: "password", required: true, configPath: "authConfig" },
    ],
  },
  {
    slug: "external-erp",
    name: "ERP חיצוני",
    nameEn: "External ERP",
    icon: Link2,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    category: "development",
    description: "חיבור למערכת ERP חיצונית — REST API כללי עם מיפוי שדות מותאם",
    features: ["REST API", "Field Mapping", "Webhooks", "Custom Auth"],
    tier: "enterprise",
    defaultBaseUrl: "https://api.example.com",
    defaultAuthMethod: "bearer",
    fields: [
      { key: "token", label: "API Token", type: "password", required: true, configPath: "authConfig" },
      { key: "testEndpoint", label: "Endpoint בדיקה", type: "text", placeholder: "/health", configPath: "authConfig" },
    ],
  },
  {
    slug: "custom",
    name: "אינטגרציה מותאמת",
    nameEn: "Custom Integration",
    icon: Plug,
    color: "text-primary",
    bgColor: "bg-primary/10",
    category: "development",
    description: "בנה חיבור מותאם אישית לכל API עם הגדרות אימות גמישות",
    features: ["REST API", "GraphQL", "Custom Auth", "Field Mapping"],
    tier: "enterprise",
    defaultBaseUrl: "https://",
    defaultAuthMethod: "none",
    fields: [
      {
        key: "authMethodSelect", label: "שיטת אימות", type: "select", configPath: "root",
        options: [
          { value: "none", label: "ללא אימות" },
          { value: "api_key", label: "מפתח API" },
          { value: "bearer", label: "Bearer Token" },
          { value: "basic", label: "Basic Auth" },
        ],
      },
      { key: "token", label: "Token / API Key", type: "password", configPath: "authConfig" },
      { key: "headerName", label: "שם Header (עבור API Key)", type: "text", placeholder: "Authorization", configPath: "authConfig" },
    ],
  },
];
