import { pgTable, serial, text, integer, boolean, timestamp, jsonb, real, uniqueIndex } from "drizzle-orm/pg-core";
import { moduleEntitiesTable } from "./module-entities";

export const entityFieldsTable = pgTable("entity_fields", {
  id: serial("id").primaryKey(),
  entityId: integer("entity_id").notNull().references(() => moduleEntitiesTable.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  nameHe: text("name_he"),
  nameEn: text("name_en"),
  slug: text("slug").notNull(),
  fieldKey: text("field_key"),
  fieldType: text("field_type").notNull(),
  groupName: text("group_name"),
  description: text("description"),
  placeholder: text("placeholder"),
  helpText: text("help_text"),
  isRequired: boolean("is_required").notNull().default(false),
  isUnique: boolean("is_unique").notNull().default(false),
  isSearchable: boolean("is_searchable").notNull().default(true),
  isSortable: boolean("is_sortable").notNull().default(true),
  isFilterable: boolean("is_filterable").notNull().default(false),
  isReadOnly: boolean("is_read_only").notNull().default(false),
  isSystemField: boolean("is_system_field").notNull().default(false),
  isCalculated: boolean("is_calculated").notNull().default(false),
  formulaExpression: text("formula_expression"),
  showInList: boolean("show_in_list").notNull().default(true),
  showInForm: boolean("show_in_form").notNull().default(true),
  showInDetail: boolean("show_in_detail").notNull().default(true),
  defaultValue: text("default_value"),
  validationRules: jsonb("validation_rules").default({}),
  displayRules: jsonb("display_rules").default({}),
  options: jsonb("options").default([]),
  optionsJson: jsonb("options_json"),
  relatedEntityId: integer("related_entity_id"),
  relatedDisplayField: text("related_display_field"),
  relationType: text("relation_type"),
  sortOrder: integer("sort_order").notNull().default(0),
  fieldWidth: text("field_width").notNull().default("full"),
  settings: jsonb("settings").default({}),
  minValue: real("min_value"),
  maxValue: real("max_value"),
  maxLength: integer("max_length"),
  sectionKey: text("section_key"),
  tabKey: text("tab_key"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  uniqueIndex("entity_fields_entity_id_field_key_unique").on(table.entityId, table.fieldKey),
]);
