import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const fixedAssetsTable = pgTable("fixed_assets", {
  id: serial("id").primaryKey(),
  assetNumber: text("asset_number").notNull(),
  assetName: text("asset_name").notNull(),
  assetType: text("asset_type").default("equipment"),
  category: text("category"),
  description: text("description"),
  serialNumber: text("serial_number"),
  manufacturer: text("manufacturer"),
  model: text("model"),
  location: text("location"),
  department: text("department"),
  assignedTo: text("assigned_to"),
  purchaseDate: date("purchase_date"),
  purchasePrice: numeric("purchase_price", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  supplier: text("supplier"),
  invoiceNumber: text("invoice_number"),
  usefulLifeYears: integer("useful_life_years").default(5),
  depreciationMethod: text("depreciation_method").default("straight_line"),
  depreciationRate: numeric("depreciation_rate", { precision: 5, scale: 2 }),
  accumulatedDepreciation: numeric("accumulated_depreciation", { precision: 15, scale: 2 }).default("0"),
  currentValue: numeric("current_value", { precision: 15, scale: 2 }).default("0"),
  residualValue: numeric("residual_value", { precision: 15, scale: 2 }).default("0"),
  annualDepreciation: numeric("annual_depreciation", { precision: 15, scale: 2 }).default("0"),
  lastDepreciationDate: date("last_depreciation_date"),
  warrantyExpiry: date("warranty_expiry"),
  insurancePolicy: text("insurance_policy"),
  insuranceExpiry: date("insurance_expiry"),
  maintenanceSchedule: text("maintenance_schedule"),
  lastMaintenanceDate: date("last_maintenance_date"),
  nextMaintenanceDate: date("next_maintenance_date"),
  status: text("status").default("active"),
  disposalDate: date("disposal_date"),
  disposalPrice: numeric("disposal_price", { precision: 15, scale: 2 }),
  disposalMethod: text("disposal_method"),
  glAccount: text("gl_account"),
  costCenter: text("cost_center"),
  barcode: text("barcode"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  assetClass: text("asset_class"),
  projectId: integer("project_id"),
  depreciationStartDate: date("depreciation_start_date"),
  monthlyDepreciation: numeric("monthly_depreciation", { precision: 14, scale: 2 }).default("0"),
  revaluationAmount: numeric("revaluation_amount", { precision: 14, scale: 2 }).default("0"),
  revaluationDate: date("revaluation_date"),
  leaseContract: text("lease_contract"),
  leased: boolean("leased").default(false),
  leaseStartDate: date("lease_start_date"),
  leaseEndDate: date("lease_end_date"),
  leaseMonthlyPayment: numeric("lease_monthly_payment", { precision: 12, scale: 2 }),
  parentAssetId: integer("parent_asset_id"),
  childCount: integer("child_count").default(0),
  rfidTag: text("rfid_tag"),
  gpsEnabled: boolean("gps_enabled").default(false),
  powerRating: text("power_rating"),
  capacity: text("capacity"),
  operatingHours: numeric("operating_hours").default("0"),
  downtimeHours: numeric("downtime_hours").default("0"),
  utilizationRate: numeric("utilization_rate"),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
  modelNumber: text("model_number"),
  insuranceValue: numeric("insurance_value", { precision: 15, scale: 2 }),
  maintenanceCostYtd: numeric("maintenance_cost_ytd", { precision: 15, scale: 2 }).default("0"),
  maintenanceScheduleType: text("maintenance_schedule"),
  energyConsumptionKwh: numeric("energy_consumption_kwh", { precision: 10, scale: 2 }),
  maxOperatingHours: integer("max_operating_hours"),
  responsiblePerson: text("responsible_person"),
  qrCode: text("qr_code"),
  calibrationRequired: boolean("calibration_required").default(false),
  calibrationDate: date("calibration_date"),
  calibrationDueDate: date("calibration_due_date"),
  calibrationCertificate: text("calibration_certificate"),
  safetyInspectionDate: date("safety_inspection_date"),
  safetyInspectionDue: date("safety_inspection_due"),
  photosUrl: text("photos_url"),
  manualsUrl: text("manuals_url"),
  tags: text("tags"),
});
