import { pgTable, serial, text, numeric, timestamp, date, integer, boolean, varchar } from "drizzle-orm/pg-core";

export const goodsReceiptsTable = pgTable("goods_receipts", {
  id: serial("id").primaryKey(),
  receiptNumber: text("receipt_number").notNull().unique(),
  orderId: integer("order_id"),
  supplierId: integer("supplier_id").notNull(),
  supplierName: varchar("supplier_name", { length: 255 }),
  purchaseOrderNumber: varchar("purchase_order_number", { length: 50 }),
  receiptDate: date("receipt_date").defaultNow(),
  status: text("status").notNull().default("חדש"),
  receivedBy: text("received_by"),
  warehouseLocation: text("warehouse_location"),
  deliveryNoteNumber: text("delivery_note_number"),
  deliveryNoteDate: date("delivery_note_date"),
  vehicleNumber: text("vehicle_number"),
  driverName: varchar("driver_name", { length: 200 }),
  driverId: varchar("driver_id", { length: 20 }),
  unloadingMethod: varchar("unloading_method", { length: 50 }),
  dockNumber: varchar("dock_number", { length: 20 }),
  arrivalTime: timestamp("arrival_time", { withTimezone: true }),
  unloadingCompleteTime: timestamp("unloading_complete_time", { withTimezone: true }),
  totalPackages: integer("total_packages"),
  totalWeightKg: numeric("total_weight_kg", { precision: 12, scale: 3 }),
  totalPallets: integer("total_pallets"),
  inspector: text("inspector"),
  overallQuality: text("overall_quality").default("תקין"),
  inspectionRequired: boolean("inspection_required").default(true),
  inspectionStatus: varchar("inspection_status", { length: 30 }).default("pending"),
  inspectionDate: date("inspection_date"),
  inspectionBy: varchar("inspection_by", { length: 200 }),
  acceptedQuantity: numeric("accepted_quantity", { precision: 15, scale: 3 }),
  rejectedQuantity: numeric("rejected_quantity", { precision: 15, scale: 3 }).default("0"),
  rejectionReason: text("rejection_reason"),
  damagedQuantity: numeric("damaged_quantity", { precision: 15, scale: 3 }).default("0"),
  damageDescription: text("damage_description"),
  damagePhotosUrl: text("damage_photos_url"),
  temperatureCheck: numeric("temperature_check", { precision: 6, scale: 2 }),
  humidityCheck: numeric("humidity_check", { precision: 5, scale: 2 }),
  certificateOfConformity: boolean("certificate_of_conformity").default(false),
  materialTestReport: boolean("material_test_report").default(false),
  materialCertificateNumber: varchar("material_certificate_number", { length: 100 }),
  batchNumber: varchar("batch_number", { length: 50 }),
  heatNumber: varchar("heat_number", { length: 50 }),
  countryOfOrigin: varchar("country_of_origin", { length: 50 }),
  customsEntryNumber: varchar("customs_entry_number", { length: 50 }),
  quarantine: boolean("quarantine").default(false),
  quarantineReleaseDate: date("quarantine_release_date"),
  quarantineReleasedBy: varchar("quarantine_released_by", { length: 200 }),
  warehouseId: integer("warehouse_id"),
  shelfLocation: varchar("shelf_location", { length: 50 }),
  binLocation: varchar("bin_location", { length: 50 }),
  inventoryUpdated: boolean("inventory_updated").default(false),
  invoiceVerified: boolean("invoice_verified").default(false),
  supplierInvoiceNumber: varchar("supplier_invoice_number", { length: 50 }),
  supplierInvoiceDate: date("supplier_invoice_date"),
  totalAmount: numeric("total_amount", { precision: 15, scale: 2 }),
  currency: varchar("currency", { length: 10 }).default("ILS"),
  lineItemsJson: text("line_items_json"),
  photosUrl: text("photos_url"),
  approvedBy: varchar("approved_by", { length: 255 }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const goodsReceiptItemsTable = pgTable("goods_receipt_items", {
  id: serial("id").primaryKey(),
  receiptId: integer("receipt_id").notNull(),
  orderItemId: integer("order_item_id"),
  materialId: integer("material_id"),
  itemCode: text("item_code"),
  itemDescription: text("item_description").notNull(),
  expectedQuantity: numeric("expected_quantity").default("0"),
  receivedQuantity: numeric("received_quantity").notNull().default("0"),
  unit: text("unit").default("יחידה"),
  qualityStatus: text("quality_status").default("תקין"),
  lotNumber: text("lot_number"),
  serialNumber: text("serial_number"),
  conditionNotes: text("condition_notes"),
  photoUrls: text("photo_urls"),
  storageLocation: text("storage_location"),
  expiryDate: date("expiry_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const inventoryTransactionsTable = pgTable("inventory_transactions", {
  id: serial("id").primaryKey(),
  materialId: integer("material_id").notNull(),
  transactionType: text("transaction_type").notNull(),
  quantity: numeric("quantity").notNull(),
  referenceType: text("reference_type"),
  referenceId: integer("reference_id"),
  warehouseLocation: text("warehouse_location"),
  notes: text("notes"),
  performedBy: text("performed_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  unitCost: numeric("unit_cost"),
  balanceAfter: numeric("balance_after"),
  batchNumber: varchar("batch_number", { length: 50 }),
  lotNumber: varchar("lot_number", { length: 50 }),
  serialNumber: varchar("serial_number", { length: 50 }),
  totalCost: numeric("total_cost", { precision: 15, scale: 2 }),
  sourceWarehouse: varchar("source_warehouse", { length: 50 }),
  destinationWarehouse: varchar("destination_warehouse", { length: 50 }),
  workOrderId: integer("work_order_id"),
  purchaseOrderId: integer("purchase_order_id"),
  salesOrderId: integer("sales_order_id"),
  approvedBy: varchar("approved_by", { length: 255 }),
  qualityStatus: varchar("quality_status", { length: 20 }),
  expiryDate: date("expiry_date"),
  costCenter: varchar("cost_center", { length: 50 }),
  materialName: varchar("material_name", { length: 200 }),
  unit: varchar("unit", { length: 20 }),
  currency: varchar("currency", { length: 10 }).default("ILS"),
  exchangeRate: numeric("exchange_rate", { precision: 10, scale: 4 }),
  inspectionStatus: varchar("inspection_status", { length: 50 }),
  shelfLocation: varchar("shelf_location", { length: 50 }),
  palletNumber: varchar("pallet_number", { length: 50 }),
  weightKg: numeric("weight_kg", { precision: 10, scale: 3 }),
  temperature: numeric("temperature", { precision: 6, scale: 2 }),
  humidity: numeric("humidity", { precision: 5, scale: 2 }),
  documentNumber: varchar("document_number", { length: 50 }),
  documentType: varchar("document_type", { length: 30 }),
  goodsReceiptId: integer("goods_receipt_id"),
  supplierId: integer("supplier_id"),
  customerId: integer("customer_id"),
  projectId: integer("project_id"),
  reasonCode: varchar("reason_code", { length: 50 }),
  adjustmentType: varchar("adjustment_type", { length: 30 }),
  countedQuantity: numeric("counted_quantity", { precision: 15, scale: 3 }),
  varianceQuantity: numeric("variance_quantity", { precision: 15, scale: 3 }),
  fifoCost: numeric("fifo_cost", { precision: 15, scale: 2 }),
  avgCost: numeric("avg_cost", { precision: 15, scale: 2 }),
  binLocation: varchar("bin_location", { length: 50 }),
  zone: varchar("zone", { length: 30 }),
  isReversal: boolean("is_reversal").default(false),
  reversalOfId: integer("reversal_of_id"),
  posted: boolean("posted").default(true),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
});
