import { pgTable, serial, text, numeric, timestamp, integer } from "drizzle-orm/pg-core";

export const importCostCalculationsTable = pgTable("import_cost_calculations", {
  id: serial("id").primaryKey(),
  calcNumber: text("calc_number").notNull().unique(),
  calcName: text("calc_name").notNull(),
  status: text("status").notNull().default("טיוטה"),
  linkedImportOrderId: integer("linked_import_order_id"),
  linkedSupplier: text("linked_supplier"),
  supplierCountry: text("supplier_country"),
  productName: text("product_name").notNull(),
  productDescription: text("product_description"),
  hsCode: text("hs_code"),
  quantity: numeric("quantity", { precision: 15, scale: 3 }).notNull().default("1"),
  unitType: text("unit_type").default("יחידה"),
  unitWeightKg: numeric("unit_weight_kg", { precision: 15, scale: 3 }).default("0"),
  totalWeightKg: numeric("total_weight_kg", { precision: 15, scale: 3 }).default("0"),
  currency: text("currency").notNull().default("USD"),
  exchangeRate: numeric("exchange_rate", { precision: 10, scale: 4 }).default("3.6"),
  productCostPerUnit: numeric("product_cost_per_unit", { precision: 15, scale: 2 }).notNull().default("0"),
  totalProductCost: numeric("total_product_cost", { precision: 15, scale: 2 }).default("0"),
  shippingMethod: text("shipping_method").default("ים"),
  shippingCost: numeric("shipping_cost", { precision: 15, scale: 2 }).default("0"),
  containerType: text("container_type"),
  containerCount: integer("container_count").default(1),
  insuranceRate: numeric("insurance_rate", { precision: 5, scale: 3 }).default("0.5"),
  insuranceCost: numeric("insurance_cost", { precision: 15, scale: 2 }).default("0"),
  customsDutyRate: numeric("customs_duty_rate", { precision: 5, scale: 2 }).default("0"),
  customsDutyAmount: numeric("customs_duty_amount", { precision: 15, scale: 2 }).default("0"),
  purchaseTaxRate: numeric("purchase_tax_rate", { precision: 5, scale: 2 }).default("0"),
  purchaseTaxAmount: numeric("purchase_tax_amount", { precision: 15, scale: 2 }).default("0"),
  vatRate: numeric("vat_rate", { precision: 5, scale: 2 }).default("18"),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  portFees: numeric("port_fees", { precision: 15, scale: 2 }).default("0"),
  storageFees: numeric("storage_fees", { precision: 15, scale: 2 }).default("0"),
  inspectionFees: numeric("inspection_fees", { precision: 15, scale: 2 }).default("0"),
  inlandTransport: numeric("inland_transport", { precision: 15, scale: 2 }).default("0"),
  handlingFees: numeric("handling_fees", { precision: 15, scale: 2 }).default("0"),
  unloadingFees: numeric("unloading_fees", { precision: 15, scale: 2 }).default("0"),
  customsBrokerFee: numeric("customs_broker_fee", { precision: 15, scale: 2 }).default("0"),
  forwardingAgentFee: numeric("forwarding_agent_fee", { precision: 15, scale: 2 }).default("0"),
  agentCommissionRate: numeric("agent_commission_rate", { precision: 5, scale: 2 }).default("0"),
  agentCommissionAmount: numeric("agent_commission_amount", { precision: 15, scale: 2 }).default("0"),
  bankCharges: numeric("bank_charges", { precision: 15, scale: 2 }).default("0"),
  lcCharges: numeric("lc_charges", { precision: 15, scale: 2 }).default("0"),
  documentationFees: numeric("documentation_fees", { precision: 15, scale: 2 }).default("0"),
  otherCosts: numeric("other_costs", { precision: 15, scale: 2 }).default("0"),
  otherCostsDescription: text("other_costs_description"),
  totalFreightCosts: numeric("total_freight_costs", { precision: 15, scale: 2 }).default("0"),
  totalTaxesDuties: numeric("total_taxes_duties", { precision: 15, scale: 2 }).default("0"),
  totalPortFees: numeric("total_port_fees", { precision: 15, scale: 2 }).default("0"),
  totalAgentFees: numeric("total_agent_fees", { precision: 15, scale: 2 }).default("0"),
  totalFinancialCosts: numeric("total_financial_costs", { precision: 15, scale: 2 }).default("0"),
  totalOtherCosts: numeric("total_other_costs", { precision: 15, scale: 2 }).default("0"),
  totalLandedCost: numeric("total_landed_cost", { precision: 15, scale: 2 }).default("0"),
  landedCostPerUnit: numeric("landed_cost_per_unit", { precision: 15, scale: 2 }).default("0"),
  landedCostPerKg: numeric("landed_cost_per_kg", { precision: 15, scale: 2 }).default("0"),
  costMarkupPercentage: numeric("cost_markup_percentage", { precision: 5, scale: 2 }).default("0"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
