import { pgTable, serial, text, integer, numeric, timestamp, varchar, date, boolean } from "drizzle-orm/pg-core";

export const performanceReviewsTable = pgTable("performance_reviews", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull(),
  reviewerId: integer("reviewer_id").notNull(),
  reviewPeriod: varchar("review_period", { length: 20 }).notNull(),
  reviewYear: integer("review_year").notNull(),
  reviewType: varchar("review_type", { length: 30 }).default("annual"),
  status: varchar("status", { length: 30 }).default("draft"),
  overallRating: numeric("overall_rating", { precision: 3, scale: 1 }),
  performanceScore: numeric("performance_score", { precision: 5, scale: 2 }),
  qualityScore: numeric("quality_score", { precision: 3, scale: 1 }),
  attendanceScore: numeric("attendance_score", { precision: 3, scale: 1 }),
  teamworkScore: numeric("teamwork_score", { precision: 3, scale: 1 }),
  initiativeScore: numeric("initiative_score", { precision: 3, scale: 1 }),
  safetyScore: numeric("safety_score", { precision: 3, scale: 1 }),
  strengths: text("strengths"),
  areasForImprovement: text("areas_for_improvement"),
  goals: text("goals"),
  employeeComments: text("employee_comments"),
  reviewerComments: text("reviewer_comments"),
  managerComments: text("manager_comments"),
  actionPlan: text("action_plan"),
  salaryRecommendation: text("salary_recommendation"),
  promotionRecommendation: boolean("promotion_recommendation").default(false),
  trainingNeeds: text("training_needs"),
  reviewDate: date("review_date"),
  acknowledgedAt: timestamp("acknowledged_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});
