import { pgTable, serial, text, integer, numeric, timestamp, boolean, varchar, date } from "drizzle-orm/pg-core";

export const productCategoriesTable = pgTable("product_categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  icon: text("icon").default("Package"),
  color: text("color").default("#3b82f6"),
  description: text("description"),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const productsTable = pgTable("products", {
  id: serial("id").primaryKey(),
  productNumber: text("product_number").notNull().unique(),
  productName: text("product_name").notNull(),
  categoryId: integer("category_id").notNull().references(() => productCategoriesTable.id),
  description: text("description"),
  imagePath: text("image_path"),
  pricePerSqmBeforeVat: numeric("price_per_sqm_before_vat").default("0"),
  materialsCostPerSqm: numeric("materials_cost_per_sqm").default("0"),
  pricePerSqmAfterVat: numeric("price_per_sqm_after_vat").default("0"),
  grossProfit: numeric("gross_profit").default("0"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  unit: text("unit").default("יחידה"),
  minStock: numeric("min_stock").default("0"),
  maxStock: numeric("max_stock").default("0"),
  currentStock: numeric("current_stock").default("0"),
  sku: varchar("sku", { length: 50 }),
  barcode: varchar("barcode", { length: 50 }),
  brand: varchar("brand", { length: 100 }),
  model: varchar("model", { length: 100 }),
  weightKg: numeric("weight_kg"),
  dimensions: varchar("dimensions", { length: 100 }),
  color: varchar("color", { length: 50 }),
  materialType: varchar("material_type", { length: 100 }),
  finishType: varchar("finish_type", { length: 100 }),
  thicknessMm: numeric("thickness_mm"),
  widthMm: numeric("width_mm"),
  heightMm: numeric("height_mm"),
  lengthMm: numeric("length_mm"),
  leadTimeDays: integer("lead_time_days"),
  warrantyMonths: integer("warranty_months"),
  supplierId: integer("supplier_id"),
  supplierName: varchar("supplier_name", { length: 200 }),
  costPrice: numeric("cost_price"),
  sellingPrice: numeric("selling_price"),
  taxRate: numeric("tax_rate").default("18"),
  isActive: boolean("is_active").default(true),
  certification: varchar("certification", { length: 200 }),
  imageUrl: text("image_url"),
  technicalDrawingUrl: text("technical_drawing_url"),
  productType: varchar("product_type", { length: 50 }).default("finished_good"),
  productGroup: varchar("product_group", { length: 100 }),
  productFamily: varchar("product_family", { length: 100 }),
  glassType: varchar("glass_type", { length: 100 }),
  glassThicknessMm: numeric("glass_thickness_mm"),
  glassColor: varchar("glass_color", { length: 50 }),
  glassTreatment: varchar("glass_treatment", { length: 100 }),
  frameType: varchar("frame_type", { length: 100 }),
  frameMaterial: varchar("frame_material", { length: 100 }),
  frameProfile: varchar("frame_profile", { length: 100 }),
  frameColor: varchar("frame_color", { length: 50 }),
  coatingType: varchar("coating_type", { length: 100 }),
  surfaceTreatment: varchar("surface_treatment", { length: 100 }),
  thermalBreak: boolean("thermal_break").default(false),
  acousticRating: varchar("acoustic_rating", { length: 30 }),
  fireRating: varchar("fire_rating", { length: 30 }),
  windResistance: varchar("wind_resistance", { length: 30 }),
  waterResistance: varchar("water_resistance", { length: 30 }),
  securityLevel: varchar("security_level", { length: 30 }),
  energyRating: varchar("energy_rating", { length: 30 }),
  siStandard: varchar("si_standard", { length: 50 }),
  isoStandard: varchar("iso_standard", { length: 50 }),
  productionTimeHours: numeric("production_time_hours"),
  assemblyTimeHours: numeric("assembly_time_hours"),
  installationTimeHours: numeric("installation_time_hours"),
  minOrderQuantity: numeric("min_order_quantity").default("1"),
  maxDimensionWidthMm: numeric("max_dimension_width_mm"),
  maxDimensionHeightMm: numeric("max_dimension_height_mm"),
  standardWidthMm: numeric("standard_width_mm"),
  standardHeightMm: numeric("standard_height_mm"),
  requiresMeasurement: boolean("requires_measurement").default(true),
  requiresInstallation: boolean("requires_installation").default(true),
  installationType: varchar("installation_type", { length: 50 }),
  hardwareIncluded: boolean("hardware_included").default(true),
  hardwareType: varchar("hardware_type", { length: 100 }),
  handleType: varchar("handle_type", { length: 100 }),
  lockType: varchar("lock_type", { length: 100 }),
  hingeType: varchar("hinge_type", { length: 100 }),
  sealType: varchar("seal_type", { length: 100 }),
  openingDirection: varchar("opening_direction", { length: 30 }),
  openingType: varchar("opening_type", { length: 50 }),
  panelsCount: integer("panels_count").default(1),
  customDesign: boolean("custom_design").default(false),
  drawingRequired: boolean("drawing_required").default(false),
  drawingUrl: text("drawing_url"),
  bomId: integer("bom_id"),
  productionLine: varchar("production_line", { length: 100 }),
  qualityStandard: varchar("quality_standard", { length: 100 }),
  testRequired: boolean("test_required").default(false),
  packagingType: varchar("packaging_type", { length: 50 }),
  packagingInstructions: text("packaging_instructions"),
  transportRequirements: text("transport_requirements"),
  countryOfOrigin: varchar("country_of_origin", { length: 50 }).default("ישראל"),
  customsCode: varchar("customs_code", { length: 20 }),
  discontinued: boolean("discontinued").default(false),
  discontinuedDate: date("discontinued_date"),
  replacementProductId: integer("replacement_product_id"),
  safetyDataSheetUrl: text("safety_data_sheet_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const productMaterialsTable = pgTable("product_materials", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").notNull().references(() => productsTable.id),
  materialId: integer("material_id").notNull(),
  quantityPerSqm: numeric("quantity_per_sqm").notNull().default("1"),
  unitCost: numeric("unit_cost").default("0"),
  totalCost: numeric("total_cost").default("0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
