import { pgTable, serial, text, numeric, integer, timestamp, date, boolean } from "drizzle-orm/pg-core";

export const bomHeadersTable = pgTable("bom_headers", {
  id: serial("id").primaryKey(),
  bomNumber: text("bom_number").notNull().unique(),
  name: text("name").notNull(),
  productName: text("product_name"),
  productSku: text("product_sku"),
  version: text("version").notNull().default("1.0"),
  status: text("status").notNull().default("draft"),
  description: text("description"),
  totalCost: numeric("total_cost").default("0"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  category: text("category"),
  effectiveDate: date("effective_date"),
  expiryDate: date("expiry_date"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  laborCost: numeric("labor_cost").default("0"),
  overheadCost: numeric("overhead_cost").default("0"),
  cycleTimeMinutes: numeric("cycle_time_minutes"),
  yieldPercent: numeric("yield_percent").default("100"),
  routingNotes: text("routing_notes"),
  revisionNumber: integer("revision_number").default(1),
  unit: text("unit").default("יחידה"),
  batchSize: numeric("batch_size").default("1"),
  drawingNumber: text("drawing_number"),
  customerName: text("customer_name"),
  projectId: integer("project_id"),
});

export const bomLinesTable = pgTable("bom_lines", {
  id: serial("id").primaryKey(),
  bomHeaderId: integer("bom_header_id").notNull(),
  componentName: text("component_name").notNull(),
  componentSku: text("component_sku"),
  quantity: numeric("quantity").notNull().default("1"),
  unit: text("unit").notNull().default("יחידה"),
  unitCost: numeric("unit_cost").default("0"),
  totalCost: numeric("total_cost").default("0"),
  level: integer("level").notNull().default(1),
  parentLineId: integer("parent_line_id"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  materialId: integer("material_id"),
  scrapFactor: numeric("scrap_factor").default("0"),
  isCritical: boolean("is_critical").default(false),
  substituteMaterial: text("substitute_material"),
  positionNumber: integer("position_number"),
  operationNumber: integer("operation_number"),
  leadTimeOffsetDays: integer("lead_time_offset_days").default(0),
  warehouse: text("warehouse"),
  phantom: boolean("phantom").default(false),
  effectiveDate: date("effective_date"),
  expiryDate: date("expiry_date"),
});
