import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const projectTasksTable = pgTable("project_tasks", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  parentTaskId: integer("parent_task_id"),
  wbsCode: text("wbs_code"),
  sortOrder: integer("sort_order").default(0),
  title: text("title").notNull(),
  description: text("description"),
  assignee: text("assignee"),
  milestoneId: integer("milestone_id"),
  status: text("status").notNull().default("todo"),
  priority: text("priority").default("medium"),
  dueDate: date("due_date"),
  estimatedHours: numeric("estimated_hours", { precision: 8, scale: 2 }),
  actualHours: numeric("actual_hours", { precision: 8, scale: 2 }),
  tags: text("tags"),
  duration: integer("duration").default(1),
  plannedStart: date("planned_start"),
  plannedEnd: date("planned_end"),
  actualStart: date("actual_start"),
  actualEnd: date("actual_end"),
  earlyStart: date("early_start"),
  earlyFinish: date("early_finish"),
  lateStart: date("late_start"),
  lateFinish: date("late_finish"),
  totalFloat: integer("total_float"),
  freeFloat: integer("free_float"),
  isCritical: boolean("is_critical").default(false),
  isMilestone: boolean("is_milestone").default(false),
  baselineStart: date("baseline_start"),
  baselineEnd: date("baseline_end"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
