import { pgTable, serial, text, numeric, timestamp, date, integer, boolean, varchar } from "drizzle-orm/pg-core";
import { suppliersTable } from "./suppliers";

export const purchaseOrdersTable = pgTable("purchase_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  supplierId: integer("supplier_id").notNull().references(() => suppliersTable.id),
  requestId: integer("request_id"),
  status: text("status").notNull().default("draft"),
  orderDate: date("order_date").defaultNow(),
  expectedDelivery: date("expected_delivery"),
  totalAmount: numeric("total_amount").default("0"),
  currency: text("currency").default("ILS"),
  paymentTerms: text("payment_terms"),
  shippingAddress: text("shipping_address"),
  shippingMethod: text("shipping_method"),
  totalBeforeTax: numeric("total_before_tax"),
  taxAmount: numeric("tax_amount"),
  createdBy: text("created_by"),
  notes: text("notes"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  priority: text("priority").default("normal"),
  discountAmount: numeric("discount_amount").default("0"),
  receivedDate: date("received_date"),
  deliveryTerms: text("delivery_terms"),
  warehouse: text("warehouse"),
  projectId: integer("project_id"),
  costCenter: text("cost_center"),
  department: text("department"),
  internalNotes: text("internal_notes"),
  referenceNumber: text("reference_number"),
  cancelledReason: text("cancelled_reason"),
  paymentStatus: text("payment_status").default("unpaid"),
  paidAmount: numeric("paid_amount").default("0"),
  incoterms: text("incoterms"),
  freightCost: numeric("freight_cost").default("0"),
  insuranceCost: numeric("insurance_cost").default("0"),
  customsCost: numeric("customs_cost").default("0"),
  landedCost: numeric("landed_cost").default("0"),
  qualityCheckRequired: boolean("quality_check_required").default(false),
  blanketAgreementId: integer("blanket_agreement_id"),
  revisionNumber: integer("revision_number").default(0),
  orderType: varchar("order_type", { length: 30 }).default("standard"),
  requisitionNumber: varchar("requisition_number", { length: 50 }),
  requisitionDate: date("requisition_date"),
  requestedBy: varchar("requested_by", { length: 200 }),
  buyer: varchar("buyer", { length: 200 }),
  supplierContact: varchar("supplier_contact", { length: 200 }),
  supplierPhone: varchar("supplier_phone", { length: 30 }),
  supplierEmail: varchar("supplier_email", { length: 200 }),
  shipToAddress: text("ship_to_address"),
  shipToCity: varchar("ship_to_city", { length: 100 }),
  estimatedArrival: date("estimated_arrival"),
  actualArrival: date("actual_arrival"),
  goodsReceived: boolean("goods_received").default(false),
  goodsReceivedDate: date("goods_received_date"),
  goodsReceivedBy: varchar("goods_received_by", { length: 200 }),
  invoiceReceived: boolean("invoice_received").default(false),
  invoiceNumber: varchar("invoice_number", { length: 50 }),
  invoiceDate: date("invoice_date"),
  invoiceAmount: numeric("invoice_amount"),
  threeWayMatch: boolean("three_way_match").default(false),
  varianceAmount: numeric("variance_amount").default("0"),
  varianceReason: text("variance_reason"),
  returnReason: text("return_reason"),
  returnDate: date("return_date"),
  returnAmount: numeric("return_amount").default("0"),
  qualityIssues: text("quality_issues"),
  penaltyAmount: numeric("penalty_amount").default("0"),
  penaltyReason: text("penalty_reason"),
  totalWeightKg: numeric("total_weight_kg"),
  totalVolumeCbm: numeric("total_volume_cbm"),
  containerType: varchar("container_type", { length: 30 }),
  containerNumber: varchar("container_number", { length: 30 }),
  billOfLading: varchar("bill_of_lading", { length: 50 }),
  customsDeclaration: varchar("customs_declaration", { length: 50 }),
  exchangeRate: numeric("exchange_rate").default("1"),
  originalCurrency: varchar("original_currency", { length: 10 }).default("ILS"),
  amountInOriginalCurrency: numeric("amount_in_original_currency"),
  deletedAt: timestamp("deleted_at"),
});

export const purchaseOrderItemsTable = pgTable("purchase_order_items", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => purchaseOrdersTable.id),
  materialId: integer("material_id"),
  itemCode: text("item_code"),
  itemDescription: text("item_description").notNull(),
  quantity: numeric("quantity").notNull().default("1"),
  unit: text("unit").default("יחידה"),
  unitPrice: numeric("unit_price").notNull().default("0"),
  discountPercent: numeric("discount_percent").default("0"),
  taxPercent: numeric("tax_percent").default("18"),
  totalPrice: numeric("total_price").notNull().default("0"),
  receivedQuantity: numeric("received_quantity").default("0"),
  deliveryDate: date("delivery_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
