import { pgTable, serial, text, numeric, timestamp, integer, boolean, jsonb, date } from "drizzle-orm/pg-core";
import { rawMaterialsTable } from "./raw-materials";
import { suppliersTable } from "./suppliers";

export const demandForecastsTable = pgTable("demand_forecasts", {
  id: serial("id").primaryKey(),
  materialId: integer("material_id").notNull().references(() => rawMaterialsTable.id),
  forecastPeriod: text("forecast_period").notNull(),
  forecastDate: date("forecast_date").notNull(),
  forecastQty: numeric("forecast_qty", { precision: 15, scale: 3 }).notNull(),
  actualQty: numeric("actual_qty", { precision: 15, scale: 3 }),
  confidenceScore: numeric("confidence_score", { precision: 5, scale: 2 }).default("0"),
  seasonalFactor: numeric("seasonal_factor", { precision: 8, scale: 4 }).default("1.0"),
  trendFactor: numeric("trend_factor", { precision: 8, scale: 4 }).default("1.0"),
  method: text("method").default("moving_average"),
  dataPointsUsed: integer("data_points_used").default(0),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const reorderSuggestionsTable = pgTable("reorder_suggestions", {
  id: serial("id").primaryKey(),
  materialId: integer("material_id").notNull().references(() => rawMaterialsTable.id),
  currentReorderPoint: numeric("current_reorder_point", { precision: 15, scale: 3 }),
  suggestedReorderPoint: numeric("suggested_reorder_point", { precision: 15, scale: 3 }).notNull(),
  currentSafetyStock: numeric("current_safety_stock", { precision: 15, scale: 3 }),
  suggestedSafetyStock: numeric("suggested_safety_stock", { precision: 15, scale: 3 }).notNull(),
  currentEoq: numeric("current_eoq", { precision: 15, scale: 3 }),
  suggestedEoq: numeric("suggested_eoq", { precision: 15, scale: 3 }).notNull(),
  confidenceScore: numeric("confidence_score", { precision: 5, scale: 2 }).default("0"),
  reasoning: text("reasoning"),
  seasonalPatternDetected: boolean("seasonal_pattern_detected").default(false),
  peakMonths: text("peak_months"),
  avgDailyDemand: numeric("avg_daily_demand", { precision: 15, scale: 4 }),
  demandVariability: numeric("demand_variability", { precision: 8, scale: 4 }),
  leadTimeDays: integer("lead_time_days"),
  status: text("status").notNull().default("pending"),
  userAction: text("user_action"),
  userOverrideValue: numeric("user_override_value", { precision: 15, scale: 3 }),
  userFeedback: text("user_feedback"),
  actionBy: text("action_by"),
  actionAt: timestamp("action_at"),
  generatedAt: timestamp("generated_at").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const vmiSuppliersTable = pgTable("vmi_suppliers", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull().references(() => suppliersTable.id),
  isVmi: boolean("is_vmi").notNull().default(true),
  vmiContractNumber: text("vmi_contract_number"),
  replenishmentLeadDays: integer("replenishment_lead_days").default(3),
  reviewFrequencyDays: integer("review_frequency_days").default(7),
  performanceScore: numeric("performance_score", { precision: 5, scale: 2 }),
  lastReviewDate: date("last_review_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const vmiItemsTable = pgTable("vmi_items", {
  id: serial("id").primaryKey(),
  vmiSupplierId: integer("vmi_supplier_id").notNull().references(() => vmiSuppliersTable.id),
  materialId: integer("material_id").notNull().references(() => rawMaterialsTable.id),
  minThreshold: numeric("min_threshold", { precision: 15, scale: 3 }).notNull(),
  maxThreshold: numeric("max_threshold", { precision: 15, scale: 3 }).notNull(),
  targetLevel: numeric("target_level", { precision: 15, scale: 3 }),
  replenishmentQty: numeric("replenishment_qty", { precision: 15, scale: 3 }),
  status: text("status").notNull().default("active"),
  lastReplenishmentDate: date("last_replenishment_date"),
  lastReplenishmentQty: numeric("last_replenishment_qty", { precision: 15, scale: 3 }),
  replenishmentDueDate: date("replenishment_due_date"),
  alertSent: boolean("alert_sent").default(false),
  alertSentAt: timestamp("alert_sent_at"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const vmiReplenishmentOrdersTable = pgTable("vmi_replenishment_orders", {
  id: serial("id").primaryKey(),
  vmiItemId: integer("vmi_item_id").notNull().references(() => vmiItemsTable.id),
  materialId: integer("material_id").notNull().references(() => rawMaterialsTable.id),
  supplierId: integer("supplier_id").notNull().references(() => suppliersTable.id),
  orderNumber: text("order_number").notNull().unique(),
  quantity: numeric("quantity", { precision: 15, scale: 3 }).notNull(),
  unit: text("unit").default("יחידה"),
  stockLevelAtOrder: numeric("stock_level_at_order", { precision: 15, scale: 3 }),
  status: text("status").notNull().default("pending"),
  expectedDeliveryDate: date("expected_delivery_date"),
  actualDeliveryDate: date("actual_delivery_date"),
  deliveredQuantity: numeric("delivered_quantity", { precision: 15, scale: 3 }),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
