export interface DataFlowNode {
  id: string;
  name: string;
  nameEn: string;
  module: string;
  category: string;
  icon: string;
  description: string;
  sourceInputs: string[];
  ownedData: string[];
  derivedData: string[];
  downstreamOutputs: string[];
  aiEnrichedFields: string[];
  upstreamModules: string[];
  downstreamModules: string[];
  syncRules: string[];
  validationRules: string[];
}

export interface DataFlowEdge {
  id: string;
  from: string;
  to: string;
  label: string;
  labelEn: string;
  trigger: string;
  dataFields: string[];
  type: "event" | "pipeline" | "sync" | "derived";
}

const NODES: DataFlowNode[] = [
  {
    id: "lead",
    name: "ליד",
    nameEn: "Lead",
    module: "CRM",
    category: "crm",
    icon: "UserPlus",
    description: "נקודת כניסה ראשונית של לקוח פוטנציאלי",
    sourceInputs: ["טופס אתר", "טלפון", "הפניה", "קמפיין"],
    ownedData: ["שם", "טלפון", "אימייל", "מקור", "הערות"],
    derivedData: ["סוג פרויקט", "דחיפות", "העדפת חומר", "תקציב משוער"],
    downstreamOutputs: ["נתוני לקוח", "כוונת רכישה", "סיווג"],
    aiEnrichedFields: ["material_preference", "urgency_level", "project_type", "estimated_budget", "extracted_dimensions"],
    upstreamModules: [],
    downstreamModules: ["לקוח", "הצעת מחיר"],
    syncRules: ["המרת ליד → יצירת לקוח + חשבון AR"],
    validationRules: ["טלפון או אימייל חובה", "בדיקת כפילויות"],
  },
  {
    id: "customer",
    name: "לקוח",
    nameEn: "Customer",
    module: "CRM",
    category: "crm",
    icon: "Users",
    description: "לקוח פעיל במערכת",
    sourceInputs: ["המרת ליד", "קליטה ישירה"],
    ownedData: ["שם חברה", "איש קשר", "כתובת", "ח.פ.", "תנאי תשלום"],
    derivedData: ["סה\"כ הזמנות", "מחזור מכירות", "דירוג לקוח"],
    downstreamOutputs: ["מזהה לקוח", "פרטי חיוב", "כתובת אספקה"],
    aiEnrichedFields: ["customer_tier", "lifetime_value", "risk_score"],
    upstreamModules: ["ליד"],
    downstreamModules: ["הצעת מחיר", "הזמנת מכירה", "פרויקט", "חשבונית"],
    syncRules: ["עדכון פרטי לקוח מתפשט להזמנות פתוחות", "שינוי תנאי תשלום מעדכן AR"],
    validationRules: ["שם חובה", "בדיקת ח.פ. ייחודי"],
  },
  {
    id: "quotation",
    name: "הצעת מחיר",
    nameEn: "Quotation",
    module: "מכירות",
    category: "sales",
    icon: "FileText",
    description: "הצעת מחיר ללקוח",
    sourceInputs: ["נתוני לקוח", "דרישות פרויקט", "מחירון"],
    ownedData: ["פריטים", "מחירים", "הנחות", "תנאים"],
    derivedData: ["סה\"כ", "מע\"מ", "רווח גולמי משוער", "חומרים נדרשים"],
    downstreamOutputs: ["פריטי הזמנה", "הערכת עלות", "רשימת חומרים"],
    aiEnrichedFields: ["price_tier", "vat_amount", "amount_with_vat", "materials_required", "item_count"],
    upstreamModules: ["לקוח"],
    downstreamModules: ["הזמנת מכירה", "פרויקט"],
    syncRules: ["אישור הצעה → יצירת הזמנת מכירה", "פריטי הצעה עוברים להזמנה"],
    validationRules: ["לקוח חובה", "לפחות פריט אחד", "מחיר חיובי"],
  },
  {
    id: "sales_order",
    name: "הזמנת מכירה",
    nameEn: "Sales Order",
    module: "מכירות",
    category: "sales",
    icon: "ShoppingCart",
    description: "הזמנה מאושרת מלקוח",
    sourceInputs: ["הצעת מחיר מאושרת", "הזמנה ישירה"],
    ownedData: ["מספר הזמנה", "תאריך", "סטטוס", "פריטים"],
    derivedData: ["עלות ייצור", "רווח", "זמן אספקה", "חומרי גלם נדרשים"],
    downstreamOutputs: ["הוראות ייצור", "רשימת חומרים", "חשבונית", "תעודת משלוח"],
    aiEnrichedFields: ["production_priority", "days_until_deadline", "procurement_material_needs", "gross_margin_pct"],
    upstreamModules: ["הצעת מחיר", "לקוח"],
    downstreamModules: ["פקודת עבודה", "רכש", "חשבונית", "תעודת משלוח", "התקנה"],
    syncRules: ["אישור → יצירת פקודת עבודה", "אישור → יצירת חשבונית", "אישור → עדכון AR"],
    validationRules: ["לקוח חובה", "פריטים חובה", "אישור מנהל מעל 50,000₪"],
  },
  {
    id: "project",
    name: "פרויקט",
    nameEn: "Project",
    module: "פרויקטים",
    category: "projects",
    icon: "FolderKanban",
    description: "פרויקט ייצור/התקנה",
    sourceInputs: ["הזמנת מכירה", "נתוני לקוח", "מדידות שטח"],
    ownedData: ["שם פרויקט", "תקציב", "לו\"ז", "צוות", "אבני דרך"],
    derivedData: ["% השלמה", "סטיית תקציב", "סטיית לו\"ז"],
    downstreamOutputs: ["תוכניות ייצור", "דרישות חומרים", "לו\"ז התקנה"],
    aiEnrichedFields: ["risk_level", "completion_forecast", "budget_variance_pct"],
    upstreamModules: ["הזמנת מכירה", "לקוח"],
    downstreamModules: ["מדידות", "הנדסה", "BOM", "ייצור", "התקנה"],
    syncRules: ["השלמת אבן דרך → חישוב % מחדש", "השלמת פרויקט → חשבונית סופית"],
    validationRules: ["לקוח חובה", "תקציב חובה"],
  },
  {
    id: "measurement",
    name: "מדידות שטח",
    nameEn: "Site Measurement",
    module: "הנדסה",
    category: "engineering",
    icon: "Ruler",
    description: "מדידות באתר הלקוח",
    sourceInputs: ["פרויקט", "כתובת לקוח"],
    ownedData: ["מידות", "תמונות", "הערות שטח", "תנאי אתר"],
    derivedData: ["שטח כולל", "כמויות ייצור", "אילוצי התקנה"],
    downstreamOutputs: ["מידות מדויקות להנדסה", "אילוצים לייצור"],
    aiEnrichedFields: ["total_area_m2", "complexity_score", "access_constraints"],
    upstreamModules: ["פרויקט", "לקוח"],
    downstreamModules: ["הנדסה", "BOM", "ייצור"],
    syncRules: ["השלמת מדידה → עדכון פרויקט", "מידות → עדכון BOM"],
    validationRules: ["פרויקט חובה", "לפחות מדידה אחת"],
  },
  {
    id: "bom",
    name: "BOM - רשימת חומרים",
    nameEn: "Bill of Materials",
    module: "הנדסה",
    category: "engineering",
    icon: "List",
    description: "רשימת חומרים וכמויות לייצור",
    sourceInputs: ["מדידות", "תוכניות הנדסיות", "הזמנת מכירה"],
    ownedData: ["חומרים", "כמויות", "מפרטים טכניים"],
    derivedData: ["עלות חומרים", "משקל כולל", "זמן ייצור משוער"],
    downstreamOutputs: ["דרישות רכש", "הוראות ייצור", "עלות חומרים"],
    aiEnrichedFields: ["total_material_cost", "estimated_weight_kg", "estimated_production_hours"],
    upstreamModules: ["מדידות", "הנדסה", "הזמנת מכירה"],
    downstreamModules: ["רכש", "ייצור"],
    syncRules: ["אישור BOM → יצירת בקשות רכש", "שינוי כמויות → עדכון עלות"],
    validationRules: ["פרויקט/הזמנה חובה", "לפחות חומר אחד"],
  },
  {
    id: "purchase_order",
    name: "הזמנת רכש",
    nameEn: "Purchase Order",
    module: "רכש",
    category: "procurement",
    icon: "ShoppingBag",
    description: "הזמנה לספק",
    sourceInputs: ["BOM", "בקשת רכש", "מלאי נמוך"],
    ownedData: ["ספק", "פריטים", "מחירים", "תנאי אספקה"],
    derivedData: ["עלות כוללת", "תאריך אספקה צפוי", "חיסכון vs מחירון"],
    downstreamOutputs: ["חשבונות זכאים", "עדכון מלאי", "פקודת יומן"],
    aiEnrichedFields: ["procurement_approval_required", "procurement_budget_tier"],
    upstreamModules: ["BOM", "מלאי"],
    downstreamModules: ["מלאי", "חשבונות זכאים", "ספר ראשי"],
    syncRules: ["אישור → AP", "קבלת טובין → עדכון מלאי"],
    validationRules: ["ספק חובה", "פריטים חובה", "אישור מנהל מעל סכום"],
  },
  {
    id: "inventory",
    name: "מלאי",
    nameEn: "Inventory",
    module: "מלאי",
    category: "inventory",
    icon: "Package",
    description: "ניהול מלאי חומרי גלם ומוצרים מוגמרים",
    sourceInputs: ["קבלת טובין", "החזרות"],
    ownedData: ["כמות", "מיקום מחסן", "מספר אצווה"],
    derivedData: ["שווי מלאי", "מלאי מינימלי", "ימי מלאי"],
    downstreamOutputs: ["זמינות לייצור", "התראות מלאי נמוך"],
    aiEnrichedFields: ["days_of_stock", "reorder_prediction", "consumption_trend"],
    upstreamModules: ["רכש", "ייצור"],
    downstreamModules: ["ייצור", "רכש"],
    syncRules: ["ירידה מתחת למינימום → התראה + בקשת רכש", "קבלת טובין → עדכון כמות"],
    validationRules: ["כמות לא שלילית", "מיקום מחסן חובה"],
  },
  {
    id: "work_order",
    name: "פקודת עבודה",
    nameEn: "Work Order",
    module: "ייצור",
    category: "production",
    icon: "Wrench",
    description: "הוראת ייצור במפעל",
    sourceInputs: ["הזמנת מכירה", "BOM", "מדידות"],
    ownedData: ["שלבי ייצור", "מכונות", "עובדים", "זמנים"],
    derivedData: ["% השלמה", "עלות ייצור בפועל", "זמן ייצור"],
    downstreamOutputs: ["מוצר מוגמר", "דוח איכות", "עלות ייצור"],
    aiEnrichedFields: ["production_priority", "days_until_deadline", "total_production_area_m2"],
    upstreamModules: ["הזמנת מכירה", "BOM", "מלאי"],
    downstreamModules: ["בקרת איכות", "תעודת משלוח", "מלאי מוגמרים"],
    syncRules: ["השלמת ייצור → עדכון מלאי מוגמרים", "כשל איכות → NCR"],
    validationRules: ["הזמנה/פרויקט חובה", "חומרי גלם זמינים"],
  },
  {
    id: "quality_control",
    name: "בקרת איכות",
    nameEn: "Quality Control",
    module: "ייצור",
    category: "production",
    icon: "CheckCircle",
    description: "בדיקות איכות ואי-התאמות",
    sourceInputs: ["פקודת עבודה", "קבלת טובין"],
    ownedData: ["תוצאות בדיקה", "אי-התאמות", "פעולות מתקנות"],
    derivedData: ["אחוז עמידה", "עלות אי-התאמות"],
    downstreamOutputs: ["אישור לאספקה", "דוח NCR"],
    aiEnrichedFields: ["defect_category", "root_cause_analysis", "corrective_action_suggestion"],
    upstreamModules: ["ייצור"],
    downstreamModules: ["תעודת משלוח", "התקנה"],
    syncRules: ["אי-התאמה → NCR + התראה", "אישור QC → מוכן לאספקה"],
    validationRules: ["פקודת עבודה חובה"],
  },
  {
    id: "delivery_note",
    name: "תעודת משלוח",
    nameEn: "Delivery Note",
    module: "לוגיסטיקה",
    category: "logistics",
    icon: "Truck",
    description: "תעודת משלוח ללקוח",
    sourceInputs: ["הזמנת מכירה", "אישור QC", "מלאי מוגמרים"],
    ownedData: ["פריטים נשלחים", "כתובת אספקה", "נהג/משלוח"],
    derivedData: ["משקל כולל", "מספר חבילות", "עלות משלוח"],
    downstreamOutputs: ["אישור קבלה", "עדכון מלאי", "בסיס לחשבונית"],
    aiEnrichedFields: ["estimated_weight_kg", "delivery_item_count", "total_delivery_units"],
    upstreamModules: ["הזמנת מכירה", "ייצור", "מלאי"],
    downstreamModules: ["התקנה", "חשבונית"],
    syncRules: ["אספקה → הפחתת מלאי", "אספקה מלאה → מוכן לחשבונית"],
    validationRules: ["הזמנה חובה", "פריטים חובה", "כתובת חובה"],
  },
  {
    id: "installation",
    name: "התקנה",
    nameEn: "Installation",
    module: "התקנות",
    category: "installation",
    icon: "HardHat",
    description: "התקנה באתר הלקוח",
    sourceInputs: ["תעודת משלוח", "מדידות", "לו\"ז התקנה"],
    ownedData: ["צוות התקנה", "תאריך", "דוח התקנה", "חתימת לקוח"],
    derivedData: ["שעות התקנה", "עלות התקנה", "שביעות רצון"],
    downstreamOutputs: ["אישור השלמה", "דוח שירות", "בסיס לחשבונית סופית"],
    aiEnrichedFields: ["estimated_installation_hours", "days_until_installation", "installation_item_count"],
    upstreamModules: ["תעודת משלוח", "פרויקט"],
    downstreamModules: ["חשבונית", "אחריות", "שירות"],
    syncRules: ["השלמת התקנה → עדכון פרויקט", "השלמת התקנה → חשבונית סופית"],
    validationRules: ["תעודת משלוח חובה", "צוות התקנה חובה"],
  },
  {
    id: "invoice",
    name: "חשבונית",
    nameEn: "Invoice",
    module: "כספים",
    category: "finance",
    icon: "Receipt",
    description: "חשבונית מס/קבלה",
    sourceInputs: ["הזמנת מכירה", "תעודת משלוח", "התקנה"],
    ownedData: ["מספר חשבונית", "סכום", "מע\"מ", "תנאי תשלום"],
    derivedData: ["סה\"כ כולל מע\"מ", "יתרת חוב", "ימי פירעון"],
    downstreamOutputs: ["חשבונות חייבים", "ספר ראשי", "תזרים מזומנים"],
    aiEnrichedFields: ["revenue_amount", "vat_component", "net_revenue", "gross_profit", "gross_margin_pct"],
    upstreamModules: ["הזמנת מכירה", "תעודת משלוח", "התקנה"],
    downstreamModules: ["חשבונות חייבים", "ספר ראשי", "דוחות ניהול"],
    syncRules: ["הפקה → AR", "תשלום → עדכון יתרה", "חשבונית → פקודת יומן GL"],
    validationRules: ["לקוח חובה", "סכום חיובי", "מספר חשבונית ייחודי"],
  },
  {
    id: "payment",
    name: "תשלום",
    nameEn: "Payment",
    module: "כספים",
    category: "finance",
    icon: "CreditCard",
    description: "קבלת תשלום מלקוח",
    sourceInputs: ["חשבונית", "הסדר תשלום"],
    ownedData: ["סכום", "אמצעי תשלום", "תאריך", "הפניה"],
    derivedData: ["יתרה לתשלום", "ימי פיגור"],
    downstreamOutputs: ["עדכון AR", "פקודת יומן", "קבלה"],
    aiEnrichedFields: ["payment_method_category", "days_overdue"],
    upstreamModules: ["חשבונית"],
    downstreamModules: ["חשבונות חייבים", "ספר ראשי", "תזרים", "רווחיות"],
    syncRules: ["תשלום → עדכון AR", "תשלום מלא → סגירת חשבונית"],
    validationRules: ["חשבונית חובה", "סכום חיובי"],
  },
  {
    id: "profitability",
    name: "רווחיות",
    nameEn: "Profitability",
    module: "ניהול",
    category: "executive",
    icon: "TrendingUp",
    description: "ניתוח רווחיות לפרויקט/לקוח",
    sourceInputs: ["חשבוניות", "עלויות ייצור", "עלויות רכש", "עלויות התקנה"],
    ownedData: [],
    derivedData: ["רווח גולמי", "רווח תפעולי", "מרווח %", "ROI"],
    downstreamOutputs: ["דשבורד ניהולי", "KPI"],
    aiEnrichedFields: ["profitability_trend", "forecast_next_quarter"],
    upstreamModules: ["חשבונית", "תשלום", "רכש", "ייצור", "התקנה"],
    downstreamModules: [],
    syncRules: ["חישוב אוטומטי מכל הזנות כספיות"],
    validationRules: [],
  },
];

const EDGES: DataFlowEdge[] = [
  { id: "e1", from: "lead", to: "customer", label: "המרת ליד", labelEn: "Lead Conversion", trigger: "status=converted/won", dataFields: ["שם", "טלפון", "אימייל", "חברה", "העדפות"], type: "event" },
  { id: "e2", from: "customer", to: "quotation", label: "יצירת הצעה", labelEn: "Create Quote", trigger: "manual/auto", dataFields: ["מזהה לקוח", "כתובת", "תנאי תשלום"], type: "derived" },
  { id: "e3", from: "quotation", to: "sales_order", label: "אישור הצעה", labelEn: "Quote Approved", trigger: "status=approved", dataFields: ["פריטים", "מחירים", "לקוח", "תנאים"], type: "event" },
  { id: "e4", from: "sales_order", to: "project", label: "פתיחת פרויקט", labelEn: "Open Project", trigger: "status=confirmed", dataFields: ["לקוח", "פריטים", "תקציב", "לו\"ז"], type: "event" },
  { id: "e5", from: "project", to: "measurement", label: "שליחה למדידה", labelEn: "Send to Measurement", trigger: "status=measuring", dataFields: ["כתובת", "דרישות", "לו\"ז"], type: "sync" },
  { id: "e6", from: "measurement", to: "bom", label: "מדידות → BOM", labelEn: "Measurements to BOM", trigger: "status=completed", dataFields: ["מידות", "כמויות", "חומרים"], type: "sync" },
  { id: "e7", from: "bom", to: "purchase_order", label: "דרישות רכש", labelEn: "Purchase Requirements", trigger: "status=approved", dataFields: ["חומרים", "כמויות", "מפרט"], type: "pipeline" },
  { id: "e8", from: "purchase_order", to: "inventory", label: "קבלת טובין", labelEn: "Goods Receipt", trigger: "status=received", dataFields: ["פריטים", "כמויות", "אצווה"], type: "event" },
  { id: "e9", from: "inventory", to: "purchase_order", label: "מלאי נמוך → הזמנה", labelEn: "Low Stock Reorder", trigger: "quantity<min", dataFields: ["פריט", "כמות חסרה"], type: "pipeline" },
  { id: "e10", from: "sales_order", to: "work_order", label: "הוראת ייצור", labelEn: "Production Order", trigger: "status=confirmed", dataFields: ["פריטים", "כמויות", "מפרט", "לו\"ז"], type: "event" },
  { id: "e11", from: "bom", to: "work_order", label: "רשימת חומרים", labelEn: "Material List", trigger: "bom_approved", dataFields: ["חומרים", "כמויות", "הוראות"], type: "sync" },
  { id: "e12", from: "work_order", to: "quality_control", label: "בדיקת איכות", labelEn: "Quality Check", trigger: "stage=inspection", dataFields: ["פריטים", "מפרט", "סטנדרטים"], type: "event" },
  { id: "e13", from: "quality_control", to: "delivery_note", label: "אישור לאספקה", labelEn: "Approved for Delivery", trigger: "status=approved", dataFields: ["פריטים מאושרים", "תעודת QC"], type: "event" },
  { id: "e14", from: "work_order", to: "delivery_note", label: "מוכן לאספקה", labelEn: "Ready for Delivery", trigger: "status=completed", dataFields: ["פריטים מוגמרים", "כמויות"], type: "sync" },
  { id: "e15", from: "delivery_note", to: "installation", label: "תיאום התקנה", labelEn: "Schedule Installation", trigger: "status=delivered", dataFields: ["פריטים", "כתובת", "לקוח"], type: "event" },
  { id: "e16", from: "installation", to: "invoice", label: "חשבונית סופית", labelEn: "Final Invoice", trigger: "status=completed", dataFields: ["פריטים", "שעות עבודה", "חומרים נוספים"], type: "event" },
  { id: "e17", from: "sales_order", to: "invoice", label: "חשבונית מהזמנה", labelEn: "Invoice from SO", trigger: "status=approved", dataFields: ["פריטים", "סכום", "לקוח", "מע\"מ"], type: "event" },
  { id: "e18", from: "delivery_note", to: "invoice", label: "חשבונית מאספקה", labelEn: "Invoice from Delivery", trigger: "status=delivered", dataFields: ["פריטים שסופקו", "כמויות"], type: "sync" },
  { id: "e19", from: "invoice", to: "payment", label: "גביית תשלום", labelEn: "Payment Collection", trigger: "manual/auto", dataFields: ["סכום", "תנאי תשלום", "מועד"], type: "derived" },
  { id: "e20", from: "payment", to: "profitability", label: "ניתוח רווחיות", labelEn: "Profitability Analysis", trigger: "payment_received", dataFields: ["הכנסה", "עלויות", "רווח"], type: "pipeline" },
  { id: "e21", from: "purchase_order", to: "profitability", label: "עלויות רכש", labelEn: "Procurement Costs", trigger: "po_completed", dataFields: ["עלות חומרים", "עלות משלוח"], type: "pipeline" },
  { id: "e22", from: "work_order", to: "profitability", label: "עלויות ייצור", labelEn: "Production Costs", trigger: "wo_completed", dataFields: ["שעות עבודה", "עלות מכונות", "פחת"], type: "pipeline" },
  { id: "e23", from: "installation", to: "profitability", label: "עלויות התקנה", labelEn: "Installation Costs", trigger: "install_completed", dataFields: ["שעות צוות", "נסיעות", "חומרים"], type: "pipeline" },
];

export function getDataFlowRegistry() {
  return { nodes: NODES, edges: EDGES };
}

export function getDataFlowNodeById(id: string) {
  return NODES.find(n => n.id === id) || null;
}

export function getLifecycleChain(): string[] {
  return [
    "lead", "customer", "quotation", "sales_order", "project",
    "measurement", "bom", "purchase_order", "inventory",
    "work_order", "quality_control", "delivery_note",
    "installation", "invoice", "payment", "profitability"
  ];
}

export function getModuleDataSpec(nodeId: string) {
  const node = NODES.find(n => n.id === nodeId);
  if (!node) return null;
  const inEdges = EDGES.filter(e => e.to === nodeId);
  const outEdges = EDGES.filter(e => e.from === nodeId);
  return {
    ...node,
    incomingFlows: inEdges.map(e => ({
      from: e.from,
      fromName: NODES.find(n => n.id === e.from)?.name || e.from,
      label: e.label,
      trigger: e.trigger,
      dataFields: e.dataFields,
      type: e.type,
    })),
    outgoingFlows: outEdges.map(e => ({
      to: e.to,
      toName: NODES.find(n => n.id === e.to)?.name || e.to,
      label: e.label,
      trigger: e.trigger,
      dataFields: e.dataFields,
      type: e.type,
    })),
  };
}
