import os

file_path = "artifacts/erp-app/src/App.tsx"
with open(file_path, 'r') as f:
    lines = f.readlines()

new_lines = []
in_conflict = False
conflict_found = False

for i, line in enumerate(lines):
    if "<<<<<<< HEAD" in line:
        in_conflict = True
        conflict_found = True
        # Insert the resolved content here
        new_lines.append('      <Suspense fallback={<PageLoader />}>\n')
        new_lines.append('        <Switch>\n')
        new_lines.append('          <Route path="/" component={KPIDashboard} />\n')
        new_lines.append('          <Route path="/platform" component={Dashboard} />\n')
        new_lines.append('          <Route path="/builder" component={BuilderDashboard} />\n')
        new_lines.append('          <Route path="/builder/modules" component={BuilderDashboard} />\n')
        new_lines.append('          <Route path="/builder/module/:id/versions" component={ModuleVersionHistory} />\n')
        new_lines.append('          <Route path="/builder/module/:id" component={ModuleEditor} />\n')
        new_lines.append('          <Route path="/builder/entity/:id" component={EntityEditor} />\n')
        new_lines.append('          <Route path="/builder/data/:entityId" component={DynamicDataView} />\n')
        new_lines.append('          <Route path="/module/:entityId" component={ModuleView} />\n')
        new_lines.append('          <Route path="/builder/entities" component={() => <BuilderSection section="entities" />} />\n')
        new_lines.append('          <Route path="/builder/fields" component={() => <BuilderSection section="fields" />} />\n')
        new_lines.append('          <Route path="/builder/relations" component={() => <BuilderSection section="relations" />} />\n')
        new_lines.append('          <Route path="/builder/forms" component={FormBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/views" component={ViewBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/details" component={DetailPageBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/categories" component={() => <BuilderSection section="categories" />} />\n')
        new_lines.append('          <Route path="/builder/statuses" component={() => <BuilderSection section="statuses" />} />\n')
        new_lines.append('          <Route path="/builder/buttons" component={ButtonsBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/actions" component={() => <BuilderSection section="actions" />} />\n')
        new_lines.append('          <Route path="/builder/validations" component={() => <BuilderSection section="validations" />} />\n')
        new_lines.append('          <Route path="/builder/permissions" component={PermissionsBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/menus" component={MenuBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/dashboards" component={DashboardBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/widgets" component={WidgetBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/workflows" component={WorkflowBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/automations" component={AutomationBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/automation-dashboard" component={AutomationDashboardPage} />\n')
        new_lines.append('          <Route path="/builder/templates" component={TemplateBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/tools" component={ToolBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/contexts" component={ContextBuilderPage} />\n')
        new_lines.append('          <Route path="/builder/publish" component={VersioningBuilderPage} />\n')
        new_lines.append('          <Route path="/menu-builder" component={MenuBuilderPage} />\n')
        new_lines.append('          <Route path="/audit-log" component={AuditLogPage} />\n')
        new_lines.append('          <Route path="/report-builder" component={ReportBuilderPage} />\n')
        new_lines.append('          <Route path="/document-builder" component={DocumentBuilderPage} />\n')
        new_lines.append('          <Route path="/integration-builder" component={IntegrationBuilderPage} />\n')
        new_lines.append('          <Route path="/ai-builder" component={AiBuilderPage} />\n')
        new_lines.append('          <Route path="/suppliers" component={SuppliersPage} />\n')
        new_lines.append('          <Route path="/suppliers/:id" component={SupplierCardPage} />\n')
        new_lines.append('          <Route path="/procurement-dashboard" component={ProcurementDashboardPage} />\n')
        new_lines.append('          <Route path="/import-dashboard" component={ImportDashboardPage} />\n')
        new_lines.append('          <Route path="/purchase-orders" component={PurchaseOrdersPage} />\n')
        new_lines.append('          <Route path="/goods-receipt" component={GoodsReceiptPage} />\n')
        new_lines.append('          <Route path="/purchase-requests" component={PurchaseRequestsPage} />\n')
        new_lines.append('          <Route path="/purchase-approvals" component={PurchaseApprovalsPage} />\n')
        new_lines.append('          <Route path="/price-quotes" component={PriceQuotesPage} />\n')
        new_lines.append('          <Route path="/inventory-management" component={InventoryManagementPage} />\n')
        new_lines.append('          <Route path="/finance/cost-centers" component={CostCentersPage} />\n')
        new_lines.append('          <Route path="/finance/invoices" component={InvoicesPage} />\n')
        new_lines.append('          <Route path="/finance/credit-notes" component={CreditNotesPage} />\n')
        new_lines.append('          <Route path="/finance/aging-report" component={AgingReportPage} />\n')
        new_lines.append('          <Route path="/finance/chart-of-accounts" component={ChartOfAccountsPage} />\n')
        new_lines.append('          <Route path="/finance/petty-cash" component={PettyCashPage} />\n')
        new_lines.append('          <Route path="/finance/expense-claims" component={ExpenseClaimsPage} />\n')
        new_lines.append('          <Route path="/finance/payment-runs" component={PaymentRunsPage} />\n')
        new_lines.append('          <Route path="/finance/withholding-tax" component={WithholdingTaxPage} />\n')
        new_lines.append('          <Route path="/production/quality-control" component={QualityControlPage} />\n')
        new_lines.append('          <Route path="/production/work-orders" component={WorkOrdersPage} />\n')
        new_lines.append('          <Route path="/production/maintenance" component={MaintenanceManagementPage} />\n')
        new_lines.append('          <Route path="/assets" component={AssetManagementPage} />\n')
        new_lines.append('          <Route path="/document-control" component={DocumentControlPage} />\n')
        new_lines.append('          <Route path="/safety" component={SafetyManagementPage} />\n')
        new_lines.append('          <Route path="/supplier-evaluations" component={SupplierEvaluationsPage} />\n')
        new_lines.append('          <Route path="/purchase-returns" component={PurchaseReturnsPage} />\n')
        new_lines.append('          <Route path="/supplier-contracts" component={SupplierContractsPage} />\n')
        new_lines.append('          <Route path="/budget-tracking" component={BudgetTrackingPage} />\n')
        new_lines.append('          <Route path="/import-orders" component={ImportOrdersPage} />\n')
        new_lines.append('          <Route path="/customs-clearance" component={CustomsClearancePage} />\n')
        new_lines.append('          <Route path="/shipment-tracking" component={ShipmentTrackingPage} />\n')
        new_lines.append('          <Route path="/foreign-suppliers" component={ForeignSuppliersPage} />\n')
        new_lines.append('          <Route path="/letters-of-credit" component={LettersOfCreditPage} />\n')
        new_lines.append('          <Route path="/import-cost-calculator" component={ImportCostCalculatorPage} />\n')
        new_lines.append('          <Route path="/compliance-certificates" component={ComplianceCertificatesPage} />\n')
        new_lines.append('          <Route path="/exchange-rates" component={ExchangeRatesPage} />\n')
        new_lines.append('          <Route path="/procurement-ai" component={ProcurementAIPage} />\n')
        new_lines.append('          <Route path="/project-analyses" component={ProjectAnalysesPage} />\n')
        new_lines.append('          <Route path="/project-analysis/:id" component={ProjectAnalysisDetailPage} />\n')
        new_lines.append('          <Route path="/claude-chat" component={ClaudeChatPage} />\n')
        new_lines.append('          <Route path="/ai-settings" component={AISettingsPage} />\n')
        new_lines.append('          <Route path="/permissions" component={PermissionsPage} />\n')
        new_lines.append('          <Route path="/governance" component={GovernancePage} />\n')
        new_lines.append('          <Route path="/finance" component={FinanceDashboard} />\n')
        new_lines.append('          <Route path="/finance/balance-sheet" component={BalanceSheetPage} />\n')
        new_lines.append('          <Route path="/finance/projects">{() => { const [, setLocation] = useLocation(); useEffect(() => { setLocation("/project-analyses"); }, []); return null; }}</Route>\n')
        new_lines.append('          <Route path="/finance/income" component={IncomePage} />\n')
        new_lines.append('          <Route path="/finance/credit-card-processing" component={CreditCardProcessingPage} />\n')
        new_lines.append('          <Route path="/finance/accounting-portal" component={AccountingPortalPage} />\n')
        new_lines.append('          <Route path="/finance/reports" component={ReportsPage} />\n')
        new_lines.append('          <Route path="/finance/income-expenses-report" component={IncomeExpensesReportPage} />\n')
        new_lines.append('          <Route path="/finance/accounting-settings" component={AccountingSettingsPage} />\n')
        new_lines.append('          <Route path="/finance/settings" component={AccountingSettingsPage} />\n')
        new_lines.append('          <Route path="/finance/standing-orders" component={StandingOrdersPage} />\n')
        new_lines.append('          <Route path="/finance/journal-entries" component={JournalEntriesPage} />\n')
        new_lines.append('          <Route path="/finance/bank-reconciliation" component={BankReconciliationPage} />\n')
        new_lines.append('          <Route path="/finance/cash-flow" component={CashFlowPage} />\n')
        new_lines.append('          <Route path="/finance/tax-management" component={TaxManagementPage} />\n')
        new_lines.append('          <Route path="/hr" component={HRDashboard} />\n')
        new_lines.append('          <Route path="/hr/employees" component={EmployeesListPage} />\n')
        new_lines.append('          <Route path="/hr/employees/:id" component={EmployeePortfolio} />\n')
        new_lines.append('          <Route path="/hr/payroll" component={PayrollPage} />\n')
        new_lines.append('          <Route path="/hr/employee-value" component={EmployeeValuePage} />\n')
        new_lines.append('          <Route path="/hr/attendance" component={AttendancePage} />\n')
        new_lines.append('          <Route path="/hr/shifts" component={ShiftsPage} />\n')
        new_lines.append('          <Route path="/hr/contractors" component={ContractorPaymentsPage} />\n')
        new_lines.append('          <Route path="/hr/leave-management" component={LeaveManagementPage} />\n')
        new_lines.append('          <Route path="/hr/training" component={TrainingPage} />\n')
        new_lines.append('          <Route path="/hr/recruitment" component={RecruitmentPage} />\n')
        new_lines.append('          <Route path="/hr/performance-reviews" component={PerformanceReviewsPage} />\n')
        new_lines.append('          <Route path="/ai/api-keys" component={ApiKeysPage} />\n')
        new_lines.append('          <Route path="/ai/models" component={ModelsPage} />\n')
        new_lines.append('          <Route path="/ai/providers" component={ProvidersPage} />\n')
        new_lines.append('          <Route path="/ai/queries" component={QueriesPage} />\n')
        new_lines.append('          <Route path="/ai/recommendations" component={RecommendationsPage} />\n')
        new_lines.append('          <Route path="/ai/responses" component={ResponsesPage} />\n')
        new_lines.append('          <Route path="/ai/usage-logs" component={UsageLogsPage} />\n')
        new_lines.append('          <Route path="/ai/prompt-templates" component={PromptTemplatesPage} />\n')
        new_lines.append('          <Route path="/crm" component={CrmDashboard} />\n')
        new_lines.append('          <Route path="/crm/field-agents" component={FieldAgentsPage} />\n')
        new_lines.append('          <Route path="/crm/leads" component={LeadsManagement} />\n')
        new_lines.append('          <Route path="/crm/pricing" component={DynamicPricingPage} />\n')
        new_lines.append('          <Route path="/crm/collections" component={CollectionsPage} />\n')
        new_lines.append('          <Route path="/crm/profitability" component={DailyProfitabilityPage} />\n')
        new_lines.append('          <Route path="/notifications" component={NotificationsPage} />\n')
        new_lines.append('          <Route path="/notification-preferences" component={NotificationPreferencesPage} />\n')
        new_lines.append('          <Route path="/crm/contractor-decision" component={ContractorDecisionPage} />\n')
        new_lines.append('          <Route path="/meetings" component={MeetingsCalendarPage} />\n')
        new_lines.append('          <Route path="/reports" component={ReportsHub} />\n')
        new_lines.append('          <Route path="/reports/financial" component={FinancialReports} />\n')
        new_lines.append('          <Route path="/reports/risks" component={RiskAnalysis} />\n')
        new_lines.append('          <Route path="/reports/kpis" component={KPIDashboard} />\n')
        new_lines.append('          <Route path="/reports/funnel" component={FunnelAnalysis} />\n')
        new_lines.append('          <Route path="/reports/operational" component={OperationalReports} />\n')
        new_lines.append('          <Route path="/settings" component={SettingsHub} />\n')
        new_lines.append('          <Route component={NotFound} />\n')
        new_lines.append('        </Switch>\n')
        new_lines.append('      </Suspense>\n')
    elif ">>>>>>>" in line:
        in_conflict = False
    elif not in_conflict:
        new_lines.append(line)

with open(file_path, 'w') as f:
    f.writelines(new_lines)
