-- TASK 1: Add missing fields to CUSTOMERS table
-- This migration adds 18 new fields to enhance customer management

BEGIN;

-- If customers table exists, add fields. Otherwise, it will be created from the schema.
-- Note: The following uses CREATE TABLE IF NOT EXISTS pattern with ALTER TABLE ADD IF NOT EXISTS

ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(15,2);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS credit_terms_days INTEGER DEFAULT 30;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS customer_category TEXT DEFAULT 'B';
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS customer_type TEXT DEFAULT 'business';
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS annual_revenue DECIMAL(15,2);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS salesperson_id INTEGER;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS customer_since DATE;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS last_purchase_date DATE;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS lifetime_value DECIMAL(15,2);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS loyalty_tier TEXT DEFAULT 'bronze';
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS billing_address_json TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS shipping_address_json TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS communication_pref TEXT DEFAULT 'email';
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS linkedin TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS blocked_reason TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS blocked_date DATE;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS custom_pricing_tier TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS special_discount_pct DECIMAL(5,2);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS gl_account_code TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS attachments_json TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS facebook TEXT;

-- TASK 2: Add missing fields to SUPPLIERS table
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS supplier_code TEXT;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS supplier_tier TEXT DEFAULT 'approved';
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS supplier_type TEXT DEFAULT 'manufacturer';
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS payment_terms_new TEXT DEFAULT 'net30';
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS bank_iban TEXT;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS bank_swift TEXT;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS lead_time_days_new INTEGER DEFAULT 7;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS min_order_value DECIMAL(15,2);
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS currency_new TEXT DEFAULT 'ILS';
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS quality_score DECIMAL(3,1) DEFAULT 3.0;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS delivery_score DECIMAL(3,1) DEFAULT 3.0;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS on_time_delivery_pct DECIMAL(5,2);
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS contract_expiry_date DATE;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS certifications_json TEXT;
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS annual_spend DECIMAL(15,2);
ALTER TABLE IF EXISTS suppliers ADD COLUMN IF NOT EXISTS internal_notes TEXT;

-- TASK 3: Add missing fields to RAW_MATERIALS/PRODUCTS tables
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS product_code TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS barcode_new TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS category_l1 TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS category_l2 TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS uom_stock TEXT DEFAULT 'יחידה';
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS uom_purchase TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS length_mm DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS width_mm DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS height_mm DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS reorder_point_new DECIMAL(10,2) DEFAULT 10;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS safety_stock_new DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS max_stock_level_new DECIMAL(10,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS cost_price DECIMAL(15,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS selling_price DECIMAL(15,2);
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS vat_rate DECIMAL(5,2) DEFAULT 17;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS hs_tariff_code TEXT;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS track_serial BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS track_batch BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS primary_supplier_id INTEGER;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS raw_materials ADD COLUMN IF NOT EXISTS notes_new TEXT;

-- TASK 4: Enhance ACCOUNTS_RECEIVABLE/INVOICES table
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS invoice_type TEXT DEFAULT 'AR';
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS direction TEXT DEFAULT 'AR';
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS payment_date DATE;
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS partial_payments BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS einvoice_status TEXT;
ALTER TABLE IF EXISTS accounts_receivable ADD COLUMN IF NOT EXISTS line_items_json TEXT;

-- TASK 5: SALES ORDERS table is created in new schema file

-- TASK 6: Enhance PROJECTS table  
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS project_type TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS customer_id INTEGER;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS site_address TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS project_manager_id INTEGER;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS phase TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS planned_start_date DATE;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS planned_end_date DATE;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS contract_value DECIMAL(15,2);
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS budget_planned DECIMAL(15,2);
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS budget_actual DECIMAL(15,2);
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS completion_pct DECIMAL(5,2) DEFAULT 0;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS milestone_json TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS warranty_period_months INTEGER;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS notes_new TEXT;

COMMIT;
