CREATE TABLE IF NOT EXISTS "gl_entries" (
  "id" serial PRIMARY KEY NOT NULL,
  "entry_number" text,
  "account_id" integer,
  "account_number" text,
  "account_name" text,
  "entry_date" date NOT NULL DEFAULT CURRENT_DATE,
  "period" text,
  "fiscal_year" integer DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  "fiscal_period" integer DEFAULT EXTRACT(MONTH FROM CURRENT_DATE),
  "description" text,
  "reference" text,
  "source_type" text,
  "source_document" text,
  "journal_entry_id" integer,
  "debit" numeric(15,2) DEFAULT 0,
  "credit" numeric(15,2) DEFAULT 0,
  "balance" numeric(15,2) DEFAULT 0,
  "running_balance" numeric(15,2) DEFAULT 0,
  "currency" text DEFAULT 'ILS',
  "exchange_rate" numeric(10,4) DEFAULT 1,
  "debit_ils" numeric(15,2) DEFAULT 0,
  "credit_ils" numeric(15,2) DEFAULT 0,
  "cost_center" text,
  "department" text,
  "project_name" text,
  "counterpart_account" text,
  "tax_code" text,
  "tax_amount" numeric(15,2) DEFAULT 0,
  "reconciled" boolean DEFAULT false,
  "reconciled_date" date,
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "status" text DEFAULT 'posted',
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "expense_reports" (
  "id" serial PRIMARY KEY NOT NULL,
  "report_number" text,
  "employee_name" text NOT NULL,
  "employee_id" integer,
  "department" text,
  "submit_date" date DEFAULT CURRENT_DATE,
  "period_start" date,
  "period_end" date,
  "total_amount" numeric(15,2) DEFAULT 0,
  "approved_amount" numeric(15,2) DEFAULT 0,
  "reimbursed_amount" numeric(15,2) DEFAULT 0,
  "currency" text DEFAULT 'ILS',
  "status" text DEFAULT 'draft',
  "purpose" text,
  "project_name" text,
  "cost_center" text,
  "approver_name" text,
  "approver_id" integer,
  "approved_at" timestamp,
  "rejected_reason" text,
  "reimbursement_date" date,
  "reimbursement_method" text,
  "notes" text,
  "lines_count" integer DEFAULT 0,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "expense_report_lines" (
  "id" serial PRIMARY KEY NOT NULL,
  "expense_report_id" integer NOT NULL,
  "line_number" integer DEFAULT 1,
  "expense_date" date NOT NULL DEFAULT CURRENT_DATE,
  "category" text NOT NULL,
  "description" text,
  "amount" numeric(15,2) DEFAULT 0,
  "currency" text DEFAULT 'ILS',
  "exchange_rate" numeric(10,4) DEFAULT 1,
  "amount_ils" numeric(15,2) DEFAULT 0,
  "vat_amount" numeric(15,2) DEFAULT 0,
  "net_amount" numeric(15,2) DEFAULT 0,
  "receipt_number" text,
  "receipt_url" text,
  "vendor_name" text,
  "payment_method" text,
  "is_billable" boolean DEFAULT false,
  "project_name" text,
  "cost_center" text,
  "gl_account" text,
  "tax_deductible" boolean DEFAULT true,
  "notes" text,
  "status" text DEFAULT 'pending',
  "created_at" timestamp DEFAULT NOW()
);
