-- ============================================================================
-- techno-kol-ops :: 001-operations-core
-- Operations hub core tables: jobs, job_tasks, properties, contracts
-- ============================================================================
-- Author     : Agent-24 (schema audit 2026-04-11)
-- Project    : techno-kol-ops (operations hub — metal fab + real estate)
-- Depends on : none (soft UUID refs to legacy clients table; hard FK added
--              after legacy schema is ported into this migrations chain)
-- Conventions:
--   * Money  -> NUMERIC(14,2)
--   * Times  -> TIMESTAMPTZ
--   * PK     -> UUID v4, generated by gen_random_uuid()
--   * Audit  -> created_at / updated_at / created_by / updated_by on every
--               business entity, plus per-row status ENUM-style CHECK.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. JOBS — unified job header (metal fabrication OR real estate OR mixed)
-- ============================================================================
CREATE TABLE IF NOT EXISTS jobs (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code              VARCHAR(32)  NOT NULL UNIQUE,
    name              VARCHAR(255) NOT NULL,

    -- soft ref: legacy clients(id) lives in src/db/schema.sql; hard FK added
    -- once legacy schema is ported into this migrations chain.
    client_id         UUID         NULL,

    project_type      VARCHAR(20)  NOT NULL
                      CHECK (project_type IN ('metal_fab', 'real_estate', 'mixed')),

    status            VARCHAR(32)  NOT NULL DEFAULT 'draft'
                      CHECK (status IN (
                          'draft',
                          'planned',
                          'active',
                          'on_hold',
                          'completed',
                          'cancelled',
                          'archived'
                      )),

    start_date        DATE         NULL,
    due_date          DATE         NULL,

    budget            NUMERIC(14,2) NOT NULL DEFAULT 0,
    actual_cost       NUMERIC(14,2) NOT NULL DEFAULT 0,

    description       TEXT         NULL,
    metadata          JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- audit-friendly columns
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        UUID         NULL,
    updated_by        UUID         NULL,
    archived_at       TIMESTAMPTZ  NULL,

    CONSTRAINT jobs_date_order
        CHECK (due_date IS NULL OR start_date IS NULL OR due_date >= start_date),
    CONSTRAINT jobs_budget_nonneg
        CHECK (budget >= 0 AND actual_cost >= 0)
);

CREATE INDEX IF NOT EXISTS idx_jobs_client       ON jobs(client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status       ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_project_type ON jobs(project_type);
CREATE INDEX IF NOT EXISTS idx_jobs_due_date     ON jobs(due_date);
CREATE INDEX IF NOT EXISTS idx_jobs_code         ON jobs(code);

COMMENT ON TABLE  jobs IS
    'Unified job header for the operations hub. Spans metal-fab orders, real-estate projects, and mixed engagements.';
COMMENT ON COLUMN jobs.code IS
    'Human readable job code, e.g. JOB-2026-00123. Unique across project_types.';
COMMENT ON COLUMN jobs.project_type IS
    'metal_fab = factory/install job; real_estate = property lifecycle; mixed = both arms.';


-- ============================================================================
-- 2. JOB_TASKS — task board inside a job
-- ============================================================================
CREATE TABLE IF NOT EXISTS job_tasks (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id           UUID         NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,

    title            VARCHAR(255) NOT NULL,
    description      TEXT         NULL,

    -- soft ref to employees (lives in legacy schema)
    assignee         UUID         NULL,

    status           VARCHAR(32)  NOT NULL DEFAULT 'todo'
                     CHECK (status IN (
                         'todo',
                         'in_progress',
                         'blocked',
                         'review',
                         'done',
                         'cancelled'
                     )),

    priority         VARCHAR(16)  NOT NULL DEFAULT 'normal'
                     CHECK (priority IN ('low','normal','high','urgent')),

    due_date         DATE         NULL,
    hours_estimate   NUMERIC(8,2) NOT NULL DEFAULT 0,
    hours_actual     NUMERIC(8,2) NOT NULL DEFAULT 0,

    ordering         INTEGER      NOT NULL DEFAULT 0,
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- audit columns
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    started_at       TIMESTAMPTZ  NULL,
    completed_at     TIMESTAMPTZ  NULL,
    created_by       UUID         NULL,
    updated_by       UUID         NULL,

    CONSTRAINT job_tasks_hours_nonneg
        CHECK (hours_estimate >= 0 AND hours_actual >= 0)
);

CREATE INDEX IF NOT EXISTS idx_job_tasks_job       ON job_tasks(job_id);
CREATE INDEX IF NOT EXISTS idx_job_tasks_assignee  ON job_tasks(assignee);
CREATE INDEX IF NOT EXISTS idx_job_tasks_status    ON job_tasks(status);
CREATE INDEX IF NOT EXISTS idx_job_tasks_due       ON job_tasks(due_date);

COMMENT ON TABLE job_tasks IS
    'Task board rows under a job. Owned by the assignee; rolls up hours to the job.';


-- ============================================================================
-- 3. PROPERTIES — real-estate arm asset register
-- ============================================================================
CREATE TABLE IF NOT EXISTS properties (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- link back to a job when a property is being actively worked on
    job_id            UUID         NULL REFERENCES jobs(id) ON DELETE SET NULL,

    address           TEXT         NOT NULL,
    city              VARCHAR(120) NULL,
    country           VARCHAR(80)  NOT NULL DEFAULT 'IL',
    lat               NUMERIC(10,7) NULL,
    lng               NUMERIC(10,7) NULL,

    property_type     VARCHAR(40)  NOT NULL
                      CHECK (property_type IN (
                          'apartment',
                          'house',
                          'duplex',
                          'penthouse',
                          'office',
                          'retail',
                          'warehouse',
                          'land',
                          'mixed_use',
                          'other'
                      )),

    status            VARCHAR(32)  NOT NULL DEFAULT 'prospect'
                      CHECK (status IN (
                          'prospect',
                          'due_diligence',
                          'owned',
                          'renovating',
                          'listed',
                          'under_contract',
                          'sold',
                          'rented',
                          'archived'
                      )),

    size_sqm          NUMERIC(10,2) NULL,
    rooms             NUMERIC(5,1) NULL,

    acquisition_date  DATE         NULL,
    acquisition_cost  NUMERIC(14,2) NULL,
    market_value      NUMERIC(14,2) NULL,
    monthly_rent      NUMERIC(14,2) NULL,

    notes             TEXT         NULL,
    metadata          JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- audit columns
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        UUID         NULL,
    updated_by        UUID         NULL,
    archived_at       TIMESTAMPTZ  NULL,

    CONSTRAINT properties_money_nonneg
        CHECK (COALESCE(acquisition_cost, 0) >= 0
           AND COALESCE(market_value,     0) >= 0
           AND COALESCE(monthly_rent,     0) >= 0)
);

CREATE INDEX IF NOT EXISTS idx_properties_job    ON properties(job_id);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_type   ON properties(property_type);
CREATE INDEX IF NOT EXISTS idx_properties_city   ON properties(city);

COMMENT ON TABLE properties IS
    'Real-estate arm asset register. A property may be linked to a job during acquisition or renovation.';


-- ============================================================================
-- 4. CONTRACTS — counterparty contract register
-- ============================================================================
CREATE TABLE IF NOT EXISTS contracts (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id            UUID         NULL REFERENCES jobs(id) ON DELETE SET NULL,
    property_id       UUID         NULL REFERENCES properties(id) ON DELETE SET NULL,

    contract_number   VARCHAR(64)  NOT NULL UNIQUE,

    party_name        VARCHAR(255) NOT NULL,
    party_tax_id      VARCHAR(32)  NULL,
    party_email       VARCHAR(255) NULL,
    party_phone       VARCHAR(64)  NULL,

    contract_type     VARCHAR(40)  NOT NULL
                      CHECK (contract_type IN (
                          'customer_sale',
                          'supplier_purchase',
                          'subcontractor',
                          'nda',
                          'lease_in',
                          'lease_out',
                          'service',
                          'employment',
                          'other'
                      )),

    status            VARCHAR(32)  NOT NULL DEFAULT 'draft'
                      CHECK (status IN (
                          'draft',
                          'sent',
                          'under_review',
                          'signed',
                          'active',
                          'expired',
                          'terminated',
                          'archived'
                      )),

    value             NUMERIC(14,2) NOT NULL DEFAULT 0,
    currency          CHAR(3)       NOT NULL DEFAULT 'ILS',

    start_date        DATE         NULL,
    end_date          DATE         NULL,
    signed_at         TIMESTAMPTZ  NULL,

    pdf_path          TEXT         NULL,
    signed_pdf_path   TEXT         NULL,

    metadata          JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- audit columns
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        UUID         NULL,
    updated_by        UUID         NULL,
    archived_at       TIMESTAMPTZ  NULL,

    CONSTRAINT contracts_date_order
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT contracts_value_nonneg
        CHECK (value >= 0)
);

CREATE INDEX IF NOT EXISTS idx_contracts_job        ON contracts(job_id);
CREATE INDEX IF NOT EXISTS idx_contracts_property   ON contracts(property_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status     ON contracts(status);
CREATE INDEX IF NOT EXISTS idx_contracts_type       ON contracts(contract_type);
CREATE INDEX IF NOT EXISTS idx_contracts_party_tax  ON contracts(party_tax_id);
CREATE INDEX IF NOT EXISTS idx_contracts_end_date   ON contracts(end_date);

COMMENT ON TABLE contracts IS
    'Legally binding counterparty contracts. May reference a job or a property (or neither, for framework NDAs).';


-- ============================================================================
-- 5. updated_at auto-touch trigger (shared function)
-- ============================================================================
CREATE OR REPLACE FUNCTION tko_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_jobs_touch_updated') THEN
        CREATE TRIGGER trg_jobs_touch_updated
            BEFORE UPDATE ON jobs
            FOR EACH ROW EXECUTE FUNCTION tko_touch_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_job_tasks_touch_updated') THEN
        CREATE TRIGGER trg_job_tasks_touch_updated
            BEFORE UPDATE ON job_tasks
            FOR EACH ROW EXECUTE FUNCTION tko_touch_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_properties_touch_updated') THEN
        CREATE TRIGGER trg_properties_touch_updated
            BEFORE UPDATE ON properties
            FOR EACH ROW EXECUTE FUNCTION tko_touch_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_contracts_touch_updated') THEN
        CREATE TRIGGER trg_contracts_touch_updated
            BEFORE UPDATE ON contracts
            FOR EACH ROW EXECUTE FUNCTION tko_touch_updated_at();
    END IF;
END $$;

-- ============================================================================
-- END 001-operations-core
-- ============================================================================
