import { Router, type IRouter } from "express";
import providerRouter from "./provider";
import auditRouter from "./audit";
import systemRouter from "./system";
import knowledgeRouter from "./knowledge";
import contextRouter from "./context";
import builderRouter from "./builder";
import devSupportRouter from "./dev-support";
import governanceRouter from "./governance";
import previewRouter from "./preview";
import changesetsRouter from "./changesets";
import diagnosticsRouter from "./diagnostics";
import gapsRouter from "./gaps";
import repairRouter from "./repair";
import managementRouter from "./management";
import dataflowRouter from "./dataflow";
import securityRouter from "./security";
import capabilitiesRouter from "./capabilities";
import healthCheckRouter from "./health-check";
import suggestionsRouter from "./suggestions";
import dependencyGraphRouter from "./dependency-graph";
import executionPolicyRouter from "./execution-policy";
import codeExecutorRouter from "./code-executor";
import chatRouter from "./chat";
import customerServiceRouter from "./customer-service";
import agentsRouter from "./agents";
import { claudeAuditMiddleware } from "./middleware";
import { claudeSecurityMiddleware } from "./security";

const router: IRouter = Router();

router.use("/claude", claudeAuditMiddleware);
router.use("/claude", claudeSecurityMiddleware);

router.use(providerRouter);
router.use(auditRouter);
router.use(systemRouter);
router.use(knowledgeRouter);
router.use(contextRouter);
router.use(builderRouter);
router.use(devSupportRouter);
router.use(governanceRouter);
router.use(previewRouter);
router.use(changesetsRouter);
router.use(diagnosticsRouter);
router.use(gapsRouter);
router.use(repairRouter);
router.use(managementRouter);
router.use(dataflowRouter);
router.use(securityRouter);
router.use(capabilitiesRouter);
router.use(healthCheckRouter);
router.use(suggestionsRouter);
router.use(dependencyGraphRouter);
router.use(executionPolicyRouter);
router.use(codeExecutorRouter);
router.use(chatRouter);
router.use(customerServiceRouter);
router.use(agentsRouter);

export default router;
