const fs = require('fs');
const filePath = 'artifacts/erp-app/src/App.tsx';
const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

const newLines = [];
let inConflict = false;

for (const line of lines) {
  if (line.includes('<<<<<<< HEAD')) {
    inConflict = true;
    newLines.push('      <Suspense fallback={<PageLoader />}>');
    newLines.push('        <Switch>');
    newLines.push('          <Route path="/" component={KPIDashboard} />');
    newLines.push('          <Route path="/platform" component={Dashboard} />');
    newLines.push('          <Route path="/builder" component={BuilderDashboard} />');
    newLines.push('          <Route path="/builder/modules" component={BuilderDashboard} />');
    newLines.push('          <Route path="/builder/module/:id/versions" component={ModuleVersionHistory} />');
    newLines.push('          <Route path="/builder/module/:id" component={ModuleEditor} />');
    newLines.push('          <Route path="/builder/entity/:id" component={EntityEditor} />');
    newLines.push('          <Route path="/builder/data/:entityId" component={DynamicDataView} />');
    newLines.push('          <Route path="/module/:entityId" component={ModuleView} />');
    newLines.push('          <Route path="/builder/entities" component={() => <BuilderSection section="entities" />} />');
    newLines.push('          <Route path="/builder/fields" component={() => <BuilderSection section="fields" />} />');
    newLines.push('          <Route path="/builder/relations" component={() => <BuilderSection section="relations" />} />');
    newLines.push('          <Route path="/builder/forms" component={FormBuilderPage} />');
    newLines.push('          <Route path="/builder/views" component={ViewBuilderPage} />');
    newLines.push('          <Route path="/builder/details" component={DetailPageBuilderPage} />');
    newLines.push('          <Route path="/builder/categories" component={() => <BuilderSection section="categories" />} />');
    newLines.push('          <Route path="/builder/statuses" component={() => <BuilderSection section="statuses" />} />');
    newLines.push('          <Route path="/builder/buttons" component={ButtonsBuilderPage} />');
    newLines.push('          <Route path="/builder/actions" component={() => <BuilderSection section="actions" />} />');
    newLines.push('          <Route path="/builder/validations" component={() => <BuilderSection section="validations" />} />');
    newLines.push('          <Route path="/builder/permissions" component={PermissionsBuilderPage} />');
    newLines.push('          <Route path="/builder/menus" component={MenuBuilderPage} />');
    newLines.push('          <Route path="/builder/dashboards" component={DashboardBuilderPage} />');
    newLines.push('          <Route path="/builder/widgets" component={WidgetBuilderPage} />');
    newLines.push('          <Route path="/builder/workflows" component={WorkflowBuilderPage} />');
    newLines.push('          <Route path="/builder/automations" component={AutomationBuilderPage} />');
    newLines.push('          <Route path="/builder/automation-dashboard" component={AutomationDashboardPage} />');
    newLines.push('          <Route path="/builder/templates" component={TemplateBuilderPage} />');
    newLines.push('          <Route path="/builder/tools" component={ToolBuilderPage} />');
    newLines.push('          <Route path="/builder/contexts" component={ContextBuilderPage} />');
    newLines.push('          <Route path="/builder/publish" component={VersioningBuilderPage} />');
    newLines.push('          <Route path="/menu-builder" component={MenuBuilderPage} />');
    newLines.push('          <Route path="/audit-log" component={AuditLogPage} />');
    newLines.push('          <Route path="/report-builder" component={ReportBuilderPage} />');
    newLines.push('          <Route path="/document-builder" component={DocumentBuilderPage} />');
    newLines.push('          <Route path="/integration-builder" component={IntegrationBuilderPage} />');
    newLines.push('          <Route path="/ai-builder" component={AiBuilderPage} />');
    newLines.push('          <Route path="/suppliers" component={SuppliersPage} />');
    newLines.push('          <Route path="/suppliers/:id" component={SupplierCardPage} />');
    newLines.push('          <Route path="/procurement-dashboard" component={ProcurementDashboardPage} />');
    newLines.push('          <Route path="/import-dashboard" component={ImportDashboardPage} />');
    newLines.push('          <Route path="/purchase-orders" component={PurchaseOrdersPage} />');
    newLines.push('          <Route path="/goods-receipt" component={GoodsReceiptPage} />');
    newLines.push('          <Route path="/purchase-requests" component={PurchaseRequestsPage} />');
    newLines.push('          <Route path="/purchase-approvals" component={PurchaseApprovalsPage} />');
    newLines.push('          <Route path="/price-quotes" component={PriceQuotesPage} />');
    newLines.push('          <Route path="/inventory-management" component={InventoryManagementPage} />');
    newLines.push('          <Route path="/finance/cost-centers" component={CostCentersPage} />');
    newLines.push('          <Route path="/finance/invoices" component={InvoicesPage} />');
    newLines.push('          <Route path="/finance/credit-notes" component={CreditNotesPage} />');
    newLines.push('          <Route path="/finance/aging-report" component={AgingReportPage} />');
    newLines.push('          <Route path="/finance/chart-of-accounts" component={ChartOfAccountsPage} />');
    newLines.push('          <Route path="/finance/petty-cash" component={PettyCashPage} />');
    newLines.push('          <Route path="/finance/expense-claims" component={ExpenseClaimsPage} />');
    newLines.push('          <Route path="/finance/payment-runs" component={PaymentRunsPage} />');
    newLines.push('          <Route path="/finance/withholding-tax" component={WithholdingTaxPage} />');
    newLines.push('          <Route path="/production/quality-control" component={QualityControlPage} />');
    newLines.push('          <Route path="/production/work-orders" component={WorkOrdersPage} />');
    newLines.push('          <Route path="/production/maintenance" component={MaintenanceManagementPage} />');
    newLines.push('          <Route path="/assets" component={AssetManagementPage} />');
    newLines.push('          <Route path="/document-control" component={DocumentControlPage} />');
    newLines.push('          <Route path="/safety" component={SafetyManagementPage} />');
    newLines.push('          <Route path="/supplier-evaluations" component={SupplierEvaluationsPage} />');
    newLines.push('          <Route path="/purchase-returns" component={PurchaseReturnsPage} />');
    newLines.push('          <Route path="/supplier-contracts" component={SupplierContractsPage} />');
    newLines.push('          <Route path="/budget-tracking" component={BudgetTrackingPage} />');
    newLines.push('          <Route path="/import-orders" component={ImportOrdersPage} />');
    newLines.push('          <Route path="/customs-clearance" component={CustomsClearancePage} />');
    newLines.push('          <Route path="/shipment-tracking" component={ShipmentTrackingPage} />');
    newLines.push('          <Route path="/foreign-suppliers" component={ForeignSuppliersPage} />');
    newLines.push('          <Route path="/letters-of-credit" component={LettersOfCreditPage} />');
    newLines.push('          <Route path="/import-cost-calculator" component={ImportCostCalculatorPage} />');
    newLines.push('          <Route path="/compliance-certificates" component={ComplianceCertificatesPage} />');
    newLines.push('          <Route path="/exchange-rates" component={ExchangeRatesPage} />');
    newLines.push('          <Route path="/procurement-ai" component={ProcurementAIPage} />');
    newLines.push('          <Route path="/project-analyses" component={ProjectAnalysesPage} />');
    newLines.push('          <Route path="/project-analysis/:id" component={ProjectAnalysisDetailPage} />');
    newLines.push('          <Route path="/claude-chat" component={ClaudeChatPage} />');
    newLines.push('          <Route path="/ai-settings" component={AISettingsPage} />');
    newLines.push('          <Route path="/permissions" component={PermissionsPage} />');
    newLines.push('          <Route path="/governance" component={GovernancePage} />');
    newLines.push('          <Route path="/finance" component={FinanceDashboard} />');
    newLines.push('          <Route path="/finance/balance-sheet" component={BalanceSheetPage} />');
    newLines.push('          <Route path="/finance/projects">{() => { const [, setLocation] = useLocation(); useEffect(() => { setLocation("/project-analyses"); }, []); return null; }}</Route>');
    newLines.push('          <Route path="/finance/income" component={IncomePage} />');
    newLines.push('          <Route path="/finance/credit-card-processing" component={CreditCardProcessingPage} />');
    newLines.push('          <Route path="/finance/accounting-portal" component={AccountingPortalPage} />');
    newLines.push('          <Route path="/finance/reports" component={ReportsPage} />');
    newLines.push('          <Route path="/finance/income-expenses-report" component={IncomeExpensesReportPage} />');
    newLines.push('          <Route path="/finance/accounting-settings" component={AccountingSettingsPage} />');
    newLines.push('          <Route path="/finance/settings" component={AccountingSettingsPage} />');
    newLines.push('          <Route path="/finance/standing-orders" component={StandingOrdersPage} />');
    newLines.push('          <Route path="/finance/journal-entries" component={JournalEntriesPage} />');
    newLines.push('          <Route path="/finance/bank-reconciliation" component={BankReconciliationPage} />');
    newLines.push('          <Route path="/finance/cash-flow" component={CashFlowPage} />');
    newLines.push('          <Route path="/finance/tax-management" component={TaxManagementPage} />');
    newLines.push('          <Route path="/hr" component={HRDashboard} />');
    newLines.push('          <Route path="/hr/employees" component={EmployeesListPage} />');
    newLines.push('          <Route path="/hr/employees/:id" component={EmployeePortfolio} />');
    newLines.push('          <Route path="/hr/payroll" component={PayrollPage} />');
    newLines.push('          <Route path="/hr/employee-value" component={EmployeeValuePage} />');
    newLines.push('          <Route path="/hr/attendance" component={AttendancePage} />');
    newLines.push('          <Route path="/hr/shifts" component={ShiftsPage} />');
    newLines.push('          <Route path="/hr/contractors" component={ContractorPaymentsPage} />');
    newLines.push('          <Route path="/hr/leave-management" component={LeaveManagementPage} />');
    newLines.push('          <Route path="/hr/training" component={TrainingPage} />');
    newLines.push('          <Route path="/hr/recruitment" component={RecruitmentPage} />');
    newLines.push('          <Route path="/hr/performance-reviews" component={PerformanceReviewsPage} />');
    newLines.push('          <Route path="/ai/api-keys" component={ApiKeysPage} />');
    newLines.push('          <Route path="/ai/models" component={ModelsPage} />');
    newLines.push('          <Route path="/ai/providers" component={ProvidersPage} />');
    newLines.push('          <Route path="/ai/queries" component={QueriesPage} />');
    newLines.push('          <Route path="/ai/recommendations" component={RecommendationsPage} />');
    newLines.push('          <Route path="/ai/responses" component={ResponsesPage} />');
    newLines.push('          <Route path="/ai/usage-logs" component={UsageLogsPage} />');
    newLines.push('          <Route path="/ai/prompt-templates" component={PromptTemplatesPage} />');
    newLines.push('          <Route path="/crm" component={CrmDashboard} />');
    newLines.push('          <Route path="/crm/field-agents" component={FieldAgentsPage} />');
    newLines.push('          <Route path="/crm/leads" component={LeadsManagement} />');
    newLines.push('          <Route path="/crm/pricing" component={DynamicPricingPage} />');
    newLines.push('          <Route path="/crm/collections" component={CollectionsPage} />');
    newLines.push('          <Route path="/crm/profitability" component={DailyProfitabilityPage} />');
    newLines.push('          <Route path="/notifications" component={NotificationsPage} />');
    newLines.push('          <Route path="/notification-preferences" component={NotificationPreferencesPage} />');
    newLines.push('          <Route path="/crm/contractor-decision" component={ContractorDecisionPage} />');
    newLines.push('          <Route path="/meetings" component={MeetingsCalendarPage} />');
    newLines.push('          <Route path="/reports" component={ReportsHub} />');
    newLines.push('          <Route path="/reports/financial" component={FinancialReports} />');
    newLines.push('          <Route path="/reports/risks" component={RiskAnalysis} />');
    newLines.push('          <Route path="/reports/kpis" component={KPIDashboard} />');
    newLines.push('          <Route path="/reports/funnel" component={FunnelAnalysis} />');
    newLines.push('          <Route path="/reports/operational" component={OperationalReports} />');
    newLines.push('          <Route path="/settings" component={SettingsHub} />');
    newLines.push('          <Route component={NotFound} />');
    newLines.push('        </Switch>');
    newLines.push('      </Suspense>');
  } else if (line.includes('>>>>>>>')) {
    inConflict = false;
  } else if (!inConflict) {
    newLines.push(line);
  }
}

fs.writeFileSync(filePath, newLines.join('\n'));
