CREATE TABLE IF NOT EXISTS "customer_refunds" (
  "id" serial PRIMARY KEY NOT NULL,
  "refund_number" text UNIQUE,
  "refund_date" date NOT NULL DEFAULT CURRENT_DATE,
  "customer_name" text,
  "customer_tax_id" text,
  "original_invoice_number" text,
  "reason" text DEFAULT 'return',
  "reason_description" text,
  "status" text DEFAULT 'draft',
  "currency" text DEFAULT 'ILS',
  "subtotal" numeric(15,2) DEFAULT 0,
  "vat_rate" numeric(5,2) DEFAULT 18,
  "vat_amount" numeric(15,2) DEFAULT 0,
  "total_amount" numeric(15,2) DEFAULT 0,
  "refund_method" text,
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "customer_payments" (
  "id" serial PRIMARY KEY NOT NULL,
  "payment_number" text UNIQUE,
  "payment_date" date NOT NULL DEFAULT CURRENT_DATE,
  "customer_name" text,
  "customer_tax_id" text,
  "invoice_number" text,
  "amount" numeric(15,2) DEFAULT 0,
  "currency" text DEFAULT 'ILS',
  "payment_method" text DEFAULT 'bank_transfer',
  "reference_number" text,
  "check_number" text,
  "status" text DEFAULT 'pending',
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "supplier_invoices" (
  "id" serial PRIMARY KEY NOT NULL,
  "invoice_number" text UNIQUE,
  "invoice_date" date NOT NULL DEFAULT CURRENT_DATE,
  "due_date" date,
  "supplier_name" text,
  "supplier_tax_id" text,
  "status" text DEFAULT 'received',
  "currency" text DEFAULT 'ILS',
  "subtotal" numeric(15,2) DEFAULT 0,
  "vat_rate" numeric(5,2) DEFAULT 18,
  "vat_amount" numeric(15,2) DEFAULT 0,
  "total_amount" numeric(15,2) DEFAULT 0,
  "amount_paid" numeric(15,2) DEFAULT 0,
  "balance_due" numeric(15,2) GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
  "payment_terms" text DEFAULT 'net_30',
  "item_description" text,
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "supplier_credit_notes" (
  "id" serial PRIMARY KEY NOT NULL,
  "credit_number" text UNIQUE,
  "credit_date" date NOT NULL DEFAULT CURRENT_DATE,
  "supplier_name" text,
  "supplier_tax_id" text,
  "original_invoice_number" text,
  "reason" text DEFAULT 'overcharge',
  "reason_description" text,
  "status" text DEFAULT 'draft',
  "currency" text DEFAULT 'ILS',
  "subtotal" numeric(15,2) DEFAULT 0,
  "vat_rate" numeric(5,2) DEFAULT 18,
  "vat_amount" numeric(15,2) DEFAULT 0,
  "total_amount" numeric(15,2) DEFAULT 0,
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "supplier_payments" (
  "id" serial PRIMARY KEY NOT NULL,
  "payment_number" text UNIQUE,
  "payment_date" date NOT NULL DEFAULT CURRENT_DATE,
  "supplier_name" text,
  "supplier_tax_id" text,
  "invoice_number" text,
  "amount" numeric(15,2) DEFAULT 0,
  "currency" text DEFAULT 'ILS',
  "payment_method" text DEFAULT 'bank_transfer',
  "reference_number" text,
  "check_number" text,
  "status" text DEFAULT 'pending',
  "notes" text,
  "created_by" integer,
  "created_by_name" text,
  "created_at" timestamp DEFAULT NOW(),
  "updated_at" timestamp DEFAULT NOW()
);
