import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const accountsReceivableTable = pgTable("accounts_receivable", {
  id: serial("id").primaryKey(),
  arNumber: text("ar_number"),
  invoiceNumber: text("invoice_number"),
  customerId: integer("customer_id"),
  customerName: text("customer_name").notNull(),
  customerPhone: text("customer_phone"),
  customerEmail: text("customer_email"),
  invoiceDate: date("invoice_date"),
  dueDate: date("due_date"),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  netAmount: numeric("net_amount", { precision: 15, scale: 2 }),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  paidAmount: numeric("paid_amount", { precision: 15, scale: 2 }).default("0"),
  balanceDue: numeric("balance_due", { precision: 15, scale: 2 }),
  status: text("status").default("open"),
  paymentTerms: text("payment_terms"),
  description: text("description"),
  category: text("category"),
  priority: text("priority").default("normal"),
  glAccount: text("gl_account"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectName: text("project_name"),
  salesperson: text("salesperson"),
  contactPerson: text("contact_person"),
  contactPhone: text("contact_phone"),
  withholdingTax: numeric("withholding_tax", { precision: 15, scale: 2 }).default("0"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }),
  orderNumber: text("order_number"),
  deliveryNote: text("delivery_note"),
  dunningLevel: integer("dunning_level").default(0),
  dunningBlocked: boolean("dunning_blocked").default(false),
  lastDunningDate: date("last_dunning_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  collectionNotes: text("collection_notes"),
  collectionStatus: text("collection_status"),
  collectionAgent: text("collection_agent"),
  disputed: boolean("disputed").default(false),
  disputeReason: text("dispute_reason"),
  disputeDate: date("dispute_date"),
  creditMemoNumber: text("credit_memo_number"),
  writeOffAmount: numeric("write_off_amount", { precision: 15, scale: 2 }).default("0"),
  writeOffDate: date("write_off_date"),
  writeOffReason: text("write_off_reason"),
  interestAmount: numeric("interest_amount", { precision: 12, scale: 2 }).default("0"),
  lateFeeAmount: numeric("late_fee_amount", { precision: 12, scale: 2 }).default("0"),
  salesOrderId: integer("sales_order_id"),
  createdBy: text("created_by"),
  agingBucket: text("aging_bucket"),
  customerContact: text("customer_contact"),
  lastReminderDate: date("last_reminder_date"),
  reminderCount: integer("reminder_count").default(0),
  nextReminderDate: date("next_reminder_date"),
  disputeAmount: numeric("dispute_amount", { precision: 15, scale: 2 }).default("0"),
  disputeResolved: boolean("dispute_resolved").default(false),
  promiseToPayDate: date("promise_to_pay_date"),
  promiseToPayAmount: numeric("promise_to_pay_amount", { precision: 15, scale: 2 }),
  writeOffApprovedBy: text("write_off_approved_by"),
  interestCharged: numeric("interest_charged", { precision: 15, scale: 2 }).default("0"),
  legalAction: boolean("legal_action").default(false),
  legalActionDate: date("legal_action_date"),
  creditHold: boolean("credit_hold").default(false),
  paymentPlan: text("payment_plan"),
  lastPaymentDate: date("last_payment_date"),
  lastPaymentAmount: numeric("last_payment_amount", { precision: 15, scale: 2 }),
});

export const arReceiptsTable = pgTable("ar_receipts", {
  id: serial("id").primaryKey(),
  receiptNumber: text("receipt_number"),
  arId: integer("ar_id").notNull(),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  receiptDate: date("receipt_date"),
  paymentMethod: text("payment_method"),
  reference: text("reference"),
  bankAccount: text("bank_account"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdByName: text("created_by_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const dunningLettersTable = pgTable("dunning_letters", {
  id: serial("id").primaryKey(),
  dunningNumber: text("dunning_number"),
  arId: integer("ar_id").notNull(),
  dunningLevel: integer("dunning_level").default(1),
  letterDate: date("letter_date"),
  totalAmount: numeric("total_amount", { precision: 15, scale: 2 }),
  status: text("status").default("draft"),
  sentDate: date("sent_date"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdByName: text("created_by_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
