import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const accountsPayableTable = pgTable("accounts_payable", {
  id: serial("id").primaryKey(),
  apNumber: text("ap_number"),
  invoiceNumber: text("invoice_number"),
  supplierId: integer("supplier_id"),
  supplierName: text("supplier_name").notNull(),
  invoiceDate: date("invoice_date"),
  dueDate: date("due_date"),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  netAmount: numeric("net_amount", { precision: 15, scale: 2 }),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  paidAmount: numeric("paid_amount", { precision: 15, scale: 2 }).default("0"),
  status: text("status").default("open"),
  paymentTerms: text("payment_terms"),
  paymentMethod: text("payment_method"),
  description: text("description"),
  category: text("category"),
  priority: text("priority").default("normal"),
  glAccount: text("gl_account"),
  glAccountName: text("gl_account_name"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectName: text("project_name"),
  contactPerson: text("contact_person"),
  contactPhone: text("contact_phone"),
  contactEmail: text("contact_email"),
  withholdingTax: numeric("withholding_tax", { precision: 15, scale: 2 }).default("0"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  threeWayMatch: boolean("three_way_match").default(false),
  poMatched: boolean("po_matched").default(false),
  grnMatched: boolean("grn_matched").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  grnNumber: text("grn_number"),
  paymentPriority: text("payment_priority").default("normal"),
  paymentReference: text("payment_reference"),
  paymentDate: date("payment_date"),
  earlyPaymentDiscount: numeric("early_payment_discount", { precision: 5, scale: 2 }).default("0"),
  earlyPaymentDate: date("early_payment_date"),
  recurring: boolean("recurring").default(false),
  recurringFrequency: text("recurring_frequency"),
  taxInvoiceNumber: text("tax_invoice_number"),
  deductionTaxAmount: numeric("deduction_tax_amount", { precision: 12, scale: 2 }).default("0"),
  exchangeRate: numeric("exchange_rate").default("1"),
  foreignAmount: numeric("foreign_amount", { precision: 15, scale: 2 }),
  agingBucket: text("aging_bucket"),
  createdBy: text("created_by"),
});

export const apPaymentsTable = pgTable("ap_payments", {
  id: serial("id").primaryKey(),
  paymentNumber: text("payment_number"),
  apId: integer("ap_id").notNull(),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  paymentDate: date("payment_date"),
  paymentMethod: text("payment_method"),
  reference: text("reference"),
  bankAccount: text("bank_account"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdByName: text("created_by_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
