import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const bankAccountsTable = pgTable("bank_accounts", {
  id: serial("id").primaryKey(),
  bankName: text("bank_name").notNull(),
  branchNumber: text("branch_number"),
  accountNumber: text("account_number").notNull(),
  accountType: text("account_type").default("checking"),
  currency: text("currency").default("ILS"),
  currentBalance: numeric("current_balance", { precision: 15, scale: 2 }).default("0"),
  availableBalance: numeric("available_balance", { precision: 15, scale: 2 }).default("0"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }).default("0"),
  isActive: boolean("is_active").default(true),
  lastReconciledAt: timestamp("last_reconciled_at", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const bankReconciliationsTable = pgTable("bank_reconciliations", {
  id: serial("id").primaryKey(),
  reconciliationNumber: text("reconciliation_number").notNull(),
  bankAccountId: integer("bank_account_id"),
  bankAccountName: text("bank_account_name"),
  statementDate: date("statement_date").notNull(),
  statementStartDate: date("statement_start_date"),
  statementEndDate: date("statement_end_date"),
  openingBalanceBank: numeric("opening_balance_bank", { precision: 15, scale: 2 }).default("0"),
  closingBalanceBank: numeric("closing_balance_bank", { precision: 15, scale: 2 }).default("0"),
  openingBalanceBooks: numeric("opening_balance_books", { precision: 15, scale: 2 }).default("0"),
  closingBalanceBooks: numeric("closing_balance_books", { precision: 15, scale: 2 }).default("0"),
  adjustedBankBalance: numeric("adjusted_bank_balance", { precision: 15, scale: 2 }).default("0"),
  adjustedBookBalance: numeric("adjusted_book_balance", { precision: 15, scale: 2 }).default("0"),
  depositsInTransit: numeric("deposits_in_transit", { precision: 15, scale: 2 }).default("0"),
  outstandingChecks: numeric("outstanding_checks", { precision: 15, scale: 2 }).default("0"),
  bankCharges: numeric("bank_charges", { precision: 15, scale: 2 }).default("0"),
  interestEarned: numeric("interest_earned", { precision: 15, scale: 2 }).default("0"),
  otherAdjustments: numeric("other_adjustments", { precision: 15, scale: 2 }).default("0"),
  difference: numeric("difference", { precision: 15, scale: 2 }).default("0"),
  status: text("status").default("in_progress"),
  totalItemsCount: integer("total_items_count").default(0),
  reconciledItemsCount: integer("reconciled_items_count").default(0),
  unreconciledItemsCount: integer("unreconciled_items_count").default(0),
  matchRate: numeric("match_rate", { precision: 5, scale: 1 }).default("0"),
  reconciledBy: integer("reconciled_by"),
  reconciledByName: text("reconciled_by_name"),
  reconciledAt: timestamp("reconciled_at", { withTimezone: true }),
  currency: text("currency").default("ILS"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const reconciliationItemsTable = pgTable("reconciliation_items", {
  id: serial("id").primaryKey(),
  reconciliationId: integer("reconciliation_id").notNull(),
  itemNumber: text("item_number"),
  itemDate: date("item_date"),
  description: text("description"),
  reference: text("reference"),
  itemType: text("item_type").default("bank_only"),
  amount: numeric("amount", { precision: 15, scale: 2 }).default("0"),
  debitAmount: numeric("debit_amount", { precision: 15, scale: 2 }).default("0"),
  creditAmount: numeric("credit_amount", { precision: 15, scale: 2 }).default("0"),
  bankAmount: numeric("bank_amount", { precision: 15, scale: 2 }).default("0"),
  bookAmount: numeric("book_amount", { precision: 15, scale: 2 }).default("0"),
  difference: numeric("difference", { precision: 15, scale: 2 }).default("0"),
  matched: boolean("matched").default(false),
  matchedDate: date("matched_date"),
  category: text("category"),
  source: text("source").default("manual"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
