import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const cashFlowRecordsTable = pgTable("cash_flow_records", {
  id: serial("id").primaryKey(),
  recordNumber: text("record_number").notNull(),
  recordDate: date("record_date").notNull(),
  flowType: text("flow_type").notNull().default("inflow"),
  category: text("category").default("כללי"),
  subCategory: text("sub_category"),
  description: text("description"),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  currency: text("currency").default("ILS"),
  bankAccountId: integer("bank_account_id"),
  bankAccountName: text("bank_account_name"),
  isRecurring: boolean("is_recurring").default(false),
  recurringFrequency: text("recurring_frequency"),
  sourceType: text("source_type"),
  sourceReference: text("source_reference"),
  customerName: text("customer_name"),
  supplierName: text("supplier_name"),
  projectName: text("project_name"),
  isForecast: boolean("is_forecast").default(false),
  forecastDate: date("forecast_date"),
  forecastProbability: integer("forecast_probability").default(100),
  actualDate: date("actual_date"),
  actualAmount: numeric("actual_amount", { precision: 15, scale: 2 }),
  fiscalYear: integer("fiscal_year"),
  fiscalPeriod: integer("fiscal_period"),
  status: text("status").default("actual"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
