import { pgTable, serial, text, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const complianceCertificatesTable = pgTable("compliance_certificates", {
  id: serial("id").primaryKey(),
  certNumber: text("cert_number").notNull().unique(),
  certName: text("cert_name").notNull(),
  certType: text("cert_type").notNull().default("תעודת מקור"),
  status: text("status").notNull().default("active"),
  linkedImportOrderId: integer("linked_import_order_id"),
  linkedSupplier: text("linked_supplier"),
  supplierCountry: text("supplier_country"),
  productName: text("product_name"),
  hsCode: text("hs_code"),
  issuingAuthority: text("issuing_authority"),
  issuingCountry: text("issuing_country"),
  documentNumber: text("document_number"),
  referenceNumber: text("reference_number"),
  issueDate: date("issue_date"),
  expiryDate: date("expiry_date"),
  renewalDate: date("renewal_date"),
  lastAuditDate: date("last_audit_date"),
  nextAuditDate: date("next_audit_date"),
  scope: text("scope"),
  standards: text("standards"),
  accreditationBody: text("accreditation_body"),
  certificateHolder: text("certificate_holder"),
  holderAddress: text("holder_address"),
  fileUrl: text("file_url"),
  fileName: text("file_name"),
  verificationUrl: text("verification_url"),
  verificationStatus: text("verification_status").default("לא אומת"),
  verifiedBy: text("verified_by"),
  verifiedDate: date("verified_date"),
  isMandatory: boolean("is_mandatory").default(false),
  isOriginal: boolean("is_original").default(false),
  copiesCount: integer("copies_count").default(0),
  notarized: boolean("notarized").default(false),
  apostille: boolean("apostille").default(false),
  translated: boolean("translated").default(false),
  translationLanguage: text("translation_language"),
  linkedLcId: integer("linked_lc_id"),
  linkedCustomsId: integer("linked_customs_id"),
  rejectionReason: text("rejection_reason"),
  amendmentNotes: text("amendment_notes"),
  priority: text("priority").default("רגיל"),
  category: text("category").default("סחר"),
  tags: text("tags"),
  notes: text("notes"),
  createdBy: text("created_by"),
  approvedBy: text("approved_by"),
  approvedDate: date("approved_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
