import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const customsClearancesTable = pgTable("customs_clearances", {
  id: serial("id").primaryKey(),
  clearanceNumber: text("clearance_number").notNull().unique(),
  importOrderId: integer("import_order_id"),
  declarationNumber: text("declaration_number"),
  customsBroker: text("customs_broker"),
  brokerPhone: text("broker_phone"),
  brokerEmail: text("broker_email"),
  portOfEntry: text("port_of_entry").default("חיפה"),
  arrivalDate: date("arrival_date"),
  submissionDate: date("submission_date"),
  releaseDate: date("release_date"),
  clearanceDate: date("clearance_date"),
  goodsValue: numeric("goods_value", { precision: 15, scale: 2 }).default("0"),
  goodsCurrency: text("goods_currency").default("USD"),
  exchangeRate: numeric("exchange_rate", { precision: 10, scale: 4 }).default("1"),
  goodsValueIls: numeric("goods_value_ils", { precision: 15, scale: 2 }).default("0"),
  customsDutyPct: numeric("customs_duty_pct", { precision: 5, scale: 2 }).default("0"),
  customsDutyAmount: numeric("customs_duty_amount", { precision: 15, scale: 2 }).default("0"),
  purchaseTaxPct: numeric("purchase_tax_pct", { precision: 5, scale: 2 }).default("0"),
  purchaseTaxAmount: numeric("purchase_tax_amount", { precision: 15, scale: 2 }).default("0"),
  vatPct: numeric("vat_pct", { precision: 5, scale: 2 }).default("18"),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  portFees: numeric("port_fees", { precision: 15, scale: 2 }).default("0"),
  storageFees: numeric("storage_fees", { precision: 15, scale: 2 }).default("0"),
  inspectionFees: numeric("inspection_fees", { precision: 15, scale: 2 }).default("0"),
  brokerFees: numeric("broker_fees", { precision: 15, scale: 2 }).default("0"),
  otherFees: numeric("other_fees", { precision: 15, scale: 2 }).default("0"),
  totalFees: numeric("total_fees", { precision: 15, scale: 2 }).default("0"),
  totalTaxes: numeric("total_taxes", { precision: 15, scale: 2 }).default("0"),
  totalCost: numeric("total_cost", { precision: 15, scale: 2 }).default("0"),
  hsCodes: text("hs_codes"),
  customsClassification: text("customs_classification"),
  containerNumbers: text("container_numbers"),
  billOfLading: text("bill_of_lading"),
  docCommercialInvoice: boolean("doc_commercial_invoice").default(false),
  docPackingList: boolean("doc_packing_list").default(false),
  docBillOfLading: boolean("doc_bill_of_lading").default(false),
  docCertificateOfOrigin: boolean("doc_certificate_of_origin").default(false),
  docInsuranceCertificate: boolean("doc_insurance_certificate").default(false),
  docCustomsDeclaration: boolean("doc_customs_declaration").default(false),
  docInspectionReport: boolean("doc_inspection_report").default(false),
  docLetterOfCredit: boolean("doc_letter_of_credit").default(false),
  docPhytosanitary: boolean("doc_phytosanitary").default(false),
  docStandardsCertificate: boolean("doc_standards_certificate").default(false),
  supplierName: text("supplier_name"),
  countryOfOrigin: text("country_of_origin"),
  responsiblePerson: text("responsible_person"),
  notes: text("notes"),
  status: text("status").notNull().default("ממתין"),
  priority: text("priority").default("רגילה"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
