import { pgTable, serial, text, numeric, timestamp, date, integer, boolean, varchar } from "drizzle-orm/pg-core";

export const employeesTable = pgTable("employees", {
  id: serial("id").primaryKey(),
  employeeNumber: varchar("employee_number", { length: 50 }).unique(),
  firstName: varchar("first_name", { length: 100 }),
  lastName: varchar("last_name", { length: 100 }),
  fullName: varchar("full_name", { length: 200 }),
  idNumber: varchar("id_number", { length: 20 }),
  email: varchar("email", { length: 200 }),
  phone: varchar("phone", { length: 30 }),
  mobilePhone: varchar("mobile_phone", { length: 30 }),
  personalEmail: varchar("personal_email", { length: 200 }),
  secondaryPhone: varchar("secondary_phone", { length: 30 }),
  department: varchar("department", { length: 100 }).default("כללי"),
  subDepartment: varchar("sub_department", { length: 100 }),
  jobTitle: varchar("job_title", { length: 200 }),
  employmentType: varchar("employment_type", { length: 50 }).default("full_time"),
  startDate: date("start_date"),
  endDate: date("end_date"),
  baseSalary: numeric("base_salary", { precision: 12, scale: 2 }).default("0"),
  grossSalary: numeric("gross_salary", { precision: 12, scale: 2 }).default("0"),
  netSalary: numeric("net_salary", { precision: 12, scale: 2 }).default("0"),
  salaryCurrency: varchar("salary_currency", { length: 10 }).default("ILS"),
  status: varchar("status", { length: 30 }).default("active"),
  managerId: integer("manager_id"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),

  dateOfBirth: date("date_of_birth"),
  gender: varchar("gender", { length: 10 }),
  maritalStatus: varchar("marital_status", { length: 20 }),
  childrenCount: integer("children_count").default(0),
  spouseName: varchar("spouse_name", { length: 200 }),
  spouseIdNumber: varchar("spouse_id_number", { length: 20 }),
  spouseWorks: boolean("spouse_works"),
  address: text("address"),
  city: varchar("city", { length: 100 }),
  postalCode: varchar("postal_code", { length: 20 }),
  country: varchar("country", { length: 50 }).default("ישראל"),

  emergencyContact: varchar("emergency_contact", { length: 200 }),
  emergencyPhone: varchar("emergency_phone", { length: 30 }),
  emergencyRelation: varchar("emergency_relation", { length: 50 }),
  emergencyContact2: varchar("emergency_contact2", { length: 200 }),
  emergencyPhone2: varchar("emergency_phone2", { length: 30 }),
  emergencyRelation2: varchar("emergency_relation2", { length: 50 }),

  nationalId: varchar("national_id", { length: 20 }),
  passportNumber: varchar("passport_number", { length: 20 }),
  passportExpiry: date("passport_expiry"),
  drivingLicense: varchar("driving_license", { length: 20 }),
  drivingLicenseType: varchar("driving_license_type", { length: 10 }),
  militaryService: varchar("military_service", { length: 100 }),
  newImmigrant: boolean("new_immigrant").default(false),
  immigrationDate: date("immigration_date"),
  residencePermit: varchar("residence_permit", { length: 50 }),
  residencePermitExpiry: date("residence_permit_expiry"),

  bankName: varchar("bank_name", { length: 100 }),
  bankBranch: varchar("bank_branch", { length: 50 }),
  bankAccount: varchar("bank_account", { length: 50 }),
  directDeposit: boolean("direct_deposit").default(true),
  nationalInsurance: varchar("national_insurance", { length: 20 }),
  healthInsurance: varchar("health_insurance", { length: 50 }),
  taxFileNumber: varchar("tax_file_number", { length: 30 }),
  taxCoordinationNumber: varchar("tax_coordination_number", { length: 20 }),
  taxCreditPoints: numeric("tax_credit_points", { precision: 4, scale: 1 }).default("2.25"),
  incomeTaxBracket: varchar("income_tax_bracket", { length: 20 }),

  pensionFund: varchar("pension_fund", { length: 100 }),
  pensionPct: numeric("pension_pct", { precision: 5, scale: 2 }).default("6"),
  employerPensionPct: numeric("employer_pension_pct", { precision: 5, scale: 2 }).default("6.5"),
  employeePensionPct: numeric("employee_pension_pct", { precision: 5, scale: 2 }).default("6"),
  severancePct: numeric("severance_pct", { precision: 5, scale: 2 }).default("8.33"),
  educationFund: varchar("education_fund", { length: 100 }),
  educationFundEmployerPct: numeric("education_fund_employer_pct", { precision: 5, scale: 2 }).default("7.5"),
  educationFundEmployeePct: numeric("education_fund_employee_pct", { precision: 5, scale: 2 }).default("2.5"),
  disabilityPercent: numeric("disability_percent", { precision: 5, scale: 2 }).default("0"),

  vacationDaysBalance: numeric("vacation_days_balance", { precision: 6, scale: 2 }).default("0"),
  vacationDaysAnnual: numeric("vacation_days_annual", { precision: 4, scale: 1 }).default("12"),
  sickDaysBalance: numeric("sick_days_balance", { precision: 6, scale: 2 }).default("0"),
  personalDaysBalance: numeric("personal_days_balance", { precision: 4, scale: 1 }).default("0"),
  convalescenceDays: integer("convalescence_days").default(0),
  convalescencePerDay: numeric("convalescence_per_day", { precision: 8, scale: 2 }),

  lastRaiseDate: date("last_raise_date"),
  lastRaiseAmount: numeric("last_raise_amount", { precision: 10, scale: 2 }),
  lastRaisePercent: numeric("last_raise_percent", { precision: 5, scale: 2 }),
  bonusTarget: numeric("bonus_target", { precision: 10, scale: 2 }).default("0"),
  commissionRate: numeric("commission_rate", { precision: 5, scale: 2 }).default("0"),
  paymentFrequency: varchar("payment_frequency", { length: 20 }).default("monthly"),
  weeklyHours: numeric("weekly_hours", { precision: 5, scale: 1 }).default("42"),
  overtimeEligible: boolean("overtime_eligible").default(true),
  hourlyRate: numeric("hourly_rate", { precision: 10, scale: 2 }),

  travelAllowance: numeric("travel_allowance", { precision: 10, scale: 2 }).default("0"),
  mealAllowance: numeric("meal_allowance", { precision: 10, scale: 2 }).default("0"),
  phoneAllowance: numeric("phone_allowance", { precision: 10, scale: 2 }).default("0"),
  toolAllowance: numeric("tool_allowance", { precision: 10, scale: 2 }).default("0"),
  carAllowance: boolean("car_allowance").default(false),
  carValue: numeric("car_value", { precision: 10, scale: 2 }),
  carType: varchar("car_type", { length: 100 }),
  carNumber: varchar("car_number", { length: 20 }),

  safetyTrainingDate: date("safety_training_date"),
  safetyTrainingExpiry: date("safety_training_expiry"),
  safetyLevel: varchar("safety_level", { length: 20 }),
  safetyCertificate: varchar("safety_certificate", { length: 100 }),
  forkliftLicense: boolean("forklift_license").default(false),
  forkliftLicenseExpiry: date("forklift_license_expiry"),
  craneLicense: boolean("crane_license").default(false),
  craneLicenseExpiry: date("crane_license_expiry"),
  weldingCertificate: varchar("welding_certificate", { length: 50 }),
  weldingCertificateExpiry: date("welding_certificate_expiry"),
  heightsCertificate: boolean("heights_certificate").default(false),
  heightsCertificateExpiry: date("heights_certificate_expiry"),
  firstAidTrained: boolean("first_aid_trained").default(false),
  firstAidExpiry: date("first_aid_expiry"),
  ppeIssued: boolean("ppe_issued").default(false),
  ppeDetails: text("ppe_details"),
  medicalExamDate: date("medical_exam_date"),
  medicalExamExpiry: date("medical_exam_expiry"),
  medicalRestrictions: text("medical_restrictions"),
  hearingTestDate: date("hearing_test_date"),
  visionTestDate: date("vision_test_date"),
  workAccidentCount: integer("work_accident_count").default(0),
  lastAccidentDate: date("last_accident_date"),
  bloodType: varchar("blood_type", { length: 5 }),
  allergies: text("allergies"),

  productionStation: varchar("production_station", { length: 50 }),
  primaryMachineId: integer("primary_machine_id"),
  secondarySkills: text("secondary_skills"),
  canOperateMachines: text("can_operate_machines"),
  qualityRating: numeric("quality_rating", { precision: 3, scale: 1 }),
  productivityRating: numeric("productivity_rating", { precision: 3, scale: 1 }),
  attendanceRating: numeric("attendance_rating", { precision: 3, scale: 1 }),
  teamName: varchar("team_name", { length: 100 }),
  teamLeader: boolean("team_leader").default(false),
  shiftPreference: varchar("shift_preference", { length: 20 }),
  shiftPattern: varchar("shift_pattern", { length: 30 }),
  costCenter: varchar("cost_center", { length: 50 }),
  workLocation: varchar("work_location", { length: 100 }),

  performanceScore: numeric("performance_score", { precision: 3, scale: 1 }),
  lastReviewDate: date("last_review_date"),
  nextReviewDate: date("next_review_date"),
  hireReason: text("hire_reason"),
  terminationReason: text("termination_reason"),
  contractType: varchar("contract_type", { length: 30 }).default("unlimited"),
  contractEndDate: date("contract_end_date"),
  probationEndDate: date("probation_end_date"),
  seniorityDate: date("seniority_date"),

  skills: text("skills"),
  certifications: text("certifications"),
  languages: text("languages"),
  educationJson: text("education_json"),
  photoUrl: text("photo_url"),
  uniformSize: varchar("uniform_size", { length: 10 }),
  shoeSize: varchar("shoe_size", { length: 10 }),
  lockerNumber: varchar("locker_number", { length: 20 }),
  badgeNumber: varchar("badge_number", { length: 30 }),
  accessLevel: varchar("access_level", { length: 20 }),
  parkingSpot: varchar("parking_spot", { length: 20 }),
  companyPhone: varchar("company_phone", { length: 30 }),
  companyEmail: varchar("company_email", { length: 200 }),
  linkedinUrl: text("linkedin_url"),

  form101Signed: boolean("form_101_signed").default(false),
  form101Date: date("form_101_date"),
  ndaSigned: boolean("nda_signed").default(false),
  ndaDate: date("nda_date"),
  contractSigned: boolean("contract_signed").default(false),
  contractUrl: text("contract_url"),
  documentsUrl: text("documents_url"),
  tags: text("tags"),

  position: text("position"),
  positionLevel: varchar("position_level", { length: 20 }),
  grade: varchar("grade", { length: 20 }),
  rank: integer("rank"),
  reportingTo: varchar("reporting_to", { length: 200 }),
  directReportsCount: integer("direct_reports_count").default(0),
  functionalManager: varchar("functional_manager", { length: 200 }),
  hireDate: date("hire_date"),
  originalHireDate: date("original_hire_date"),
  rehireDate: date("rehire_date"),
  terminationDate: date("termination_date"),
  terminationType: varchar("termination_type", { length: 30 }),
  eligibleForRehire: boolean("eligible_for_rehire").default(true),
  noticePeriodDays: integer("notice_period_days").default(30),
  noticeGivenDate: date("notice_given_date"),
  lastWorkingDay: date("last_working_day"),
  clearanceCompleted: boolean("clearance_completed").default(false),
  exitInterviewDone: boolean("exit_interview_done").default(false),
  exitInterviewNotes: text("exit_interview_notes"),
  separationReason: text("separation_reason"),

  street: varchar("street", { length: 200 }),
  houseNumber: varchar("house_number", { length: 20 }),
  apartment: varchar("apartment", { length: 20 }),
  neighborhood: varchar("neighborhood", { length: 100 }),
  region: varchar("region", { length: 100 }),
  gpsLatitude: numeric("gps_latitude", { precision: 10, scale: 7 }),
  gpsLongitude: numeric("gps_longitude", { precision: 10, scale: 7 }),
  homePhone: varchar("home_phone", { length: 30 }),
  workPhone: varchar("work_phone", { length: 30 }),
  fax: varchar("fax", { length: 30 }),
  whatsapp: varchar("whatsapp", { length: 30 }),
  preferredContactMethod: varchar("preferred_contact_method", { length: 20 }),
  nationality: varchar("nationality", { length: 50 }),

  iban: varchar("iban", { length: 50 }),
  swiftCode: varchar("swift_code", { length: 20 }),
  socialSecurityNumber: varchar("social_security_number", { length: 30 }),
  taxStatus: varchar("tax_status", { length: 20 }),
  taxExemption: boolean("tax_exemption").default(false),
  taxExemptionDetails: text("tax_exemption_details"),
  workPermit: varchar("work_permit", { length: 50 }),
  workPermitExpiry: date("work_permit_expiry"),
  visaType: varchar("visa_type", { length: 30 }),
  visaExpiry: date("visa_expiry"),
  unionMember: boolean("union_member").default(false),
  unionName: varchar("union_name", { length: 100 }),
  collectiveAgreement: varchar("collective_agreement", { length: 100 }),

  educationLevel: varchar("education_level", { length: 50 }),
  university: varchar("university", { length: 200 }),
  degree: varchar("degree", { length: 100 }),
  graduationYear: integer("graduation_year"),
  professionalLicense: varchar("professional_license", { length: 100 }),
  professionalLicenseExpiry: date("professional_license_expiry"),
  trainingBudget: numeric("training_budget", { precision: 10, scale: 2 }).default("0"),
  trainingHoursYtd: numeric("training_hours_ytd", { precision: 6, scale: 1 }).default("0"),
  requiredTrainingHours: numeric("required_training_hours", { precision: 6, scale: 1 }),

  disciplinaryWarnings: integer("disciplinary_warnings").default(0),
  lastDisciplinaryDate: date("last_disciplinary_date"),
  disciplinaryNotes: text("disciplinary_notes"),
  rewardPoints: integer("reward_points").default(0),
  employeeOfMonthCount: integer("employee_of_month_count").default(0),
  referredBy: varchar("referred_by", { length: 200 }),
  recruitmentSource: varchar("recruitment_source", { length: 100 }),
  onboardingCompleted: boolean("onboarding_completed").default(false),
  onboardingDate: date("onboarding_date"),
  mentor: varchar("mentor", { length: 200 }),
  buddy: varchar("buddy", { length: 200 }),
  itEquipmentIssued: text("it_equipment_issued"),
  systemUsername: varchar("system_username", { length: 100 }),
  fingerPrintEnrolled: boolean("finger_print_enrolled").default(false),
  faceRecognitionEnrolled: boolean("face_recognition_enrolled").default(false),
  keyCardNumber: varchar("key_card_number", { length: 30 }),
  gateAccessZones: text("gate_access_zones"),
  workingFromHomeDays: integer("working_from_home_days").default(0),
  flexTimeEligible: boolean("flex_time_eligible").default(false),
  annualLeaveTaken: numeric("annual_leave_taken", { precision: 6, scale: 2 }).default("0"),
  sickLeaveTaken: numeric("sick_leave_taken", { precision: 6, scale: 2 }).default("0"),
  reserveDutyDays: integer("reserve_duty_days").default(0),
  lastReserveDuty: date("last_reserve_duty"),
});
