import { pgTable, serial, text, timestamp, date, numeric, integer } from "drizzle-orm/pg-core";

export const exchangeRatesTable = pgTable("exchange_rates", {
  id: serial("id").primaryKey(),
  rateNumber: text("rate_number").notNull().unique(),
  currencyCode: text("currency_code").notNull(),
  currencyName: text("currency_name").notNull(),
  baseCurrency: text("base_currency").notNull().default("ILS"),
  rate: numeric("rate", { precision: 12, scale: 6 }).notNull(),
  previousRate: numeric("previous_rate", { precision: 12, scale: 6 }),
  changePercent: numeric("change_percent", { precision: 8, scale: 4 }),
  rateDate: date("rate_date").notNull(),
  source: text("source").default("ידני"),
  rateType: text("rate_type").default("רשמי"),
  buyRate: numeric("buy_rate", { precision: 12, scale: 6 }),
  sellRate: numeric("sell_rate", { precision: 12, scale: 6 }),
  midRate: numeric("mid_rate", { precision: 12, scale: 6 }),
  status: text("status").default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const hedgingContractsTable = pgTable("hedging_contracts", {
  id: serial("id").primaryKey(),
  contractNumber: text("contract_number").notNull().unique(),
  contractType: text("contract_type").notNull().default("forward"),
  status: text("status").notNull().default("active"),
  currencyCode: text("currency_code").notNull(),
  amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
  hedgedRate: numeric("hedged_rate", { precision: 12, scale: 6 }).notNull(),
  spotRateAtContract: numeric("spot_rate_at_contract", { precision: 12, scale: 6 }),
  startDate: date("start_date").notNull(),
  maturityDate: date("maturity_date").notNull(),
  settlementDate: date("settlement_date"),
  counterparty: text("counterparty"),
  bankName: text("bank_name"),
  linkedImportOrder: text("linked_import_order"),
  linkedLc: text("linked_lc"),
  premiumCost: numeric("premium_cost", { precision: 12, scale: 2 }),
  premiumCurrency: text("premium_currency").default("ILS"),
  strikePrice: numeric("strike_price", { precision: 12, scale: 6 }),
  optionType: text("option_type"),
  notionalAmount: numeric("notional_amount", { precision: 14, scale: 2 }),
  settlementAmount: numeric("settlement_amount", { precision: 14, scale: 2 }),
  realizedPnl: numeric("realized_pnl", { precision: 14, scale: 2 }),
  unrealizedPnl: numeric("unrealized_pnl", { precision: 14, scale: 2 }),
  marginRequired: numeric("margin_required", { precision: 12, scale: 2 }),
  marginDeposited: numeric("margin_deposited", { precision: 12, scale: 2 }),
  referenceNumber: text("reference_number"),
  priority: text("priority").default("רגיל"),
  notes: text("notes"),
  createdBy: text("created_by"),
  approvedBy: text("approved_by"),
  approvedDate: date("approved_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const currencyExposuresTable = pgTable("currency_exposures", {
  id: serial("id").primaryKey(),
  exposureNumber: text("exposure_number").notNull().unique(),
  currencyCode: text("currency_code").notNull(),
  exposureType: text("exposure_type").notNull().default("יבוא"),
  category: text("category").default("סחורות"),
  totalExposure: numeric("total_exposure", { precision: 14, scale: 2 }).notNull(),
  hedgedAmount: numeric("hedged_amount", { precision: 14, scale: 2 }).default("0"),
  unhedgedAmount: numeric("unhedged_amount", { precision: 14, scale: 2 }).default("0"),
  hedgeRatio: numeric("hedge_ratio", { precision: 6, scale: 2 }).default("0"),
  currentRate: numeric("current_rate", { precision: 12, scale: 6 }),
  budgetRate: numeric("budget_rate", { precision: 12, scale: 6 }),
  impactAtCurrent: numeric("impact_at_current", { precision: 14, scale: 2 }),
  impactAtBudget: numeric("impact_at_budget", { precision: 14, scale: 2 }),
  variance: numeric("variance", { precision: 14, scale: 2 }),
  linkedSupplier: text("linked_supplier"),
  linkedOrders: text("linked_orders"),
  maturityMonth: text("maturity_month"),
  status: text("status").default("פתוח"),
  riskLevel: text("risk_level").default("בינוני"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
