import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const expensesTable = pgTable("expenses", {
  id: serial("id").primaryKey(),
  expenseNumber: text("expense_number"),
  expenseDate: date("expense_date"),
  category: text("category"),
  subcategory: text("subcategory"),
  description: text("description").notNull(),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  paymentMethod: text("payment_method"),
  vendorName: text("vendor_name"),
  receiptNumber: text("receipt_number"),
  isRecurring: boolean("is_recurring").default(false),
  recurrencePeriod: text("recurrence_period"),
  department: text("department"),
  projectId: integer("project_id"),
  approvedBy: text("approved_by"),
  status: text("status").default("pending"),
  accountId: integer("account_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  fileUrl: text("file_url"),
  receiptUrl: text("receipt_url"),
  employeeId: integer("employee_id"),
  employeeName: text("employee_name"),
  projectName: text("project_name"),
  costCenter: text("cost_center"),
  mileageKm: numeric("mileage_km"),
  mileageRate: numeric("mileage_rate"),
  vehicleNumber: text("vehicle_number"),
  reimbursable: boolean("reimbursable").default(true),
  reimbursed: boolean("reimbursed").default(false),
  reimbursementDate: date("reimbursement_date"),
  advancePaymentId: integer("advance_payment_id"),
  exchangeRate: numeric("exchange_rate").default("1"),
  baseAmount: numeric("base_amount"),
  budgetCode: text("budget_code"),
  overBudget: boolean("over_budget").default(false),
  recurring: boolean("recurring").default(false),
  recurringPeriod: text("recurring_period"),
  tags: text("tags"),
  expenseType: text("expense_type").default("regular"),
  vendorTaxId: text("vendor_tax_id"),
  invoiceNumber: text("invoice_number"),
  invoiceDate: date("invoice_date"),
  vatRate: numeric("vat_rate").default("18"),
  vatReclaimable: boolean("vat_reclaimable").default(true),
  vatReclaimed: boolean("vat_reclaimed").default(false),
  withholdingTaxRate: numeric("withholding_tax_rate"),
  withholdingTaxAmount: numeric("withholding_tax_amount").default("0"),
  netAmount: numeric("net_amount"),
  bankAccountId: integer("bank_account_id"),
  checkNumber: text("check_number"),
  checkDate: date("check_date"),
  creditCardLast4: text("credit_card_last4"),
  creditCardType: text("credit_card_type"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  approvalRequired: boolean("approval_required").default(false),
  paid: boolean("paid").default(false),
  paidDate: date("paid_date"),
  paidAmount: numeric("paid_amount"),
  journalEntryId: integer("journal_entry_id"),
  glAccountId: integer("gl_account_id"),
  glAccountName: text("gl_account_name"),
  reconciled: boolean("reconciled").default(false),
  reconciledDate: date("reconciled_date"),
  reimbursementAmount: numeric("reimbursement_amount"),
  supplierId: integer("supplier_id"),
  supplierName: text("supplier_name"),
  purchaseOrderId: integer("purchase_order_id"),
  assetId: integer("asset_id"),
  isCapex: boolean("is_capex").default(false),
  documentsUrl: text("documents_url"),
});
