import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const financialAccountsTable = pgTable("financial_accounts", {
  id: serial("id").primaryKey(),
  accountNumber: text("account_number").notNull(),
  accountName: text("account_name").notNull(),
  accountNameHe: text("account_name_he"),
  accountType: text("account_type").notNull().default("asset"),
  parentAccount: text("parent_account"),
  parentId: integer("parent_id"),
  level: integer("level").default(1),
  balance: numeric("balance", { precision: 15, scale: 2 }).default("0"),
  openingBalance: numeric("opening_balance", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  description: text("description"),
  isActive: boolean("is_active").default(true),
  isHeader: boolean("is_header").default(false),
  normalSide: text("normal_side").default("debit"),
  taxCode: text("tax_code"),
  costCenter: text("cost_center"),
  department: text("department"),
  notes: text("notes"),
  debitTotal: numeric("debit_total", { precision: 15, scale: 2 }).default("0"),
  creditTotal: numeric("credit_total", { precision: 15, scale: 2 }).default("0"),
  isReconcilable: boolean("is_reconcilable").default(false),
  reconciliationDate: date("reconciliation_date"),
  budgetAmount: numeric("budget_amount", { precision: 15, scale: 2 }).default("0"),
  budgetWarningPercent: numeric("budget_warning_percent", { precision: 5, scale: 2 }).default("80"),
  isLocked: boolean("is_locked").default(false),
  lockedDate: date("locked_date"),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
