import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const foreignSuppliersTable = pgTable("foreign_suppliers", {
  id: serial("id").primaryKey(),
  supplierCode: text("supplier_code").notNull().unique(),
  companyName: text("company_name").notNull(),
  companyNameEnglish: text("company_name_english"),
  country: text("country").notNull(),
  city: text("city"),
  address: text("address"),
  postalCode: text("postal_code"),
  contactPerson: text("contact_person"),
  contactTitle: text("contact_title"),
  phone: text("phone"),
  mobile: text("mobile"),
  email: text("email"),
  website: text("website"),
  language: text("language").default("English"),
  timeZone: text("time_zone").default("UTC"),
  preferredCurrency: text("preferred_currency").default("USD"),
  paymentMethod: text("payment_method").default("Wire Transfer"),
  bankName: text("bank_name"),
  bankBranch: text("bank_branch"),
  bankAccount: text("bank_account"),
  swiftCode: text("swift_code"),
  iban: text("iban"),
  paymentTerms: text("payment_terms").default("Net 30"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }).default("0"),
  taxId: text("tax_id"),
  vatNumber: text("vat_number"),
  dunsNumber: text("duns_number"),
  tradeAgreements: text("trade_agreements"),
  freeTradeZone: boolean("free_trade_zone").default(false),
  preferentialOrigin: boolean("preferential_origin").default(false),
  incoterms: text("incoterms").default("FOB"),
  minOrderValue: numeric("min_order_value", { precision: 15, scale: 2 }).default("0"),
  leadTimeDays: integer("lead_time_days").default(30),
  iso9001: boolean("iso_9001").default(false),
  iso14001: boolean("iso_14001").default(false),
  iso45001: boolean("iso_45001").default(false),
  ceMarking: boolean("ce_marking").default(false),
  ulListed: boolean("ul_listed").default(false),
  rohsCompliant: boolean("rohs_compliant").default(false),
  reachCompliant: boolean("reach_compliant").default(false),
  otherCertifications: text("other_certifications"),
  productCategories: text("product_categories"),
  mainProducts: text("main_products"),
  annualImportVolume: numeric("annual_import_volume", { precision: 15, scale: 2 }).default("0"),
  totalOrders: integer("total_orders").default(0),
  totalImportValue: numeric("total_import_value", { precision: 15, scale: 2 }).default("0"),
  lastOrderDate: date("last_order_date"),
  avgDeliveryScore: numeric("avg_delivery_score", { precision: 3, scale: 1 }).default("0"),
  avgQualityScore: numeric("avg_quality_score", { precision: 3, scale: 1 }).default("0"),
  blacklistedCountries: text("blacklisted_countries"),
  sanctionsCheck: boolean("sanctions_check").default(false),
  sanctionsCheckDate: date("sanctions_check_date"),
  insuranceRequired: boolean("insurance_required").default(false),
  lcRequired: boolean("lc_required").default(false),
  rating: text("rating").default("B"),
  notes: text("notes"),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
