import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const generalLedgerTable = pgTable("general_ledger", {
  id: serial("id").primaryKey(),
  entryNumber: text("entry_number").notNull(),
  entryDate: date("entry_date").notNull(),
  accountNumber: text("account_number").notNull(),
  accountName: text("account_name").notNull(),
  accountType: text("account_type"),
  description: text("description"),
  reference: text("reference"),
  sourceDocument: text("source_document"),
  sourceType: text("source_type"),
  debitAmount: numeric("debit_amount", { precision: 15, scale: 2 }).default("0"),
  creditAmount: numeric("credit_amount", { precision: 15, scale: 2 }).default("0"),
  balance: numeric("balance", { precision: 15, scale: 2 }).default("0"),
  runningBalance: numeric("running_balance", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  exchangeRate: numeric("exchange_rate", { precision: 12, scale: 6 }).default("1"),
  amountIls: numeric("amount_ils", { precision: 15, scale: 2 }).default("0"),
  fiscalYear: integer("fiscal_year"),
  fiscalPeriod: integer("fiscal_period"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectName: text("project_name"),
  journalEntryId: integer("journal_entry_id"),
  status: text("status").default("posted"),
  postedBy: integer("posted_by"),
  postedByName: text("posted_by_name"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
