import { pgTable, serial, text, integer, numeric, timestamp, boolean, varchar, date } from "drizzle-orm/pg-core";

export const inventoryTable = pgTable("inventory", {
  id: serial("id").primaryKey(),
  itemCode: text("item_code").notNull().unique(),
  name: text("name").notNull(),
  nameHe: text("name_he"),
  description: text("description"),
  category: varchar("category", { length: 100 }).default("כללי"),
  subCategory: varchar("sub_category", { length: 100 }),
  unit: varchar("unit", { length: 30 }).default("יח'"),
  quantityOnHand: numeric("quantity_on_hand", { precision: 12, scale: 3 }).default("0"),
  quantityReserved: numeric("quantity_reserved", { precision: 12, scale: 3 }).default("0"),
  quantityAvailable: numeric("quantity_available", { precision: 12, scale: 3 }).default("0"),
  reorderLevel: numeric("reorder_level", { precision: 12, scale: 3 }).default("0"),
  reorderQuantity: numeric("reorder_quantity", { precision: 12, scale: 3 }).default("0"),
  maxStockLevel: numeric("max_stock_level", { precision: 12, scale: 3 }),
  costPrice: numeric("cost_price", { precision: 15, scale: 2 }).default("0"),
  sellingPrice: numeric("selling_price", { precision: 15, scale: 2 }).default("0"),
  lastPurchasePrice: numeric("last_purchase_price", { precision: 15, scale: 2 }),
  currency: varchar("currency", { length: 10 }).default("ILS"),
  supplierId: integer("supplier_id"),
  warehouseLocation: text("warehouse_location"),
  shelfNumber: varchar("shelf_number", { length: 50 }),
  barcode: varchar("barcode", { length: 100 }),
  weight: numeric("weight", { precision: 10, scale: 3 }),
  dimensions: text("dimensions"),
  isActive: boolean("is_active").notNull().default(true),
  isCritical: boolean("is_critical").notNull().default(false),
  lastCountDate: date("last_count_date"),
  lastPurchaseDate: date("last_purchase_date"),
  expiryDate: date("expiry_date"),
  notes: text("notes"),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});
