import { pgTable, serial, text, integer, numeric, date, timestamp, boolean, varchar } from "drizzle-orm/pg-core";

export const invoicesTable = pgTable("invoices", {
  id: serial("id").primaryKey(),
  invoiceNumber: text("invoice_number").notNull().unique(),
  customerId: integer("customer_id").notNull(),
  workOrderId: integer("work_order_id"),
  quoteId: integer("quote_id"),
  type: varchar("type", { length: 30 }).notNull().default("invoice"),
  status: varchar("status", { length: 30 }).notNull().default("draft"),
  issueDate: date("issue_date").notNull().defaultNow(),
  dueDate: date("due_date"),
  subtotal: numeric("subtotal", { precision: 15, scale: 2 }).default("0"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  discountAmount: numeric("discount_amount", { precision: 15, scale: 2 }).default("0"),
  taxRate: numeric("tax_rate", { precision: 5, scale: 2 }).default("17"),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }).default("0"),
  totalAmount: numeric("total_amount", { precision: 15, scale: 2 }).default("0"),
  amountPaid: numeric("amount_paid", { precision: 15, scale: 2 }).default("0"),
  balanceDue: numeric("balance_due", { precision: 15, scale: 2 }).default("0"),
  currency: varchar("currency", { length: 10 }).default("ILS"),
  paymentTerms: text("payment_terms"),
  paymentMethod: varchar("payment_method", { length: 30 }),
  paidAt: timestamp("paid_at"),
  notes: text("notes"),
  internalNotes: text("internal_notes"),
  billingAddress: text("billing_address"),
  shippingAddress: text("shipping_address"),
  contactPerson: text("contact_person"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  createdBy: integer("created_by"),
  approvedBy: integer("approved_by"),
  sentAt: timestamp("sent_at"),
  cancelledAt: timestamp("cancelled_at"),
  cancelReason: text("cancel_reason"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});

export const invoiceItemsTable = pgTable("invoice_items", {
  id: serial("id").primaryKey(),
  invoiceId: integer("invoice_id").notNull(),
  description: text("description").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 3 }).notNull().default("1"),
  unitPrice: numeric("unit_price", { precision: 15, scale: 2 }).notNull().default("0"),
  unit: varchar("unit", { length: 20 }).default("יח'"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  taxRate: numeric("tax_rate", { precision: 5, scale: 2 }).default("17"),
  lineTotal: numeric("line_total", { precision: 15, scale: 2 }).default("0"),
  itemCode: text("item_code"),
  sortOrder: integer("sort_order").default(0),
  notes: text("notes"),
});
