import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const lettersOfCreditTable = pgTable("letters_of_credit", {
  id: serial("id").primaryKey(),
  lcNumber: text("lc_number").notNull().unique(),
  lcType: text("lc_type").notNull().default("Irrevocable"),
  status: text("status").notNull().default("טיוטה"),
  issuingBank: text("issuing_bank").notNull(),
  issuingBankBranch: text("issuing_bank_branch"),
  issuingBankSwift: text("issuing_bank_swift"),
  advisingBank: text("advising_bank"),
  advisingBankSwift: text("advising_bank_swift"),
  confirmingBank: text("confirming_bank"),
  applicantName: text("applicant_name").notNull(),
  applicantAddress: text("applicant_address"),
  beneficiaryName: text("beneficiary_name").notNull(),
  beneficiaryAddress: text("beneficiary_address"),
  beneficiaryCountry: text("beneficiary_country"),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull().default("0"),
  currency: text("currency").notNull().default("USD"),
  amountTolerancePlus: numeric("amount_tolerance_plus", { precision: 5, scale: 2 }).default("0"),
  amountToleranceMinus: numeric("amount_tolerance_minus", { precision: 5, scale: 2 }).default("0"),
  amountInWords: text("amount_in_words"),
  issueDate: date("issue_date"),
  expiryDate: date("expiry_date").notNull(),
  expiryPlace: text("expiry_place"),
  latestShipmentDate: date("latest_shipment_date"),
  presentationPeriod: integer("presentation_period").default(21),
  partialShipments: text("partial_shipments").default("Allowed"),
  transshipment: text("transshipment").default("Allowed"),
  incoterms: text("incoterms").default("FOB"),
  portOfLoading: text("port_of_loading"),
  portOfDischarge: text("port_of_discharge"),
  countryOfOrigin: text("country_of_origin"),
  goodsDescription: text("goods_description"),
  hsCode: text("hs_code"),
  linkedImportOrderId: integer("linked_import_order_id"),
  linkedSupplierId: integer("linked_supplier_id"),
  requiredDocuments: text("required_documents"),
  additionalConditions: text("additional_conditions"),
  paymentTerms: text("payment_terms").default("At Sight"),
  deferredPaymentDays: integer("deferred_payment_days"),
  chargesApplicant: text("charges_applicant").default("Opening charges"),
  chargesBeneficiary: text("charges_beneficiary").default("Advising charges"),
  commissionRate: numeric("commission_rate", { precision: 5, scale: 3 }).default("0"),
  commissionAmount: numeric("commission_amount", { precision: 15, scale: 2 }).default("0"),
  insuranceRequired: boolean("insurance_required").default(false),
  insuranceCoverage: numeric("insurance_coverage", { precision: 5, scale: 2 }).default("110"),
  amendmentCount: integer("amendment_count").default(0),
  lastAmendmentDate: date("last_amendment_date"),
  negotiationDate: date("negotiation_date"),
  paymentDate: date("payment_date"),
  paidAmount: numeric("paid_amount", { precision: 15, scale: 2 }).default("0"),
  outstandingAmount: numeric("outstanding_amount", { precision: 15, scale: 2 }).default("0"),
  discrepancyNotes: text("discrepancy_notes"),
  rejectionReason: text("rejection_reason"),
  swiftMessageType: text("swift_message_type").default("MT700"),
  ucpVersion: text("ucp_version").default("UCP 600"),
  governingLaw: text("governing_law").default("ICC Rules"),
  notes: text("notes"),
  createdBy: text("created_by"),
  approvedBy: text("approved_by"),
  approvedDate: date("approved_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const lcAmendmentsTable = pgTable("lc_amendments", {
  id: serial("id").primaryKey(),
  lcId: integer("lc_id").notNull(),
  amendmentNumber: integer("amendment_number").notNull().default(1),
  amendmentDate: date("amendment_date").notNull(),
  amendmentType: text("amendment_type").notNull().default("שינוי סכום"),
  description: text("description").notNull(),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  status: text("status").notNull().default("ממתין"),
  requestedBy: text("requested_by"),
  approvedBy: text("approved_by"),
  approvedDate: date("approved_date"),
  bankReference: text("bank_reference"),
  feeAmount: numeric("fee_amount", { precision: 15, scale: 2 }).default("0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
