import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const marketingCampaignsTable = pgTable("marketing_campaigns", {
  id: serial("id").primaryKey(),
  campaignName: text("campaign_name").notNull(),
  description: text("description"),
  channel: text("channel"),
  targetAudience: text("target_audience"),
  budget: numeric("budget", { precision: 15, scale: 2 }).default("0"),
  actualSpend: numeric("actual_spend", { precision: 15, scale: 2 }).default("0"),
  startDate: date("start_date"),
  endDate: date("end_date"),
  leadsCount: integer("leads_count").default(0),
  conversions: integer("conversions").default(0),
  revenue: numeric("revenue", { precision: 15, scale: 2 }).default("0"),
  roi: numeric("roi", { precision: 10, scale: 2 }),
  manager: text("manager"),
  status: text("status").default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const contentCalendarTable = pgTable("content_calendar", {
  id: serial("id").primaryKey(),
  contentTitle: text("content_title").notNull(),
  contentType: text("content_type"),
  channel: text("channel"),
  plannedDate: date("planned_date"),
  publishTime: text("publish_time"),
  contentText: text("content_text"),
  creativeLink: text("creative_link"),
  assignee: text("assignee"),
  status: text("status").default("planned"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const socialMediaTable = pgTable("social_media_metrics", {
  id: serial("id").primaryKey(),
  platform: text("platform").notNull(),
  accountName: text("account_name"),
  followers: integer("followers").default(0),
  followersChange: integer("followers_change").default(0),
  posts: integer("posts").default(0),
  engagement: numeric("engagement", { precision: 10, scale: 2 }).default("0"),
  reach: integer("reach").default(0),
  impressions: integer("impressions").default(0),
  clicks: integer("clicks").default(0),
  shares: integer("shares").default(0),
  metricDate: date("metric_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const emailMarketingTable = pgTable("email_marketing", {
  id: serial("id").primaryKey(),
  campaignName: text("campaign_name").notNull(),
  subject: text("subject"),
  listName: text("list_name"),
  recipients: integer("recipients").default(0),
  sent: integer("sent").default(0),
  delivered: integer("delivered").default(0),
  opens: integer("opens").default(0),
  clicks: integer("clicks").default(0),
  bounces: integer("bounces").default(0),
  unsubscribes: integer("unsubscribes").default(0),
  openRate: numeric("open_rate", { precision: 5, scale: 2 }),
  clickRate: numeric("click_rate", { precision: 5, scale: 2 }),
  sendDate: date("send_date"),
  status: text("status").default("draft"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const marketingBudgetTable = pgTable("marketing_budget", {
  id: serial("id").primaryKey(),
  budgetName: text("budget_name").notNull(),
  channel: text("channel"),
  campaignRef: text("campaign_ref"),
  month: text("month"),
  year: integer("year"),
  plannedBudget: numeric("planned_budget", { precision: 15, scale: 2 }).default("0"),
  actualSpend: numeric("actual_spend", { precision: 15, scale: 2 }).default("0"),
  remaining: numeric("remaining", { precision: 15, scale: 2 }).default("0"),
  roi: numeric("roi", { precision: 10, scale: 2 }),
  status: text("status").default("active"),
  approvedBy: text("approved_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
