import { pgTable, serial, text, integer, numeric, timestamp, varchar, date, boolean } from "drizzle-orm/pg-core";

export const payrollRecordsTable = pgTable("payroll_records", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull(),
  payPeriod: varchar("pay_period", { length: 20 }).notNull(),
  payYear: integer("pay_year").notNull(),
  payMonth: integer("pay_month").notNull(),
  status: varchar("status", { length: 30 }).default("draft"),
  baseSalary: numeric("base_salary", { precision: 12, scale: 2 }).default("0"),
  overtimeHours: numeric("overtime_hours", { precision: 6, scale: 2 }).default("0"),
  overtimePay: numeric("overtime_pay", { precision: 12, scale: 2 }).default("0"),
  bonuses: numeric("bonuses", { precision: 12, scale: 2 }).default("0"),
  commissions: numeric("commissions", { precision: 12, scale: 2 }).default("0"),
  travelAllowance: numeric("travel_allowance", { precision: 12, scale: 2 }).default("0"),
  mealAllowance: numeric("meal_allowance", { precision: 12, scale: 2 }).default("0"),
  grossPay: numeric("gross_pay", { precision: 12, scale: 2 }).default("0"),
  incomeTax: numeric("income_tax", { precision: 12, scale: 2 }).default("0"),
  nationalInsurance: numeric("national_insurance", { precision: 12, scale: 2 }).default("0"),
  healthInsurance: numeric("health_insurance", { precision: 12, scale: 2 }).default("0"),
  pensionEmployee: numeric("pension_employee", { precision: 12, scale: 2 }).default("0"),
  pensionEmployer: numeric("pension_employer", { precision: 12, scale: 2 }).default("0"),
  educationFund: numeric("education_fund", { precision: 12, scale: 2 }).default("0"),
  otherDeductions: numeric("other_deductions", { precision: 12, scale: 2 }).default("0"),
  totalDeductions: numeric("total_deductions", { precision: 12, scale: 2 }).default("0"),
  netPay: numeric("net_pay", { precision: 12, scale: 2 }).default("0"),
  currency: varchar("currency", { length: 10 }).default("ILS"),
  paymentMethod: varchar("payment_method", { length: 30 }).default("bank_transfer"),
  paymentDate: date("payment_date"),
  bankName: varchar("bank_name", { length: 100 }),
  bankBranch: varchar("bank_branch", { length: 50 }),
  bankAccount: varchar("bank_account", { length: 50 }),
  workDays: integer("work_days"),
  sickDays: numeric("sick_days", { precision: 4, scale: 1 }).default("0"),
  vacationDays: numeric("vacation_days", { precision: 4, scale: 1 }).default("0"),
  absenceDays: numeric("absence_days", { precision: 4, scale: 1 }).default("0"),
  isApproved: boolean("is_approved").notNull().default(false),
  approvedBy: integer("approved_by"),
  approvedAt: timestamp("approved_at"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});
