import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const productRoadmapTable = pgTable("product_roadmap", {
  id: serial("id").primaryKey(),
  featureName: text("feature_name").notNull(),
  description: text("description"),
  version: text("version"),
  targetDate: date("target_date"),
  completedDate: date("completed_date"),
  status: text("status").default("planned"),
  priority: text("priority").default("medium"),
  assignee: text("assignee"),
  effort: text("effort"),
  category: text("category"),
  dependencies: text("dependencies"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const rdProjectsTable = pgTable("rd_projects", {
  id: serial("id").primaryKey(),
  projectName: text("project_name").notNull(),
  description: text("description"),
  projectType: text("project_type"),
  startDate: date("start_date"),
  endDate: date("end_date"),
  budget: numeric("budget", { precision: 15, scale: 2 }).default("0"),
  actualCost: numeric("actual_cost", { precision: 15, scale: 2 }).default("0"),
  status: text("status").default("active"),
  priority: text("priority").default("medium"),
  teamLead: text("team_lead"),
  teamSize: integer("team_size").default(1),
  successRate: numeric("success_rate", { precision: 5, scale: 2 }),
  milestones: text("milestones"),
  risks: text("risks"),
  outcomes: text("outcomes"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const featureRequestsTable = pgTable("feature_requests", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  source: text("source"),
  requesterName: text("requester_name"),
  priority: text("priority").default("medium"),
  status: text("status").default("new"),
  votes: integer("votes").default(0),
  category: text("category"),
  assignee: text("assignee"),
  targetVersion: text("target_version"),
  estimatedEffort: text("estimated_effort"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const qaTestingTable = pgTable("qa_testing", {
  id: serial("id").primaryKey(),
  testName: text("test_name").notNull(),
  version: text("version"),
  testType: text("test_type"),
  testSuite: text("test_suite"),
  tester: text("tester"),
  testDate: date("test_date"),
  result: text("result").default("ממתין"),
  bugsFound: integer("bugs_found").default(0),
  bugsCritical: integer("bugs_critical").default(0),
  bugsResolved: integer("bugs_resolved").default(0),
  coverage: numeric("coverage", { precision: 5, scale: 2 }),
  duration: text("duration"),
  environment: text("environment"),
  steps: text("steps"),
  expectedResult: text("expected_result"),
  actualResult: text("actual_result"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
