import { pgTable, serial, text, integer, boolean, timestamp, numeric, date, jsonb } from "drizzle-orm/pg-core";

export const bomTreeTable = pgTable("bom_tree", {
  id: serial("id").primaryKey(),
  bomNumber: text("bom_number").notNull(),
  productCode: text("product_code").notNull(),
  productName: text("product_name").notNull(),
  version: text("version").default("1.0"),
  bomLevel: text("bom_level").default("top"),
  parentBomId: integer("parent_bom_id"),
  componentsJson: jsonb("components_json").default([]),
  quantityPerUnit: numeric("quantity_per_unit").default("1"),
  unit: text("unit").default("unit"),
  materialCost: numeric("material_cost").default("0"),
  laborCost: numeric("labor_cost").default("0"),
  overheadCost: numeric("overhead_cost").default("0"),
  rolledUpCost: numeric("rolled_up_cost").default("0"),
  preferredSupplier: text("preferred_supplier"),
  leadTimeDays: integer("lead_time_days").default(0),
  status: text("status").default("draft"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const workInstructionsTable = pgTable("work_instructions", {
  id: serial("id").primaryKey(),
  instructionNumber: text("instruction_number").notNull(),
  title: text("title").notNull(),
  productName: text("product_name"),
  productCode: text("product_code"),
  version: text("version").default("1.0"),
  department: text("department"),
  category: text("category").default("production"),
  stepsJson: jsonb("steps_json").default([]),
  attachmentsJson: jsonb("attachments_json").default([]),
  safetyNotes: text("safety_notes"),
  qualityRequirements: text("quality_requirements"),
  toolsRequired: text("tools_required"),
  estimatedTime: integer("estimated_time").default(0),
  skillLevel: text("skill_level").default("basic"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at"),
  status: text("status").default("draft"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const productionPlanningTable = pgTable("production_planning", {
  id: serial("id").primaryKey(),
  planNumber: text("plan_number").notNull(),
  title: text("title").notNull(),
  productName: text("product_name"),
  productCode: text("product_code"),
  productionLine: text("production_line"),
  plannedQuantity: integer("planned_quantity").default(0),
  actualQuantity: integer("actual_quantity").default(0),
  unit: text("unit").default("unit"),
  startDate: date("start_date"),
  endDate: date("end_date"),
  actualStartDate: date("actual_start_date"),
  actualEndDate: date("actual_end_date"),
  priority: text("priority").default("medium"),
  status: text("status").default("draft"),
  assignedTo: text("assigned_to"),
  shiftPattern: text("shift_pattern"),
  bottleneck: text("bottleneck"),
  utilizationPercent: numeric("utilization_percent").default("0"),
  onTimePercent: numeric("on_time_percent").default("0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const qualityControlEntTable = pgTable("quality_control_ent", {
  id: serial("id").primaryKey(),
  inspectionNumber: text("inspection_number").notNull(),
  inspectionType: text("inspection_type").default("incoming"),
  inspectionDate: date("inspection_date"),
  productName: text("product_name"),
  productCode: text("product_code"),
  batchNumber: text("batch_number"),
  orderReference: text("order_reference"),
  supplierName: text("supplier_name"),
  inspectorName: text("inspector_name"),
  inspectionMethod: text("inspection_method"),
  sampleSize: integer("sample_size").default(1),
  acceptedCount: integer("accepted_count").default(0),
  rejectedCount: integer("rejected_count").default(0),
  defectType: text("defect_type"),
  defectDescription: text("defect_description"),
  severity: text("severity").default("minor"),
  result: text("result").default("pending"),
  correctiveAction: text("corrective_action"),
  preventiveAction: text("preventive_action"),
  disposition: text("disposition").default("pending"),
  reworkRequired: boolean("rework_required").default(false),
  reworkCompleted: boolean("rework_completed").default(false),
  costOfQuality: numeric("cost_of_quality").default("0"),
  certificateNumber: text("certificate_number"),
  status: text("status").default("pending"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const machineMaintenanceTable = pgTable("machine_maintenance", {
  id: serial("id").primaryKey(),
  maintenanceNumber: text("maintenance_number").notNull(),
  machineName: text("machine_name").notNull(),
  machineCode: text("machine_code"),
  location: text("location"),
  maintenanceType: text("maintenance_type").default("preventive"),
  title: text("title").notNull(),
  description: text("description"),
  frequency: text("frequency").default("monthly"),
  priority: text("priority").default("medium"),
  status: text("status").default("scheduled"),
  scheduledDate: date("scheduled_date"),
  completedDate: date("completed_date"),
  assignedTo: text("assigned_to"),
  estimatedHours: numeric("estimated_hours").default("0"),
  actualHours: numeric("actual_hours").default("0"),
  partsCost: numeric("parts_cost").default("0"),
  laborCost: numeric("labor_cost").default("0"),
  totalCost: numeric("total_cost").default("0"),
  downtimeHours: numeric("downtime_hours").default("0"),
  partsUsed: text("parts_used"),
  findings: text("findings"),
  nextMaintenanceDate: date("next_maintenance_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const productionReportsTable = pgTable("production_reports", {
  id: serial("id").primaryKey(),
  reportNumber: text("report_number").notNull(),
  reportType: text("report_type").default("daily"),
  reportDate: date("report_date"),
  periodStart: date("period_start"),
  periodEnd: date("period_end"),
  productionLine: text("production_line"),
  totalUnitsProduced: integer("total_units_produced").default(0),
  totalUnitsPlanned: integer("total_units_planned").default(0),
  defectiveUnits: integer("defective_units").default(0),
  costPerUnit: numeric("cost_per_unit").default("0"),
  totalCost: numeric("total_cost").default("0"),
  laborHours: numeric("labor_hours").default("0"),
  machineHours: numeric("machine_hours").default("0"),
  oee: numeric("oee").default("0"),
  availability: numeric("availability").default("0"),
  performance: numeric("performance").default("0"),
  quality: numeric("quality").default("0"),
  downtimeHours: numeric("downtime_hours").default("0"),
  wasteMaterial: numeric("waste_material").default("0"),
  energyConsumption: numeric("energy_consumption").default("0"),
  status: text("status").default("draft"),
  preparedBy: text("prepared_by"),
  approvedBy: text("approved_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
