import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const purchaseReturnsTable = pgTable("purchase_returns", {
  id: serial("id").primaryKey(),
  returnNumber: text("return_number").notNull().unique(),
  purchaseOrderId: integer("purchase_order_id"),
  goodsReceiptId: integer("goods_receipt_id"),
  supplierId: integer("supplier_id").notNull(),
  returnDate: date("return_date").notNull().defaultNow(),
  reasonCategory: text("reason_category").notNull().default("פגם באיכות"),
  reasonDetails: text("reason_details"),
  returnedBy: text("returned_by"),
  approvedBy: text("approved_by"),
  creditNoteNumber: text("credit_note_number"),
  creditNoteAmount: numeric("credit_note_amount").default("0"),
  creditNoteDate: date("credit_note_date"),
  creditNoteReceived: boolean("credit_note_received").default(false),
  replacementOrderId: integer("replacement_order_id"),
  replacementRequested: boolean("replacement_requested").default(false),
  shippingMethod: text("shipping_method"),
  trackingNumber: text("tracking_number"),
  warehouseLocation: text("warehouse_location"),
  totalItems: integer("total_items").default(0),
  totalValue: numeric("total_value").default("0"),
  currency: text("currency").default("ILS"),
  status: text("status").notNull().default("טיוטה"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const purchaseReturnItemsTable = pgTable("purchase_return_items", {
  id: serial("id").primaryKey(),
  returnId: integer("return_id").notNull(),
  materialId: integer("material_id"),
  itemCode: text("item_code"),
  itemName: text("item_name").notNull(),
  unit: text("unit").default("יח"),
  orderedQuantity: numeric("ordered_quantity").default("0"),
  receivedQuantity: numeric("received_quantity").default("0"),
  returnedQuantity: numeric("returned_quantity").notNull().default("0"),
  unitPrice: numeric("unit_price").default("0"),
  totalPrice: numeric("total_price").default("0"),
  reason: text("reason"),
  conditionOnReturn: text("condition_on_return").default("פגום"),
  lotNumber: text("lot_number"),
  serialNumber: text("serial_number"),
  inspectionNotes: text("inspection_notes"),
  photoUrls: text("photo_urls"),
  status: text("status").default("ממתין"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
