import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const rawMaterialsTable = pgTable("raw_materials", {
  id: serial("id").primaryKey(),
  materialNumber: text("material_number").notNull().unique(),
  materialName: text("material_name").notNull(),
  category: text("category").notNull().default("כללי"),
  subCategory: text("sub_category"),
  unit: text("unit").notNull().default("יחידה"),
  description: text("description"),
  minimumStock: numeric("minimum_stock"),
  currentStock: numeric("current_stock").default("0"),
  maximumStock: numeric("maximum_stock"),
  reorderPoint: numeric("reorder_point"),
  standardPrice: numeric("standard_price"),
  currency: text("currency").default("ILS"),
  weightPerUnit: numeric("weight_per_unit"),
  weightPerMeter: numeric("weight_per_meter"),
  dimensions: text("dimensions"),
  materialGrade: text("material_grade"),
  materialType: text("material_type"),
  finish: text("finish"),
  thickness: numeric("thickness"),
  width: numeric("width"),
  height: numeric("height"),
  warehouseLocation: text("warehouse_location").default("מחסן ראשי"),
  lastCountDate: date("last_count_date"),
  lastCountQuantity: numeric("last_count_quantity"),
  abcClassification: text("abc_classification").default("C"),
  annualUsageValue: numeric("annual_usage_value").default("0"),
  leadTimeDays: integer("lead_time_days"),
  lastReceiptDate: date("last_receipt_date"),
  lastIssueDate: date("last_issue_date"),
  supplierId: integer("supplier_id"),
  barcode: text("barcode"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  rodLength: numeric("rod_length"),
  pricingMethod: text("pricing_method").default("יחידה"),
  pricePerMeter: numeric("price_per_meter"),
  pricePerKg: numeric("price_per_kg"),
  packageQuantity: numeric("package_quantity"),
  totalPriceBeforeVat: numeric("total_price_before_vat"),
  totalPriceAfterVat: numeric("total_price_after_vat"),
  diameter: numeric("diameter"),
  innerDiameter: numeric("inner_diameter"),
  innerType: text("inner_type"),
  standard: text("standard"),
  countryOfOrigin: text("country_of_origin"),
  color: text("color"),
  minimumOrder: numeric("minimum_order"),
  deliveryDays: integer("delivery_days"),
  warrantyMonths: integer("warranty_months"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  hazardClass: text("hazard_class"),
  shelfLifeDays: integer("shelf_life_days"),
  lotTracking: boolean("lot_tracking").default(false),
  serialTracking: boolean("serial_tracking").default(false),
  inspectionRequired: boolean("inspection_required").default(false),
  qualityGrade: text("quality_grade"),
  preferredSupplierId: integer("preferred_supplier_id"),
  alternateSupplierId: integer("alternate_supplier_id"),
  economicOrderQty: numeric("economic_order_qty"),
  safetyStock: numeric("safety_stock").default("0"),
  lastPurchasePrice: numeric("last_purchase_price"),
  averageCost: numeric("average_cost"),
  standardCost: numeric("standard_cost"),
  customsTariffCode: text("customs_tariff_code"),
  storageConditions: text("storage_conditions"),
  handlingInstructions: text("handling_instructions"),
  msdsUrl: text("msds_url"),
  imageUrl: text("image_url"),
  // TASK 3: Enhanced product/material fields
  productCode: text("product_code"),
  sku: text("sku"),
  categoryL1: text("category_l1"),
  categoryL2: text("category_l2"),
  uomStock: text("uom_stock").default("יחידה"),
  uomPurchase: text("uom_purchase"),
  weightKg: numeric("weight_kg", { precision: 10, scale: 2 }),
  lengthMm: numeric("length_mm", { precision: 10, scale: 2 }),
  widthMm: numeric("width_mm", { precision: 10, scale: 2 }),
  heightMm: numeric("height_mm", { precision: 10, scale: 2 }),
  costPrice: numeric("cost_price", { precision: 15, scale: 2 }),
  sellingPrice: numeric("selling_price", { precision: 15, scale: 2 }),
  vatRate: numeric("vat_rate", { precision: 5, scale: 2 }).default("18"),
  hsTariffCode: text("hs_tariff_code"),
  trackSerial: boolean("track_serial").default(false),
  trackBatch: boolean("track_batch").default(false),
  primarySupplierId: integer("primary_supplier_id"),
  isActive: boolean("is_active").default(true),
  deletedAt: timestamp("deleted_at"),
});

export const materialCategoriesTable = pgTable("material_categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  parentCategory: text("parent_category"),
  description: text("description"),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierMaterialsTable = pgTable("supplier_materials", {
  id: serial("id").primaryKey(),
  supplierId: numeric("supplier_id").notNull(),
  materialId: numeric("material_id").notNull(),
  supplierMaterialCode: text("supplier_material_code"),
  supplierPrice: numeric("supplier_price"),
  currency: text("currency").default("ILS"),
  leadTimeDays: numeric("lead_time_days"),
  minimumOrderQty: numeric("minimum_order_qty"),
  isPreferred: text("is_preferred").default("false"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
