import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const salesCustomersTable = pgTable("sales_customers", {
  id: serial("id").primaryKey(),
  customerNumber: text("customer_number").unique(),
  name: text("name").notNull(),
  customerType: text("customer_type").default("company"),
  email: text("email"),
  phone: text("phone"),
  mobile: text("mobile"),
  fax: text("fax"),
  website: text("website"),
  address: text("address"),
  city: text("city"),
  country: text("country").default("ישראל"),
  postalCode: text("postal_code"),
  region: text("region"),
  billingAddress: text("billing_address"),
  shippingAddress: text("shipping_address"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }).default("0"),
  paymentTerms: text("payment_terms").default("שוטף 30"),
  creditTermsDays: integer("credit_terms_days").default(30),
  currency: text("currency").default("ILS"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  paymentMethod: text("payment_method"),
  vatExempt: boolean("vat_exempt").default(false),
  withholdingTaxRate: numeric("withholding_tax_rate", { precision: 5, scale: 2 }).default("0"),
  bankName: text("bank_name"),
  bankBranch: text("bank_branch"),
  bankAccount: text("bank_account"),
  assignedRep: text("assigned_rep"),
  salespersonId: integer("salesperson_id"),
  status: text("status").default("active"),
  tags: text("tags"),
  contactPerson: text("contact_person"),
  taxId: text("tax_id"),
  notes: text("notes"),
  internalNotes: text("internal_notes"),
  industry: text("industry"),
  category: text("category").default("רגיל"),
  source: text("source"),
  companySize: text("company_size"),
  secondaryContact: text("secondary_contact"),
  secondaryPhone: text("secondary_phone"),
  secondaryEmail: text("secondary_email"),
  languagePref: text("language_pref").default("he"),
  communicationPref: text("communication_pref").default("phone"),
  preferredDelivery: text("preferred_delivery"),
  priceListId: integer("price_list_id"),
  acquisitionSource: text("acquisition_source"),
  customerSince: date("customer_since"),
  totalRevenue: numeric("total_revenue", { precision: 15, scale: 2 }).default("0"),
  outstandingBalance: numeric("outstanding_balance", { precision: 15, scale: 2 }).default("0"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
