import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";
import { customersTable } from "./customers";

export const salesOrdersTable = pgTable("sales_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  orderType: text("order_type").default("standard"),
  orderSource: text("order_source").default("sales"),
  customerId: integer("customer_id").notNull().references(() => customersTable.id),
  customerName: text("customer_name").notNull(),
  salespersonId: integer("salesperson_id"),
  orderDate: date("order_date").defaultNow(),
  requestedDeliveryDate: date("requested_delivery_date"),
  status: text("status").notNull().default("draft"),
  subtotal: numeric("subtotal", { precision: 15, scale: 2 }).default("0"),
  vatPercent: numeric("vat_percent", { precision: 5, scale: 2 }).default("18"),
  vatAmount: numeric("vat_amount", { precision: 15, scale: 2 }).default("0"),
  totalAmount: numeric("total_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  paymentTerms: text("payment_terms"),
  paymentMethod: text("payment_method"),
  shippingMethod: text("shipping_method"),
  shippingAddress: text("shipping_address"),
  shippingCost: numeric("shipping_cost", { precision: 15, scale: 2 }).default("0"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  discountAmount: numeric("discount_amount", { precision: 15, scale: 2 }).default("0"),
  profitMarginPct: numeric("profit_margin_pct", { precision: 5, scale: 2 }).default("0"),
  notes: text("notes"),
  internalNotes: text("internal_notes"),
  attachmentsJson: text("attachments_json"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});

export const salesOrderItemsTable = pgTable("sales_order_items", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => salesOrdersTable.id),
  materialId: integer("material_id"),
  productCode: text("product_code"),
  productName: text("product_name").notNull(),
  quantity: numeric("quantity").notNull().default("1"),
  unit: text("unit").default("יחידה"),
  unitPrice: numeric("unit_price", { precision: 15, scale: 2 }).notNull().default("0"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  vatPercent: numeric("vat_percent", { precision: 5, scale: 2 }).default("18"),
  totalPrice: numeric("total_price", { precision: 15, scale: 2 }).notNull().default("0"),
  deliveredQuantity: numeric("delivered_quantity", { precision: 10, scale: 2 }).default("0"),
  reservedQuantity: numeric("reserved_quantity", { precision: 10, scale: 2 }).default("0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
