import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const shipmentTrackingTable = pgTable("shipment_tracking", {
  id: serial("id").primaryKey(),
  shipmentNumber: text("shipment_number").notNull().unique(),
  importOrderId: integer("import_order_id"),
  carrierName: text("carrier_name"),
  carrierType: text("carrier_type").default("sea"),
  trackingNumber: text("tracking_number"),
  bookingNumber: text("booking_number"),
  vesselName: text("vessel_name"),
  voyageNumber: text("voyage_number"),
  originPort: text("origin_port"),
  destinationPort: text("destination_port").default("חיפה"),
  originCountry: text("origin_country"),
  etd: date("etd"),
  eta: date("eta"),
  actualDeparture: date("actual_departure"),
  actualArrival: date("actual_arrival"),
  containerNumber: text("container_number"),
  containerType: text("container_type"),
  containerCount: integer("container_count").default(1),
  sealNumber: text("seal_number"),
  billOfLading: text("bill_of_lading"),
  goodsDescription: text("goods_description"),
  weightKg: numeric("weight_kg", { precision: 12, scale: 2 }),
  volumeCbm: numeric("volume_cbm", { precision: 12, scale: 2 }),
  packagesCount: integer("packages_count"),
  freightCost: numeric("freight_cost", { precision: 15, scale: 2 }).default("0"),
  freightCurrency: text("freight_currency").default("USD"),
  insuranceValue: numeric("insurance_value", { precision: 15, scale: 2 }).default("0"),
  goodsValue: numeric("goods_value", { precision: 15, scale: 2 }).default("0"),
  supplierName: text("supplier_name"),
  consignee: text("consignee"),
  notifyParty: text("notify_party"),
  forwardingAgent: text("forwarding_agent"),
  agentPhone: text("agent_phone"),
  agentEmail: text("agent_email"),
  customsBroker: text("customs_broker"),
  currentLocation: text("current_location"),
  lastUpdateDate: timestamp("last_update_date"),
  delayDays: integer("delay_days").default(0),
  delayReason: text("delay_reason"),
  notes: text("notes"),
  status: text("status").notNull().default("הוזמן"),
  priority: text("priority").default("רגילה"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const shipmentStatusUpdatesTable = pgTable("shipment_status_updates", {
  id: serial("id").primaryKey(),
  shipmentId: integer("shipment_id").notNull(),
  status: text("status").notNull(),
  location: text("location"),
  description: text("description"),
  updateDate: timestamp("update_date").notNull().defaultNow(),
  updatedBy: text("updated_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
