import { pgTable, serial, text, integer, boolean, timestamp, jsonb, numeric } from "drizzle-orm/pg-core";

export const supplierPortalAccountsTable = pgTable("supplier_portal_accounts", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id"),
  supplierName: text("supplier_name").notNull(),
  contactEmail: text("contact_email").notNull().unique(),
  contactName: text("contact_name"),
  passwordHash: text("password_hash"),
  inviteToken: text("invite_token").unique(),
  inviteExpiry: timestamp("invite_expiry"),
  isActive: boolean("is_active").default(true),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierPerformanceScoresTable = pgTable("supplier_performance_scores", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  supplierName: text("supplier_name"),
  onTimeDeliveryRate: numeric("on_time_delivery_rate", { precision: 5, scale: 2 }),
  qualityRejectRate: numeric("quality_reject_rate", { precision: 5, scale: 2 }),
  priceCompetitivenessIndex: numeric("price_competitiveness_index", { precision: 5, scale: 2 }),
  responsivenessScore: numeric("responsiveness_score", { precision: 5, scale: 2 }),
  overallScore: numeric("overall_score", { precision: 5, scale: 2 }),
  scoreTrend: text("score_trend"),
  lastCalculatedAt: timestamp("last_calculated_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierContractsTable = pgTable("supplier_contracts", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  supplierName: text("supplier_name"),
  contractNumber: text("contract_number").notNull().unique(),
  contractName: text("contract_name"),
  description: text("description"),
  startDate: timestamp("start_date").notNull(),
  endDate: timestamp("end_date").notNull(),
  autoRenew: boolean("auto_renew").default(false),
  renewalTermDays: integer("renewal_term_days"),
  paymentTerms: text("payment_terms"),
  pricingStructure: jsonb("pricing_structure").default({}),
  volumeDiscountTiers: jsonb("volume_discount_tiers").default([]),
  deliveryTerms: text("delivery_terms"),
  qualityRequirements: jsonb("quality_requirements").default({}),
  status: text("status").notNull().default("active"),
  attachments: jsonb("attachments").default([]),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierContractAlertsTable = pgTable("supplier_contract_alerts", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").notNull().references(() => supplierContractsTable.id, { onDelete: "cascade" }),
  supplierId: integer("supplier_id").notNull(),
  alertType: text("alert_type").notNull(),
  daysUntilExpiry: integer("days_until_expiry"),
  message: text("message"),
  severity: text("severity").notNull().default("warning"),
  status: text("status").notNull().default("active"),
  acknowledgedAt: timestamp("acknowledged_at"),
  acknowledgedBy: text("acknowledged_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const supplierInvoiceSubmissionsTable = pgTable("supplier_invoice_submissions", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  supplierEmail: text("supplier_email"),
  poNumber: text("po_number"),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: timestamp("invoice_date"),
  invoiceAmount: numeric("invoice_amount", { precision: 15, scale: 2 }),
  currency: text("currency").default("USD"),
  lineItems: jsonb("line_items").default([]),
  attachments: jsonb("attachments").default([]),
  submittedAt: timestamp("submitted_at"),
  status: text("status").notNull().default("submitted"),
  matchingStatus: text("matching_status"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierDeliveryUpdatesTable = pgTable("supplier_delivery_updates", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  poNumber: text("po_number").notNull(),
  currentEta: timestamp("current_eta"),
  originalEta: timestamp("original_eta"),
  status: text("status").notNull().default("on_track"),
  delayReason: text("delay_reason"),
  quantityShipped: numeric("quantity_shipped", { precision: 15, scale: 2 }),
  shipmentTrackingId: text("shipment_tracking_id"),
  estimatedDeliveryDate: timestamp("estimated_delivery_date"),
  updatedBy: text("updated_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierCertificationsTable = pgTable("supplier_certifications", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  certificationName: text("certification_name").notNull(),
  certificateNumber: text("certificate_number"),
  issuanceDate: timestamp("issuance_date"),
  expiryDate: timestamp("expiry_date"),
  issuingBody: text("issuing_body"),
  fileUrl: text("file_url"),
  verificationStatus: text("verification_status").default("pending"),
  verifiedBy: text("verified_by"),
  verifiedAt: timestamp("verified_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierRiskAssessmentTable = pgTable("supplier_risk_assessment", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  supplierName: text("supplier_name"),
  singleSourceDependency: boolean("single_source_dependency").default(false),
  geographicRisk: numeric("geographic_risk", { precision: 5, scale: 2 }),
  financialHealthScore: numeric("financial_health_score", { precision: 5, scale: 2 }),
  creditRating: text("credit_rating"),
  paymentHistoryScore: numeric("payment_history_score", { precision: 5, scale: 2 }),
  complianceScore: numeric("compliance_score", { precision: 5, scale: 2 }),
  overallRiskScore: numeric("overall_risk_score", { precision: 5, scale: 2 }),
  riskLevel: text("risk_level").notNull(),
  riskFactors: jsonb("risk_factors").default([]),
  recommendations: jsonb("recommendations").default([]),
  lastAssessedAt: timestamp("last_assessed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const supplierRiskAlertsTable = pgTable("supplier_risk_alerts", {
  id: serial("id").primaryKey(),
  supplierId: integer("supplier_id").notNull(),
  riskAssessmentId: integer("risk_assessment_id").references(() => supplierRiskAssessmentTable.id, { onDelete: "cascade" }),
  alertType: text("alert_type").notNull(),
  severity: text("severity").notNull(),
  message: text("message"),
  details: jsonb("details").default({}),
  status: text("status").notNull().default("active"),
  acknowledgedAt: timestamp("acknowledged_at"),
  acknowledgedBy: text("acknowledged_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
