import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const taxRecordsTable = pgTable("tax_records", {
  id: serial("id").primaryKey(),
  recordNumber: text("record_number").notNull(),
  taxType: text("tax_type").default("vat"),
  taxPeriod: text("tax_period"),
  periodStart: date("period_start"),
  periodEnd: date("period_end"),
  filingDeadline: date("filing_deadline"),
  filingDate: date("filing_date"),
  taxBase: numeric("tax_base", { precision: 15, scale: 2 }).default("0"),
  taxRate: numeric("tax_rate", { precision: 5, scale: 2 }).default("18"),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }).default("0"),
  inputVat: numeric("input_vat", { precision: 15, scale: 2 }).default("0"),
  outputVat: numeric("output_vat", { precision: 15, scale: 2 }).default("0"),
  netVat: numeric("net_vat", { precision: 15, scale: 2 }).default("0"),
  withholdingTax: numeric("withholding_tax", { precision: 15, scale: 2 }).default("0"),
  advancePayments: numeric("advance_payments", { precision: 15, scale: 2 }).default("0"),
  amountDue: numeric("amount_due", { precision: 15, scale: 2 }).default("0"),
  amountPaid: numeric("amount_paid", { precision: 15, scale: 2 }).default("0"),
  balanceDue: numeric("balance_due", { precision: 15, scale: 2 }).default("0"),
  paymentDate: date("payment_date"),
  paymentReference: text("payment_reference"),
  status: text("status").default("pending"),
  filingStatus: text("filing_status").default("not_filed"),
  confirmationNumber: text("confirmation_number"),
  taxAuthority: text("tax_authority").default("רשות המסים"),
  currency: text("currency").default("ILS"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdByName: text("created_by_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
