import { pgTable, serial, text, boolean, timestamp, varchar, integer, numeric, date, doublePrecision } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id: serial("id").primaryKey(),
  username: varchar("username", { length: 100 }).notNull().unique(),
  email: varchar("email", { length: 255 }).unique(),
  passwordHash: text("password_hash").notNull(),
  fullName: varchar("full_name", { length: 200 }).notNull(),
  fullNameHe: varchar("full_name_he", { length: 200 }),
  phone: varchar("phone", { length: 50 }),
  mobile: varchar("mobile", { length: 30 }),
  department: varchar("department", { length: 100 }),
  jobTitle: varchar("job_title", { length: 100 }),
  avatarUrl: text("avatar_url"),
  isActive: boolean("is_active").notNull().default(true),
  isSuperAdmin: boolean("is_super_admin").notNull().default(false),
  lastLoginAt: timestamp("last_login_at"),
  loginCount: integer("login_count").notNull().default(0),
  failedLoginAttempts: integer("failed_login_attempts").notNull().default(0),
  lockedUntil: timestamp("locked_until"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  employeeNumber: varchar("employee_number", { length: 30 }),
  idNumber: varchar("id_number", { length: 20 }),
  dateOfBirth: date("date_of_birth"),
  gender: varchar("gender", { length: 10 }),
  maritalStatus: varchar("marital_status", { length: 20 }),
  nationality: varchar("nationality", { length: 50 }).default("ישראלי"),
  address: text("address"),
  city: varchar("city", { length: 100 }),
  zipCode: varchar("zip_code", { length: 20 }),
  emergencyContactName: varchar("emergency_contact_name", { length: 200 }),
  emergencyContactPhone: varchar("emergency_contact_phone", { length: 30 }),
  emergencyContactRelation: varchar("emergency_contact_relation", { length: 50 }),
  hireDate: date("hire_date"),
  probationEndDate: date("probation_end_date"),
  terminationDate: date("termination_date"),
  terminationReason: text("termination_reason"),
  employmentType: varchar("employment_type", { length: 30 }).default("full_time"),
  workSchedule: varchar("work_schedule", { length: 50 }).default("regular"),
  weeklyHours: numeric("weekly_hours").default("42"),
  salary: numeric("salary"),
  salaryCurrency: varchar("salary_currency", { length: 10 }).default("ILS"),
  payFrequency: varchar("pay_frequency", { length: 20 }).default("monthly"),
  bankName: varchar("bank_name", { length: 100 }),
  bankBranch: varchar("bank_branch", { length: 50 }),
  bankAccountNumber: varchar("bank_account_number", { length: 50 }),
  taxBracket: varchar("tax_bracket", { length: 20 }),
  taxCredits: numeric("tax_credits").default("0"),
  pensionPlan: varchar("pension_plan", { length: 100 }),
  pensionEmployeeRate: numeric("pension_employee_rate").default("6"),
  pensionEmployerRate: numeric("pension_employer_rate").default("6.5"),
  healthInsurance: varchar("health_insurance", { length: 100 }),
  educationFundRate: numeric("education_fund_rate").default("2.5"),
  vacationDaysAnnual: integer("vacation_days_annual").default(12),
  vacationDaysUsed: numeric("vacation_days_used").default("0"),
  vacationDaysBalance: numeric("vacation_days_balance").default("0"),
  sickDaysAnnual: integer("sick_days_annual").default(18),
  sickDaysUsed: numeric("sick_days_used").default("0"),
  sickDaysBalance: numeric("sick_days_balance").default("0"),
  managerId: integer("manager_id"),
  costCenter: varchar("cost_center", { length: 50 }),
  workLocation: varchar("work_location", { length: 100 }).default("מפעל ראשי"),
  shift: varchar("shift", { length: 30 }),
  skills: text("skills"),
  certifications: text("certifications"),
  driversLicense: varchar("drivers_license", { length: 20 }),
  vehicleType: varchar("vehicle_type", { length: 50 }),
  vehiclePlate: varchar("vehicle_plate", { length: 20 }),
  uniformSize: varchar("uniform_size", { length: 10 }),
  shoeSize: varchar("shoe_size", { length: 10 }),
  safetyTrainingDate: date("safety_training_date"),
  safetyTrainingExpiry: date("safety_training_expiry"),
  medicalExamDate: date("medical_exam_date"),
  medicalExamExpiry: date("medical_exam_expiry"),
  notes: text("notes"),
  profileImageUrl: text("profile_image_url"),
  digitalSignatureUrl: text("digital_signature_url"),
  gpsEnabled: boolean("gps_enabled").notNull().default(true),
  gpsDeviceId: text("gps_device_id"),
  deletedAt: timestamp("deleted_at"),
});

export const userGpsStatusTable = pgTable("user_gps_status", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().unique().references(() => usersTable.id, { onDelete: "cascade" }),
  lastLatitude: doublePrecision("last_latitude"),
  lastLongitude: doublePrecision("last_longitude"),
  lastAccuracy: doublePrecision("last_accuracy"),
  lastSpeed: doublePrecision("last_speed"),
  lastBatteryLevel: doublePrecision("last_battery_level"),
  lastHeading: doublePrecision("last_heading"),
  lastAltitude: doublePrecision("last_altitude"),
  lastAddress: text("last_address"),
  lastPingAt: timestamp("last_ping_at", { withTimezone: true }),
  totalPings: integer("total_pings").default(0),
  totalDistanceKm: doublePrecision("total_distance_km").default(0),
  isMoving: boolean("is_moving").default(false),
  status: text("status").default("idle"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const userSessionsTable = pgTable("user_sessions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id),
  token: varchar("token", { length: 512 }).notNull().unique(),
  ipAddress: varchar("ip_address", { length: 45 }),
  userAgent: text("user_agent"),
  fingerprint: varchar("fingerprint", { length: 256 }),
  deviceName: varchar("device_name", { length: 200 }),
  location: varchar("location", { length: 200 }),
  isActive: boolean("is_active").notNull().default(true),
  isMfaVerified: boolean("is_mfa_verified").notNull().default(false),
  expiresAt: timestamp("expires_at").notNull(),
  absoluteExpiresAt: timestamp("absolute_expires_at"),
  lastActivityAt: timestamp("last_activity_at").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
