import { Router, type IRouter, type Request, type Response, type NextFunction } from "express";
import modulesRouter from "./modules";
import entitiesRouter from "./entities";
import fieldsRouter from "./fields";
import relationsRouter from "./relations";
import recordsRouter from "./records";
import statusesRouter from "./statuses";
import viewsRouter from "./views";
import formsRouter from "./forms";
import actionsRouter from "./actions";
import categoriesRouter from "./categories";
import categoryDefinitionsRouter from "./category-definitions";
import validationsRouter from "./validations";
import auditRouter from "./audit";
import widgetsRouter from "./widgets";
import workflowsRouter from "./workflows";
import detailsRouter from "./details";
import rolesRouter from "./roles";
import permissionsRouter from "./permissions";
import menuItemsRouter from "./menu-items";
import automationsRouter from "./automations";
import templatesRouter from "./templates";
import dashboardPagesRouter from "./dashboard-pages";
import reportsRouter from "./reports";
import documentsRouter from "./documents";
import integrationsRouter from "./integrations";
import aiBuilderRouter from "./ai-builder";
import supplierMigrationRouter from "./supplier-migration";
import hrMigrationRouter from "./hr-migration";
import dmsMigrationRouter from "./dms-migration";
import buttonsRouter from "./buttons";
import buttonDefinitionsRouter from "./button-definitions";
import categoryItemsRouter from "./category-items";
import detailPageDefinitionsRouter from "./detail-page-definitions";
import versionsRouter from "./versions";
import childRecordsRouter from "./child-records";
import approvalsRouter from "./approvals";
import webhooksReceiverRouter from "./webhooks-receiver";
import governanceRouter from "./governance";
import toolsRouter from "./tools";
import contextsRouter from "./contexts";
import strategyModulesMigrationRouter from "./strategy-modules-migration";
import meetingsRouter from "./meetings";
import contentTemplatesRouter from "./content-templates";
import usersRouter from "./users";
import settingsRouter from "./settings";
import localesRouter from "./locales";
import translationsRouter from "./translations";
import menuDefinitionsRouter from "./menu-definitions";
import rolePermissionsRouter from "./role-permissions";
import moduleVersionsRouter from "./module-versions";
import messagingRouter from "./messaging";
import approvalChainsRouter from "./approval-chains";
import businessRulesRouter from "./business-rules";
import webhooksManagementRouter from "./webhooks-management";
import scheduledTasksRouter from "./scheduled-tasks";

const router: IRouter = Router();

function requireSuperAdminForDelete(req: Request, res: Response, next: NextFunction) {
  const isDeleteMethod = req.method === "DELETE";
  const isBulkDeletePost = req.method === "POST" && req.path.endsWith("/bulk-delete");
  if (!isDeleteMethod && !isBulkDeletePost) return next();
  const permissions = (req as any).permissions;
  if (!permissions?.isSuperAdmin) {
    return res.status(403).json({ error: "מחיקה מותרת רק למנהל מערכת ראשי" });
  }
  return next();
}

router.use(requireSuperAdminForDelete);
router.use(webhooksReceiverRouter);
router.use(modulesRouter);
router.use(entitiesRouter);
router.use(fieldsRouter);
router.use(relationsRouter);
router.use(recordsRouter);
router.use(statusesRouter);
router.use(viewsRouter);
router.use(formsRouter);
router.use(actionsRouter);
router.use(categoriesRouter);
router.use(categoryDefinitionsRouter);
router.use(validationsRouter);
router.use(auditRouter);
router.use(widgetsRouter);
router.use(workflowsRouter);
router.use(detailsRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(menuItemsRouter);
router.use(automationsRouter);
router.use(templatesRouter);
router.use(dashboardPagesRouter);
router.use(reportsRouter);
router.use(documentsRouter);
router.use(integrationsRouter);
router.use(aiBuilderRouter);
router.use(supplierMigrationRouter);
router.use(hrMigrationRouter);
router.use(dmsMigrationRouter);
router.use(buttonsRouter);
router.use(buttonDefinitionsRouter);
router.use(categoryItemsRouter);
router.use(detailPageDefinitionsRouter);
router.use(versionsRouter);
router.use(childRecordsRouter);
router.use(approvalsRouter);
router.use(governanceRouter);
router.use(toolsRouter);
router.use(contextsRouter);
router.use(strategyModulesMigrationRouter);
router.use(meetingsRouter);
router.use(contentTemplatesRouter);
router.use(usersRouter);
router.use(settingsRouter);
router.use(localesRouter);
router.use(translationsRouter);
router.use(menuDefinitionsRouter);
router.use(rolePermissionsRouter);
router.use(moduleVersionsRouter);
router.use(messagingRouter);
router.use(approvalChainsRouter);
router.use(businessRulesRouter);
router.use(webhooksManagementRouter);
router.use(scheduledTasksRouter);

export default router;
