import { pgTable, serial, text, numeric, timestamp, integer, date, boolean, varchar } from "drizzle-orm/pg-core";

export const budgetsTable = pgTable("budgets", {
  id: serial("id").primaryKey(),
  budgetNumber: text("budget_number"),
  budgetName: text("budget_name").notNull(),
  budgetType: text("budget_type").default("תפעולי"),
  fiscalYear: integer("fiscal_year").notNull(),
  fiscalMonth: integer("fiscal_month"),
  category: varchar("category", { length: 50 }).notNull(),
  department: varchar("department", { length: 50 }),
  budgetedAmount: numeric("budgeted_amount", { precision: 15, scale: 2 }).notNull(),
  actualAmount: numeric("actual_amount", { precision: 15, scale: 2 }).default("0"),
  committedAmount: numeric("committed_amount", { precision: 15, scale: 2 }).default("0"),
  forecastAmount: numeric("forecast_amount", { precision: 15, scale: 2 }).default("0"),
  variance: numeric("variance", { precision: 15, scale: 2 }),
  remainingAmount: numeric("remaining_amount", { precision: 15, scale: 2 }),
  utilizationPct: numeric("utilization_pct", { precision: 5, scale: 2 }),
  projectId: integer("project_id"),
  status: text("status").default("active"),
  approvedBy: text("approved_by"),
  approvedDate: date("approved_date"),
  alertThreshold80: boolean("alert_threshold_80").default(true),
  alertThreshold90: boolean("alert_threshold_90").default(true),
  alertThreshold100: boolean("alert_threshold_100").default(true),
  responsiblePerson: text("responsible_person"),
  priority: text("priority").default("רגילה"),
  tags: text("tags"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
