import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const customersTable = pgTable("customers", {
  id: serial("id").primaryKey(),
  customerNumber: text("customer_number").notNull().unique(),
  customerName: text("customer_name").notNull(),
  contactPerson: text("contact_person"),
  phone: text("phone"),
  mobile: text("mobile"),
  fax: text("fax"),
  email: text("email"),
  website: text("website"),
  linkedin: text("linkedin"),
  facebook: text("facebook"),
  address: text("address"),
  city: text("city"),
  region: text("region"),
  postalCode: text("postal_code"),
  country: text("country").default("Israel"),
  billingAddress: text("billing_address"),
  shippingAddress: text("shipping_address"),
  taxId: text("tax_id"),
  vatNumber: text("vat_number"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }).default("0"),
  creditTermsDays: integer("credit_terms_days").default(30),
  currency: text("currency").default("ILS"),
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  paymentMethod: text("payment_method"),
  paymentTerms: text("payment_terms").default("שוטף 30"),
  vatExempt: boolean("vat_exempt").default(false),
  withholdingTaxRate: numeric("withholding_tax_rate", { precision: 5, scale: 2 }).default("0"),
  bankName: text("bank_name"),
  bankBranch: text("bank_branch"),
  bankAccount: text("bank_account"),
  customerCategory: text("customer_category").default("B"),
  customerType: text("customer_type").default("business"),
  industry: text("industry"),
  category: text("category").default("רגיל"),
  source: text("source"),
  companySize: text("company_size"),
  annualRevenue: numeric("annual_revenue", { precision: 15, scale: 2 }),
  secondaryContact: text("secondary_contact"),
  secondaryPhone: text("secondary_phone"),
  secondaryEmail: text("secondary_email"),
  languagePref: text("language_pref").default("he"),
  communicationPref: text("communication_pref").default("email"),
  preferredDelivery: text("preferred_delivery"),
  salespersonId: integer("salesperson_id"),
  assignedRep: text("assigned_rep"),
  priceListId: integer("price_list_id"),
  acquisitionSource: text("acquisition_source"),
  customerSince: date("customer_since"),
  lastPurchaseDate: date("last_purchase_date"),
  lifetimeValue: numeric("lifetime_value", { precision: 15, scale: 2 }).default("0"),
  loyaltyTier: text("loyalty_tier").default("bronze"),
  billingAddressJson: text("billing_address_json"),
  shippingAddressJson: text("shipping_address_json"),
  status: text("status").notNull().default("active"),
  blockedReason: text("blocked_reason"),
  blockedDate: date("blocked_date"),
  customPricingTier: text("custom_pricing_tier"),
  specialDiscountPct: numeric("special_discount_pct", { precision: 5, scale: 2 }).default("0"),
  glAccountCode: text("gl_account_code"),
  notes: text("notes"),
  internalNotes: text("internal_notes"),
  attachmentsJson: text("attachments_json"),
  tags: text("tags"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});
