import { pgTable, serial, text, integer, boolean, timestamp, jsonb, varchar, numeric } from "drizzle-orm/pg-core";
import { suppliersTable } from "./suppliers";

export const ediTradingPartnersTable = pgTable("edi_trading_partners", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  supplierId: integer("supplier_id").references(() => suppliersTable.id),
  ediId: varchar("edi_id", { length: 100 }),
  ediQualifier: varchar("edi_qualifier", { length: 10 }).default("01"),
  protocol: varchar("protocol", { length: 20 }).notNull().default("webhook"),
  webhookUrl: text("webhook_url"),
  webhookSecret: text("webhook_secret"),
  sftpHost: text("sftp_host"),
  sftpPort: integer("sftp_port").default(22),
  sftpUsername: text("sftp_username"),
  sftpPassword: text("sftp_password"),
  sftpInboundPath: text("sftp_inbound_path").default("/inbound"),
  sftpOutboundPath: text("sftp_outbound_path").default("/outbound"),
  as2Url: text("as2_url"),
  as2FromId: text("as2_from_id"),
  as2ToId: text("as2_to_id"),
  apiKey: text("api_key"),
  ediFormat: varchar("edi_format", { length: 20 }).notNull().default("X12"),
  supportedDocTypes: jsonb("supported_doc_types").default([]),
  isActive: boolean("is_active").notNull().default(true),
  testMode: boolean("test_mode").notNull().default(false),
  notes: text("notes"),
  lastContactAt: timestamp("last_contact_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const ediDocumentMappingsTable = pgTable("edi_document_mappings", {
  id: serial("id").primaryKey(),
  tradingPartnerId: integer("trading_partner_id").references(() => ediTradingPartnersTable.id),
  docType: varchar("doc_type", { length: 20 }).notNull(),
  docTypeName: varchar("doc_type_name", { length: 100 }),
  ediFormat: varchar("edi_format", { length: 20 }).notNull().default("X12"),
  direction: varchar("direction", { length: 10 }).notNull().default("outbound"),
  mappingConfig: jsonb("mapping_config").default({}),
  transformationRules: jsonb("transformation_rules").default([]),
  validationRules: jsonb("validation_rules").default([]),
  isActive: boolean("is_active").notNull().default(true),
  isDefault: boolean("is_default").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const ediTransactionLogsTable = pgTable("edi_transaction_logs", {
  id: serial("id").primaryKey(),
  tradingPartnerId: integer("trading_partner_id").references(() => ediTradingPartnersTable.id),
  docType: varchar("doc_type", { length: 20 }).notNull(),
  docTypeName: varchar("doc_type_name", { length: 100 }),
  direction: varchar("direction", { length: 10 }).notNull(),
  status: varchar("status", { length: 30 }).notNull().default("pending"),
  controlNumber: varchar("control_number", { length: 50 }),
  referenceType: varchar("reference_type", { length: 50 }),
  referenceId: integer("reference_id"),
  referenceNumber: varchar("reference_number", { length: 100 }),
  rawContent: text("raw_content"),
  parsedData: jsonb("parsed_data"),
  errorMessage: text("error_message"),
  retryCount: integer("retry_count").notNull().default(0),
  maxRetries: integer("max_retries").notNull().default(3),
  sentAt: timestamp("sent_at"),
  receivedAt: timestamp("received_at"),
  acknowledgedAt: timestamp("acknowledged_at"),
  processedAt: timestamp("processed_at"),
  createdRecordType: varchar("created_record_type", { length: 50 }),
  createdRecordId: integer("created_record_id"),
  fileSizeBytes: integer("file_size_bytes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const ediAcknowledgmentsTable = pgTable("edi_acknowledgments", {
  id: serial("id").primaryKey(),
  transactionLogId: integer("transaction_log_id").references(() => ediTransactionLogsTable.id),
  tradingPartnerId: integer("trading_partner_id").references(() => ediTradingPartnersTable.id),
  ackType: varchar("ack_type", { length: 20 }).notNull().default("997"),
  status: varchar("status", { length: 30 }).notNull().default("pending"),
  controlNumber: varchar("control_number", { length: 50 }),
  acceptedSets: integer("accepted_sets").default(0),
  rejectedSets: integer("rejected_sets").default(0),
  errorSegments: jsonb("error_segments").default([]),
  rawContent: text("raw_content"),
  receivedAt: timestamp("received_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
