import { pgTable, serial, text, numeric, timestamp, integer, boolean, varchar } from "drizzle-orm/pg-core";

export const fabricationProfilesTable = pgTable("fabrication_profiles", {
  id: serial("id").primaryKey(),
  profileNumber: text("profile_number").notNull().unique(),
  profileName: text("profile_name").notNull(),
  series: text("series"),
  systemType: text("system_type").default("aluminum"),
  profileType: text("profile_type").default("frame"),
  material: text("material").default("aluminum"),
  alloy: text("alloy"),
  temper: text("temper"),
  weightPerMeter: numeric("weight_per_meter"),
  lengthMm: numeric("length_mm").default("6000"),
  widthMm: numeric("width_mm"),
  heightMm: numeric("height_mm"),
  wallThicknessMm: numeric("wall_thickness_mm"),
  momentOfInertiaX: numeric("moment_of_inertia_x"),
  momentOfInertiaY: numeric("moment_of_inertia_y"),
  crossSectionArea: numeric("cross_section_area"),
  thermalBreak: boolean("thermal_break").default(false),
  thermalBreakWidthMm: numeric("thermal_break_width_mm"),
  gasketSlots: integer("gasket_slots").default(0),
  glazingPocketMm: numeric("glazing_pocket_mm"),
  maxSpanMm: numeric("max_span_mm"),
  surfaceTreatment: text("surface_treatment"),
  defaultFinish: text("default_finish").default("anodized"),
  defaultColor: text("default_color"),
  compatibleSystems: text("compatible_systems"),
  drawingUrl: text("drawing_url"),
  imageUrl: text("image_url"),
  supplierId: integer("supplier_id"),
  supplierPartNumber: text("supplier_part_number"),
  costPerMeter: numeric("cost_per_meter"),
  currentStockMeters: numeric("current_stock_meters").default("0"),
  minimumStockMeters: numeric("minimum_stock_meters"),
  reorderPointMeters: numeric("reorder_point_meters"),
  warehouseLocation: text("warehouse_location"),
  siStandard: text("si_standard"),
  isoStandard: text("iso_standard"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const fabricationSystemsTable = pgTable("fabrication_systems", {
  id: serial("id").primaryKey(),
  systemNumber: text("system_number").notNull().unique(),
  systemName: text("system_name").notNull(),
  systemType: text("system_type").notNull().default("window"),
  manufacturer: text("manufacturer"),
  series: text("series"),
  material: text("material").default("aluminum"),
  description: text("description"),
  maxWidthMm: numeric("max_width_mm"),
  maxHeightMm: numeric("max_height_mm"),
  maxWeightKg: numeric("max_weight_kg"),
  minGlassThicknessMm: numeric("min_glass_thickness_mm"),
  maxGlassThicknessMm: numeric("max_glass_thickness_mm"),
  thermalBreak: boolean("thermal_break").default(false),
  uValueFrame: numeric("u_value_frame"),
  uValueSystem: numeric("u_value_system"),
  acousticRating: varchar("acoustic_rating", { length: 30 }),
  fireRating: varchar("fire_rating", { length: 30 }),
  windResistanceClass: varchar("wind_resistance_class", { length: 20 }),
  waterTightnessClass: varchar("water_tightness_class", { length: 20 }),
  airPermeabilityClass: varchar("air_permeability_class", { length: 20 }),
  securityClass: varchar("security_class", { length: 20 }),
  openingTypes: text("opening_types"),
  profileIds: text("profile_ids"),
  defaultHardwareSet: text("default_hardware_set"),
  defaultSealType: text("default_seal_type"),
  defaultGasketType: text("default_gasket_type"),
  installationMethod: text("installation_method"),
  certifications: text("certifications"),
  drawingUrl: text("drawing_url"),
  catalogUrl: text("catalog_url"),
  imageUrl: text("image_url"),
  costPerSqm: numeric("cost_per_sqm"),
  laborHoursPerSqm: numeric("labor_hours_per_sqm"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const glassCatalogTable = pgTable("glass_catalog", {
  id: serial("id").primaryKey(),
  glassCode: text("glass_code").notNull().unique(),
  glassName: text("glass_name").notNull(),
  glassType: text("glass_type").notNull().default("float"),
  composition: text("composition"),
  thicknessMm: numeric("thickness_mm").notNull(),
  isLaminated: boolean("is_laminated").default(false),
  laminatedLayers: text("laminated_layers"),
  isInsulated: boolean("is_insulated").default(false),
  insulatedConfig: text("insulated_config"),
  spacerWidthMm: numeric("spacer_width_mm"),
  gasFill: text("gas_fill"),
  isTempered: boolean("is_tempered").default(false),
  isHeatStrengthened: boolean("is_heat_strengthened").default(false),
  coating: text("coating"),
  coatingPosition: text("coating_position"),
  tintColor: text("tint_color"),
  uValue: numeric("u_value"),
  shgc: numeric("shgc"),
  lightTransmission: numeric("light_transmission"),
  soundReduction: numeric("sound_reduction"),
  maxWidthMm: numeric("max_width_mm"),
  maxHeightMm: numeric("max_height_mm"),
  maxAreaSqm: numeric("max_area_sqm"),
  weightPerSqm: numeric("weight_per_sqm"),
  breakagePattern: text("breakage_pattern"),
  safetyClass: text("safety_class"),
  fireRating: text("fire_rating"),
  siStandard: text("si_standard"),
  isoStandard: text("iso_standard"),
  supplierId: integer("supplier_id"),
  pricePerSqm: numeric("price_per_sqm"),
  leadTimeDays: integer("lead_time_days"),
  currentStockSqm: numeric("current_stock_sqm").default("0"),
  minimumStockSqm: numeric("minimum_stock_sqm"),
  warehouseLocation: text("warehouse_location"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const finishesTable = pgTable("finishes", {
  id: serial("id").primaryKey(),
  finishCode: text("finish_code").notNull().unique(),
  finishName: text("finish_name").notNull(),
  finishType: text("finish_type").notNull().default("powder_coating"),
  applicableMaterials: text("applicable_materials"),
  thicknessMicrons: numeric("thickness_microns"),
  minCoats: integer("min_coats").default(1),
  cureTemperatureC: numeric("cure_temperature_c"),
  cureTimeMinutes: integer("cure_time_minutes"),
  durabilityClass: text("durability_class"),
  weatherResistance: text("weather_resistance"),
  corrosionResistance: text("corrosion_resistance"),
  warranty_years: integer("warranty_years"),
  qualicoatClass: text("qualicoat_class"),
  qualidecoCertified: boolean("qualideco_certified").default(false),
  supplierId: integer("supplier_id"),
  costPerSqm: numeric("cost_per_sqm"),
  leadTimeDays: integer("lead_time_days"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const colorsTable = pgTable("colors", {
  id: serial("id").primaryKey(),
  colorCode: text("color_code").notNull().unique(),
  colorName: text("color_name").notNull(),
  colorNameHe: text("color_name_he"),
  colorSystem: text("color_system").notNull().default("RAL"),
  ralNumber: text("ral_number"),
  hexValue: text("hex_value"),
  colorFamily: text("color_family"),
  isMetallic: boolean("is_metallic").default(false),
  isWoodGrain: boolean("is_wood_grain").default(false),
  textureType: text("texture_type"),
  applicableFinishes: text("applicable_finishes"),
  surchargePercent: numeric("surcharge_percent").default("0"),
  popularityRank: integer("popularity_rank"),
  imageUrl: text("image_url"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const accessoriesHardwareTable = pgTable("accessories_hardware", {
  id: serial("id").primaryKey(),
  partNumber: text("part_number").notNull().unique(),
  partName: text("part_name").notNull(),
  partNameHe: text("part_name_he"),
  category: text("category").notNull().default("handle"),
  subCategory: text("sub_category"),
  material: text("material"),
  finish: text("finish"),
  color: text("color"),
  brand: text("brand"),
  model: text("model"),
  compatibleSystems: text("compatible_systems"),
  compatibleProfiles: text("compatible_profiles"),
  dimensionsMm: text("dimensions_mm"),
  weightGrams: numeric("weight_grams"),
  loadCapacityKg: numeric("load_capacity_kg"),
  operationCycles: integer("operation_cycles"),
  securityLevel: text("security_level"),
  fireRated: boolean("fire_rated").default(false),
  antiCorrosion: boolean("anti_corrosion").default(false),
  childSafe: boolean("child_safe").default(false),
  supplierId: integer("supplier_id"),
  costPerUnit: numeric("cost_per_unit"),
  sellingPrice: numeric("selling_price"),
  currentStock: numeric("current_stock").default("0"),
  minimumStock: numeric("minimum_stock"),
  reorderPoint: numeric("reorder_point"),
  warehouseLocation: text("warehouse_location"),
  imageUrl: text("image_url"),
  drawingUrl: text("drawing_url"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const unitConversionsTable = pgTable("unit_conversions", {
  id: serial("id").primaryKey(),
  fromUnit: text("from_unit").notNull(),
  toUnit: text("to_unit").notNull(),
  conversionFactor: numeric("conversion_factor").notNull(),
  materialCategory: text("material_category"),
  description: text("description"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
