import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const importOrdersTable = pgTable("import_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  supplierId: integer("supplier_id"),
  supplierName: text("supplier_name"),
  countryOfOrigin: text("country_of_origin"),
  incoterms: text("incoterms").default("FOB"),
  currency: text("currency").default("USD"),
  exchangeRate: numeric("exchange_rate", { precision: 10, scale: 4 }).default("1"),
  totalValue: numeric("total_value", { precision: 15, scale: 2 }).default("0"),
  totalValueIls: numeric("total_value_ils", { precision: 15, scale: 2 }).default("0"),
  customsDutyPct: numeric("customs_duty_pct", { precision: 5, scale: 2 }).default("0"),
  estimatedCustomsDuty: numeric("estimated_customs_duty", { precision: 15, scale: 2 }).default("0"),
  customsClassification: text("customs_classification"),
  shippingMethod: text("shipping_method").default("sea"),
  containerType: text("container_type"),
  containerCount: integer("container_count").default(1),
  portOfOrigin: text("port_of_origin"),
  portOfDestination: text("port_of_destination").default("חיפה"),
  estimatedDeparture: date("estimated_departure"),
  estimatedArrival: date("estimated_arrival"),
  actualArrival: date("actual_arrival"),
  insuranceCompany: text("insurance_company"),
  insurancePolicyNumber: text("insurance_policy_number"),
  insuranceValue: numeric("insurance_value", { precision: 15, scale: 2 }).default("0"),
  lcNumber: text("lc_number"),
  lcBank: text("lc_bank"),
  lcAmount: numeric("lc_amount", { precision: 15, scale: 2 }).default("0"),
  lcExpiryDate: date("lc_expiry_date"),
  freightCost: numeric("freight_cost", { precision: 15, scale: 2 }).default("0"),
  handlingCost: numeric("handling_cost", { precision: 15, scale: 2 }).default("0"),
  otherCosts: numeric("other_costs", { precision: 15, scale: 2 }).default("0"),
  totalLandedCost: numeric("total_landed_cost", { precision: 15, scale: 2 }).default("0"),
  customsBroker: text("customs_broker"),
  forwardingAgent: text("forwarding_agent"),
  contactPerson: text("contact_person"),
  contactPhone: text("contact_phone"),
  contactEmail: text("contact_email"),
  notes: text("notes"),
  status: text("status").notNull().default("טיוטה"),
  priority: text("priority").default("רגילה"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const importOrderItemsTable = pgTable("import_order_items", {
  id: serial("id").primaryKey(),
  importOrderId: integer("import_order_id").notNull(),
  itemName: text("item_name").notNull(),
  itemCode: text("item_code"),
  hsCode: text("hs_code"),
  description: text("description"),
  quantity: numeric("quantity", { precision: 15, scale: 2 }).notNull().default("1"),
  unit: text("unit").default("יח"),
  unitPrice: numeric("unit_price", { precision: 15, scale: 2 }).notNull().default("0"),
  totalPrice: numeric("total_price", { precision: 15, scale: 2 }).default("0"),
  customsDutyPct: numeric("customs_duty_pct", { precision: 5, scale: 2 }).default("0"),
  customsDutyAmount: numeric("customs_duty_amount", { precision: 15, scale: 2 }).default("0"),
  weightKg: numeric("weight_kg", { precision: 10, scale: 2 }),
  volumeCbm: numeric("volume_cbm", { precision: 10, scale: 4 }),
  countryOfOrigin: text("country_of_origin"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
