import { pgTable, serial, text, numeric, timestamp, integer, boolean, date } from "drizzle-orm/pg-core";

export const journalEntriesTable = pgTable("journal_entries", {
  id: serial("id").primaryKey(),
  entryNumber: text("entry_number").notNull(),
  entryDate: date("entry_date").notNull(),
  description: text("description").notNull(),
  reference: text("reference"),
  entryType: text("entry_type").default("standard"),
  debitAccountId: integer("debit_account_id"),
  debitAccountName: text("debit_account_name"),
  creditAccountId: integer("credit_account_id"),
  creditAccountName: text("credit_account_name"),
  amount: numeric("amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  exchangeRate: numeric("exchange_rate", { precision: 12, scale: 6 }).default("1"),
  amountIls: numeric("amount_ils", { precision: 15, scale: 2 }).default("0"),
  totalDebit: numeric("total_debit", { precision: 15, scale: 2 }).default("0"),
  totalCredit: numeric("total_credit", { precision: 15, scale: 2 }).default("0"),
  isBalanced: boolean("is_balanced").default(true),
  linesCount: integer("lines_count").default(0),
  status: text("status").default("draft"),
  sourceDocument: text("source_document"),
  sourceType: text("source_type"),
  notes: text("notes"),
  createdBy: integer("created_by"),
  createdByName: text("created_by_name"),
  approvedBy: integer("approved_by"),
  approvedByName: text("approved_by_name"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  postedAt: timestamp("posted_at", { withTimezone: true }),
  reversedAt: timestamp("reversed_at", { withTimezone: true }),
  fiscalYear: integer("fiscal_year"),
  fiscalPeriod: integer("fiscal_period"),
  tags: text("tags"),
  isRecurring: boolean("is_recurring").default(false),
  recurringFrequency: text("recurring_frequency"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectName: text("project_name"),
  journalType: text("journal_type").default("general"),
  taxCode: text("tax_code"),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }).default("0"),
  reconciled: boolean("reconciled").default(false),
  reconciledDate: date("reconciled_date"),
  reconciledBy: text("reconciled_by"),
  reversed: boolean("reversed").default(false),
  reversalDate: date("reversal_date"),
  sourceId: integer("source_id"),
  posted: boolean("posted").default(false),
  postedBy: text("posted_by"),
  baseAmount: numeric("base_amount", { precision: 15, scale: 2 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const journalEntryLinesTable = pgTable("journal_entry_lines", {
  id: serial("id").primaryKey(),
  journalEntryId: integer("journal_entry_id").notNull(),
  lineNumber: integer("line_number").default(1),
  accountNumber: text("account_number"),
  accountName: text("account_name"),
  accountId: integer("account_id"),
  debitAmount: numeric("debit_amount", { precision: 15, scale: 2 }).default("0"),
  creditAmount: numeric("credit_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("ILS"),
  exchangeRate: numeric("exchange_rate", { precision: 12, scale: 6 }).default("1"),
  debitAmountIls: numeric("debit_amount_ils", { precision: 15, scale: 2 }).default("0"),
  creditAmountIls: numeric("credit_amount_ils", { precision: 15, scale: 2 }).default("0"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectName: text("project_name"),
  taxCode: text("tax_code"),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }).default("0"),
  description: text("description"),
  reference: text("reference"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
