import { pgTable, serial, text, integer, boolean, timestamp, date, numeric, jsonb } from "drizzle-orm/pg-core";

export const leadsTable = pgTable("leads", {
  id: serial("id").primaryKey(),
  leadNumber: text("lead_number").unique(),
  source: text("source").default("other"),
  status: text("status").default("new"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  companyName: text("company_name"),
  email: text("email"),
  phone: text("phone"),
  mobile: text("mobile"),
  addressCity: text("address_city"),
  productInterest: jsonb("product_interest").default([]),
  estimatedValue: numeric("estimated_value").default("0"),
  estimatedCloseDate: date("estimated_close_date"),
  leadScore: numeric("lead_score").default("0"),
  assignedTo: text("assigned_to"),
  nextFollowUp: timestamp("next_follow_up"),
  followUpCount: integer("follow_up_count").default(0),
  lostReason: text("lost_reason"),
  convertedCustomerId: integer("converted_customer_id"),
  tags: jsonb("tags").default([]),
  notes: text("notes"),
  isActive: boolean("is_active").default(true),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
