import { pgTable, serial, text, integer, boolean, timestamp, numeric, date, jsonb } from "drizzle-orm/pg-core";

export const priceListsTable = pgTable("price_lists_ent", {
  id: serial("id").primaryKey(),
  listNumber: text("list_number").notNull(),
  listName: text("list_name").notNull(),
  listType: text("list_type").default("general"),
  customerCategory: text("customer_category"),
  currency: text("currency").default("ILS"),
  validFrom: date("valid_from"),
  validTo: date("valid_to"),
  discountPercent: numeric("discount_percent").default("0"),
  itemsJson: jsonb("items_json").default([]),
  totalProducts: integer("total_products").default(0),
  status: text("status").default("draft"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const costCalculationsTable = pgTable("cost_calculations", {
  id: serial("id").primaryKey(),
  calculationNumber: text("calculation_number").notNull(),
  productName: text("product_name").notNull(),
  productCode: text("product_code"),
  category: text("category"),
  materialsCost: numeric("materials_cost").default("0"),
  laborCost: numeric("labor_cost").default("0"),
  overheadCost: numeric("overhead_cost").default("0"),
  packagingCost: numeric("packaging_cost").default("0"),
  shippingCost: numeric("shipping_cost").default("0"),
  customsCost: numeric("customs_cost").default("0"),
  otherCosts: numeric("other_costs").default("0"),
  totalCost: numeric("total_cost").default("0"),
  marginPercent: numeric("margin_percent").default("0"),
  sellingPrice: numeric("selling_price").default("0"),
  profit: numeric("profit").default("0"),
  breakdownJson: jsonb("breakdown_json").default([]),
  currency: text("currency").default("ILS"),
  status: text("status").default("draft"),
  calculatedBy: text("calculated_by"),
  approvedBy: text("approved_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const collectionManagementTable = pgTable("collection_management", {
  id: serial("id").primaryKey(),
  collectionNumber: text("collection_number").notNull(),
  customerName: text("customer_name").notNull(),
  customerId: text("customer_id"),
  invoiceNumber: text("invoice_number"),
  invoiceDate: date("invoice_date"),
  dueDate: date("due_date"),
  originalAmount: numeric("original_amount").default("0"),
  paidAmount: numeric("paid_amount").default("0"),
  balanceDue: numeric("balance_due").default("0"),
  daysOverdue: integer("days_overdue").default(0),
  riskLevel: text("risk_level").default("low"),
  status: text("status").default("open"),
  collector: text("collector"),
  phone: text("phone"),
  email: text("email"),
  lastContactDate: date("last_contact_date"),
  nextAction: text("next_action"),
  nextActionDate: date("next_action_date"),
  paymentPlan: text("payment_plan"),
  dunningLettersSent: integer("dunning_letters_sent").default(0),
  escalationLevel: integer("escalation_level").default(0),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
