import { pgTable, serial, text, numeric, integer, date, timestamp, boolean, varchar } from "drizzle-orm/pg-core";

export const productionWorkOrdersTable = pgTable("production_work_orders", {
  id: serial("id").primaryKey(),
  orderNumber: text("order_number").notNull().unique(),
  productName: text("product_name").notNull(),
  bomId: integer("bom_id"),
  plannedStart: date("planned_start"),
  plannedEnd: date("planned_end"),
  actualStart: date("actual_start"),
  actualEnd: date("actual_end"),
  quantityPlanned: numeric("quantity_planned").notNull().default("0"),
  quantityProduced: numeric("quantity_produced").default("0"),
  status: text("status").notNull().default("planned"),
  assignedTo: text("assigned_to"),
  priority: text("priority").notNull().default("medium"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  salesOrderId: integer("sales_order_id"),
  customerName: text("customer_name"),
  productionLine: text("production_line"),
  machineId: integer("machine_id"),
  unitCost: numeric("unit_cost").default("0"),
  totalCost: numeric("total_cost").default("0"),
  scrapQuantity: numeric("scrap_quantity").default("0"),
  rejectQuantity: numeric("reject_quantity").default("0"),
  laborHours: numeric("labor_hours").default("0"),
  setupHours: numeric("setup_hours").default("0"),
  machineHours: numeric("machine_hours").default("0"),
  efficiencyRate: numeric("efficiency_rate"),
  yieldRate: numeric("yield_rate"),
  qualityStatus: text("quality_status").default("pending"),
  qualityNotes: text("quality_notes"),
  workInstructions: text("work_instructions"),
  department: text("department"),
  costCenter: text("cost_center"),
  createdBy: text("created_by"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  materialCost: numeric("material_cost").default("0"),
  laborCost: numeric("labor_cost").default("0"),
  overheadCost: numeric("overhead_cost").default("0"),
  batchNumber: text("batch_number"),
  lotNumber: text("lot_number"),
  routingId: integer("routing_id"),
  shift: text("shift"),
  downtimeMinutes: integer("downtime_minutes").default(0),
  reworkQuantity: numeric("rework_quantity").default("0"),
  workOrderType: varchar("work_order_type", { length: 30 }).default("standard"),
  customerId: integer("customer_id"),
  deliveryDate: date("delivery_date"),
  completionPercentage: numeric("completion_percentage").default("0"),
  parentWorkOrderId: integer("parent_work_order_id"),
  isRework: boolean("is_rework").default(false),
  reworkReason: text("rework_reason"),
  originalWorkOrderId: integer("original_work_order_id"),
  toolingRequired: text("tooling_required"),
  specialInstructions: text("special_instructions"),
  safetyRequirements: text("safety_requirements"),
  rawMaterialStatus: varchar("raw_material_status", { length: 30 }).default("pending"),
  cuttingStatus: varchar("cutting_status", { length: 30 }).default("pending"),
  weldingStatus: varchar("welding_status", { length: 30 }).default("pending"),
  assemblyStatus: varchar("assembly_status", { length: 30 }).default("pending"),
  paintingStatus: varchar("painting_status", { length: 30 }).default("pending"),
  glassStatus: varchar("glass_status", { length: 30 }).default("pending"),
  packagingStatus: varchar("packaging_status", { length: 30 }).default("pending"),
  inspectionStatus: varchar("inspection_status", { length: 30 }).default("pending"),
  energyConsumptionKwh: numeric("energy_consumption_kwh").default("0"),
  wasteMaterialKg: numeric("waste_material_kg").default("0"),
  recycledMaterialKg: numeric("recycled_material_kg").default("0"),
  ambientTemperature: numeric("ambient_temperature"),
  humidityPercent: numeric("humidity_percent"),
  operatorCount: integer("operator_count").default(1),
  overtimeHours: numeric("overtime_hours").default("0"),
  actualUnitCost: numeric("actual_unit_cost"),
  varianceCost: numeric("variance_cost").default("0"),
  deletedAt: timestamp("deleted_at"),
});
