import { pgTable, serial, text, numeric, timestamp, integer, date } from "drizzle-orm/pg-core";

export const projectsTable = pgTable("projects", {
  id: serial("id").primaryKey(),
  projectCode: text("project_code"),
  name: text("name").notNull(),
  projectType: text("project_type"),
  description: text("description"),
  client: text("client"),
  customerId: integer("customer_id"),
  siteAddress: text("site_address"),
  projectManagerId: integer("project_manager_id"),
  status: text("status").notNull().default("planning"),
  phase: text("phase"),
  startDate: date("start_date"),
  plannedStartDate: date("planned_start_date"),
  plannedEndDate: date("planned_end_date"),
  endDate: date("end_date"),
  owner: text("owner"),
  budget: numeric("budget", { precision: 15, scale: 2 }).default("0"),
  budgetPlanned: numeric("budget_planned", { precision: 15, scale: 2 }),
  budgetActual: numeric("budget_actual", { precision: 15, scale: 2 }),
  spent: numeric("spent", { precision: 15, scale: 2 }).default("0"),
  completionPct: numeric("completion_pct", { precision: 5, scale: 2 }).default("0"),
  priority: text("priority").default("medium"),
  tags: text("tags"),
  contractValue: numeric("contract_value", { precision: 15, scale: 2 }),
  warrantyPeriodMonths: integer("warranty_period_months"),
  milestoneJson: text("milestone_json"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});
