import { pgTable, serial, text, numeric, timestamp, integer, boolean, jsonb, date } from "drizzle-orm/pg-core";

// ==================== PACKING & SHIPPING ====================

export const packingListsV2Table = pgTable("packing_lists_v2", {
  id: serial("id").primaryKey(),
  packingNumber: text("packing_number").notNull().unique(),
  deliveryId: integer("delivery_id"),
  orderId: integer("order_id"),
  customerName: text("customer_name"),
  deliveryAddress: text("delivery_address"),
  containerType: text("container_type").default("20GP"),
  containerDimensionsL: numeric("container_dimensions_l", { precision: 10, scale: 2 }).default("590"),
  containerDimensionsW: numeric("container_dimensions_w", { precision: 10, scale: 2 }).default("235"),
  containerDimensionsH: numeric("container_dimensions_h", { precision: 10, scale: 2 }).default("239"),
  items: jsonb("items").default("[]"),
  totalWeight: numeric("total_weight", { precision: 12, scale: 2 }).default("0"),
  totalVolume: numeric("total_volume", { precision: 12, scale: 4 }).default("0"),
  utilizationPct: numeric("utilization_pct", { precision: 5, scale: 2 }).default("0"),
  status: text("status").default("draft"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const shippingLabelsTable = pgTable("shipping_labels", {
  id: serial("id").primaryKey(),
  packingListId: integer("packing_list_id"),
  carrier: text("carrier"),
  barcode: text("barcode"),
  trackingNumber: text("tracking_number"),
  labelData: jsonb("label_data").default("{}"),
  shipper: text("shipper"),
  consignee: text("consignee"),
  shipToAddress: text("ship_to_address"),
  weight: numeric("weight", { precision: 10, scale: 2 }),
  dimensions: text("dimensions"),
  serviceType: text("service_type"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const containerLoadPlansTable = pgTable("container_load_plans", {
  id: serial("id").primaryKey(),
  packingListId: integer("packing_list_id"),
  placementMap: jsonb("placement_map").default("[]"),
  containerType: text("container_type"),
  utilizationPct: numeric("utilization_pct", { precision: 5, scale: 2 }),
  totalItems: integer("total_items").default(0),
  algorithm: text("algorithm").default("first-fit-decreasing"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ==================== CARRIER RATES & FREIGHT COST ====================

export const carriersTable = pgTable("carriers", {
  id: serial("id").primaryKey(),
  carrierCode: text("carrier_code").notNull().unique(),
  carrierName: text("carrier_name").notNull(),
  carrierType: text("carrier_type").default("sea"),
  country: text("country"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  isActive: boolean("is_active").default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const carrierRatesTable = pgTable("carrier_rates", {
  id: serial("id").primaryKey(),
  carrierId: integer("carrier_id"),
  rateType: text("rate_type").default("weight"),
  originZone: text("origin_zone"),
  destinationZone: text("destination_zone"),
  weightBrackets: jsonb("weight_brackets").default("[]"),
  volumeBrackets: jsonb("volume_brackets").default("[]"),
  distanceZones: jsonb("distance_zones").default("[]"),
  baseRate: numeric("base_rate", { precision: 12, scale: 4 }).default("0"),
  currency: text("currency").default("USD"),
  fuelSurcharge: numeric("fuel_surcharge", { precision: 5, scale: 2 }).default("0"),
  handlingFee: numeric("handling_fee", { precision: 10, scale: 2 }).default("0"),
  minimumCharge: numeric("minimum_charge", { precision: 10, scale: 2 }).default("0"),
  effectiveDate: date("effective_date"),
  expiryDate: date("expiry_date"),
  isActive: boolean("is_active").default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const carrierScorecardsTable = pgTable("carrier_scorecards", {
  id: serial("id").primaryKey(),
  carrierId: integer("carrier_id"),
  periodYear: integer("period_year"),
  periodQuarter: integer("period_quarter"),
  onTimePct: numeric("on_time_pct", { precision: 5, scale: 2 }).default("0"),
  damageRate: numeric("damage_rate", { precision: 5, scale: 2 }).default("0"),
  avgCostPerKg: numeric("avg_cost_per_kg", { precision: 10, scale: 4 }).default("0"),
  claimsCount: integer("claims_count").default(0),
  shipmentsCount: integer("shipments_count").default(0),
  avgTransitDays: numeric("avg_transit_days", { precision: 5, scale: 1 }).default("0"),
  overallScore: numeric("overall_score", { precision: 5, scale: 2 }).default("0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const freightCalculationsTable = pgTable("freight_calculations", {
  id: serial("id").primaryKey(),
  shipmentId: integer("shipment_id"),
  shipmentRef: text("shipment_ref"),
  carrierId: integer("carrier_id"),
  carrierName: text("carrier_name"),
  weightKg: numeric("weight_kg", { precision: 12, scale: 2 }).default("0"),
  volumeCbm: numeric("volume_cbm", { precision: 12, scale: 4 }).default("0"),
  distanceKm: numeric("distance_km", { precision: 10, scale: 2 }),
  originZone: text("origin_zone"),
  destinationZone: text("destination_zone"),
  baseRate: numeric("base_rate", { precision: 12, scale: 4 }).default("0"),
  fuelSurcharge: numeric("fuel_surcharge", { precision: 10, scale: 2 }).default("0"),
  handlingFee: numeric("handling_fee", { precision: 10, scale: 2 }).default("0"),
  calculatedCost: numeric("calculated_cost", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("USD"),
  isSelected: boolean("is_selected").default(false),
  comparisonGroupId: text("comparison_group_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== CUSTOMS DOCUMENTATION ====================

export const customsDocumentsTable = pgTable("customs_documents", {
  id: serial("id").primaryKey(),
  docNumber: text("doc_number").notNull().unique(),
  shipmentId: integer("shipment_id"),
  shipmentRef: text("shipment_ref"),
  docType: text("doc_type").default("commercial_invoice"),
  exporterName: text("exporter_name"),
  exporterAddress: text("exporter_address"),
  exporterTaxId: text("exporter_tax_id"),
  importerName: text("importer_name"),
  importerAddress: text("importer_address"),
  countryOfOrigin: text("country_of_origin").default("Israel"),
  countryOfDestination: text("country_of_destination"),
  incoterms: text("incoterms").default("FOB"),
  portOfLoading: text("port_of_loading"),
  portOfDischarge: text("port_of_discharge"),
  commercialInvoiceData: jsonb("commercial_invoice_data").default("{}"),
  packingListData: jsonb("packing_list_data").default("{}"),
  certificateOfOriginData: jsonb("certificate_of_origin_data").default("{}"),
  hsCodes: jsonb("hs_codes").default("[]"),
  customsValue: numeric("customs_value", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("USD"),
  totalWeight: numeric("total_weight", { precision: 12, scale: 2 }).default("0"),
  totalPackages: integer("total_packages").default(0),
  declarationText: text("declaration_text"),
  status: text("status").default("draft"),
  issuedDate: date("issued_date"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ==================== FREIGHT AUDIT ====================

export const freightAuditTable = pgTable("freight_audit", {
  id: serial("id").primaryKey(),
  auditNumber: text("audit_number").notNull().unique(),
  carrierInvoiceId: text("carrier_invoice_id"),
  carrierId: integer("carrier_id"),
  carrierName: text("carrier_name"),
  shipmentRef: text("shipment_ref"),
  shipmentId: integer("shipment_id"),
  invoiceDate: date("invoice_date"),
  invoiceAmount: numeric("invoice_amount", { precision: 15, scale: 2 }).default("0"),
  expectedAmount: numeric("expected_amount", { precision: 15, scale: 2 }).default("0"),
  discrepancyAmount: numeric("discrepancy_amount", { precision: 15, scale: 2 }).default("0"),
  discrepancyPct: numeric("discrepancy_pct", { precision: 6, scale: 2 }).default("0"),
  currency: text("currency").default("USD"),
  discrepancyThreshold: numeric("discrepancy_threshold", { precision: 5, scale: 2 }).default("5"),
  isFlagged: boolean("is_flagged").default(false),
  disputeStatus: text("dispute_status").default("none"),
  disputeOpenedAt: timestamp("dispute_opened_at"),
  disputeResolvedAt: timestamp("dispute_resolved_at"),
  resolutionNotes: text("resolution_notes"),
  savingsRealized: numeric("savings_realized", { precision: 15, scale: 2 }).default("0"),
  rateDetails: jsonb("rate_details").default("{}"),
  invoiceDetails: jsonb("invoice_details").default("{}"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
