import { pgTable, serial, text, numeric, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";

export const supplierContractsTable = pgTable("supplier_contracts", {
  id: serial("id").primaryKey(),
  contractNumber: text("contract_number").notNull().unique(),
  supplierId: integer("supplier_id").notNull(),
  contractType: text("contract_type").notNull().default("מסגרת"),
  title: text("title").notNull(),
  description: text("description"),
  startDate: date("start_date").notNull(),
  endDate: date("end_date"),
  autoRenewal: boolean("auto_renewal").default(false),
  renewalPeriodMonths: integer("renewal_period_months").default(12),
  renewalNoticeDays: integer("renewal_notice_days").default(30),
  contractValue: numeric("contract_value").default("0"),
  currency: text("currency").default("ILS"),
  paymentTerms: text("payment_terms"),
  paymentFrequency: text("payment_frequency").default("חודשי"),
  slaResponseTime: text("sla_response_time"),
  slaResolutionTime: text("sla_resolution_time"),
  slaUptimePct: numeric("sla_uptime_pct"),
  slaDetails: text("sla_details"),
  penaltyLateDelivery: numeric("penalty_late_delivery").default("0"),
  penaltyQualityIssue: numeric("penalty_quality_issue").default("0"),
  penaltySlaBreach: numeric("penalty_sla_breach").default("0"),
  penaltyDetails: text("penalty_details"),
  warrantyPeriodMonths: integer("warranty_period_months").default(0),
  warrantyDetails: text("warranty_details"),
  terminationNoticeDays: integer("termination_notice_days").default(30),
  terminationConditions: text("termination_conditions"),
  contactPerson: text("contact_person"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  responsiblePerson: text("responsible_person"),
  department: text("department"),
  categories: text("categories"),
  notes: text("notes"),
  attachmentUrls: text("attachment_urls"),
  status: text("status").notNull().default("טיוטה"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
