import { pgTable, serial, text, integer, numeric, date, timestamp, boolean } from "drizzle-orm/pg-core";

export const suppliersTable = pgTable("suppliers", {
  id: serial("id").primaryKey(),
  supplierNumber: text("supplier_number").notNull().unique(),
  supplierName: text("supplier_name").notNull(),
  contactPerson: text("contact_person"),
  phone: text("phone"),
  mobile: text("mobile"),
  fax: text("fax"),
  email: text("email"),
  website: text("website"),
  address: text("address"),
  city: text("city"),
  country: text("country"),
  category: text("category").notNull().default("כללי"),
  supplyType: text("supply_type"),
  paymentTerms: text("payment_terms"),
  leadTimeDays: integer("lead_time_days"),
  vatNumber: text("vat_number"),
  taxId: text("tax_id"),
  bankName: text("bank_name"),
  bankBranch: text("bank_branch"),
  bankAccountNumber: text("bank_account_number"),
  creditLimit: numeric("credit_limit"),
  rating: integer("rating").default(0),
  certifications: text("certifications"),
  contractStartDate: date("contract_start_date"),
  contractEndDate: date("contract_end_date"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  activityField: text("activity_field"),
  materialTypes: text("material_types"),
  geographicArea: text("geographic_area"),
  currency: text("currency").default("ILS"),
  creditDays: integer("credit_days"),
  minimumOrder: text("minimum_order"),
  urgentLeadTimeDays: integer("urgent_lead_time_days"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  swiftCode: text("swift_code"),
  iban: text("iban"),
  secondaryContact: text("secondary_contact"),
  secondaryPhone: text("secondary_phone"),
  secondaryEmail: text("secondary_email"),
  preferredSupplier: boolean("preferred_supplier").default(false),
  paymentMethod: text("payment_method"),
  taxWithholdingRate: numeric("tax_withholding_rate").default("0"),
  vatExempt: boolean("vat_exempt").default(false),
  qualityRating: numeric("quality_rating"),
  deliveryRating: numeric("delivery_rating"),
  priceRating: numeric("price_rating"),
  insuranceCertificate: text("insurance_certificate"),
  insuranceExpiry: date("insurance_expiry"),
  isoCertified: boolean("iso_certified").default(false),
  isoCertificateNumber: text("iso_certificate_number"),
  blacklisted: boolean("blacklisted").default(false),
  blacklistReason: text("blacklist_reason"),
  annualVolume: numeric("annual_volume").default("0"),
  discountPercent: numeric("discount_percent").default("0"),
  returnPolicy: text("return_policy"),
  latitude: numeric("latitude"),
  longitude: numeric("longitude"),
  supplierTier: text("supplier_tier").default("approved"),
  supplierType: text("supplier_type").default("manufacturer"),
  minOrderValue: numeric("min_order_value", { precision: 15, scale: 2 }),
  onTimeDeliveryPct: numeric("on_time_delivery_pct", { precision: 5, scale: 2 }),
  certificationsJson: text("certifications_json"),
  annualSpend: numeric("annual_spend", { precision: 15, scale: 2 }),
  internalNotes: text("internal_notes"),
  deletedAt: timestamp("deleted_at"),
});
