export const ACTION_LABELS: Record<string, { label: string; icon: string; color: string }> = {
  sql_write: { label: "SQL כתיבה", icon: "🗄️", color: "text-orange-400" },
  sql_read: { label: "SQL קריאה", icon: "📊", color: "text-teal-400" },
  create_record: { label: "רשומה חדשה", icon: "➕", color: "text-green-400" },
  update_record: { label: "עדכון רשומה", icon: "✏️", color: "text-blue-400" },
  delete_record: { label: "מחיקת רשומה", icon: "🗑️", color: "text-red-400" },
  get_record: { label: "קריאת רשומה", icon: "👁️", color: "text-sky-400" },
  clone_record: { label: "שכפול רשומה", icon: "📋", color: "text-lime-400" },
  create_entity: { label: "ישות חדשה", icon: "🏗️", color: "text-purple-400" },
  update_entity: { label: "עדכון ישות", icon: "✏️", color: "text-violet-400" },
  create_field: { label: "שדה חדש", icon: "📝", color: "text-cyan-400" },
  update_field: { label: "עדכון שדה", icon: "✏️", color: "text-sky-400" },
  create_module: { label: "מודול חדש", icon: "📦", color: "text-amber-400" },
  api_call: { label: "קריאת API", icon: "🔌", color: "text-indigo-400" },
  list_modules: { label: "רשימת מודולים", icon: "📋", color: "text-muted-foreground" },
  list_entities: { label: "רשימת ישויות", icon: "📋", color: "text-muted-foreground" },
  list_entity_fields: { label: "שדות ישות", icon: "📋", color: "text-muted-foreground" },
  search_records: { label: "חיפוש רשומות", icon: "🔍", color: "text-yellow-400" },
  bulk_create_records: { label: "יצירה מרובה", icon: "📥", color: "text-emerald-400" },
  bulk_update_records: { label: "עדכון מרובה", icon: "📝", color: "text-blue-300" },
  bulk_delete_records: { label: "מחיקה מרובה", icon: "🗑️", color: "text-red-300" },
  describe_table: { label: "מבנה טבלה", icon: "🔬", color: "text-pink-400" },
  count_records: { label: "ספירת רשומות", icon: "#️⃣", color: "text-fuchsia-400" },
  list_tables: { label: "רשימת טבלאות", icon: "📑", color: "text-gray-300" },
  table_stats: { label: "סטטיסטיקת טבלאות", icon: "📈", color: "text-rose-400" },
  db_size: { label: "גודל מסד נתונים", icon: "💾", color: "text-violet-300" },
  db_indexes: { label: "אינדקסים", icon: "🔗", color: "text-amber-300" },
  find_entity: { label: "חיפוש ישות", icon: "🔎", color: "text-yellow-300" },
  entity_summary: { label: "סיכום ישות", icon: "📄", color: "text-cyan-300" },
  validate_entity: { label: "בדיקת ישות", icon: "✅", color: "text-green-300" },
  compare_entities: { label: "השוואת ישויות", icon: "⚖️", color: "text-indigo-300" },
  export_data: { label: "ייצוא נתונים", icon: "📤", color: "text-emerald-300" },
  system_stats: { label: "סטטוס מערכת", icon: "🖥️", color: "text-blue-200" },
  global_search: { label: "חיפוש גלובלי", icon: "🌐", color: "text-yellow-200" },
  duplicate_entity: { label: "שכפול ישות", icon: "📑", color: "text-purple-300" },
  entity_relations: { label: "קשרי ישות", icon: "🔗", color: "text-cyan-200" },
  schema_export: { label: "ייצוא סכמה", icon: "📋", color: "text-green-200" },
  transfer_records: { label: "העברת רשומות", icon: "🔄", color: "text-orange-200" },
  field_stats: { label: "סטטיסטיקת שדה", icon: "📊", color: "text-pink-200" },
  audit_log: { label: "יומן שינויים", icon: "📜", color: "text-amber-200" },
  performance_check: { label: "בדיקת ביצועים", icon: "⚡", color: "text-lime-300" },
  data_quality_report: { label: "דוח איכות נתונים", icon: "📋", color: "text-teal-200" },
  smart_suggest: { label: "הצעות חכמות", icon: "💡", color: "text-yellow-300" },
  list_menu_items: { label: "רשימת תפריט", icon: "📋", color: "text-blue-300" },
  delete_menu_item: { label: "מחיקת פריט תפריט", icon: "🗑️", color: "text-red-400" },
  create_menu_item: { label: "יצירת פריט תפריט", icon: "➕", color: "text-green-400" },
  update_menu_item: { label: "עדכון פריט תפריט", icon: "✏️", color: "text-amber-400" },
  read_file: { label: "קריאת קובץ", icon: "📖", color: "text-sky-300" },
  write_file: { label: "כתיבת קובץ", icon: "💾", color: "text-green-300" },
  edit_file: { label: "עריכת קובץ", icon: "✂️", color: "text-yellow-300" },
  delete_file: { label: "מחיקת קובץ", icon: "🗑️", color: "text-red-300" },
  list_files: { label: "רשימת קבצים", icon: "📁", color: "text-blue-200" },
  search_code: { label: "חיפוש בקוד", icon: "🔍", color: "text-purple-300" },
  run_command: { label: "הרצת פקודה", icon: "⚙️", color: "text-orange-300" },
  create_directory: { label: "יצירת תיקייה", icon: "📂", color: "text-teal-300" },
  file_info: { label: "מידע על קובץ", icon: "ℹ️", color: "text-gray-300" },
  git_status: { label: "Git סטטוס", icon: "🔀", color: "text-orange-200" },
  git_log: { label: "Git היסטוריה", icon: "📜", color: "text-violet-200" },
  git_diff: { label: "Git שינויים", icon: "📝", color: "text-pink-300" },
  install_package: { label: "התקנת חבילה", icon: "📦", color: "text-green-200" },
  restart_server: { label: "הפעלה מחדש", icon: "🔄", color: "text-cyan-300" },
  company_report: { label: "דוח חברה", icon: "🏢", color: "text-blue-300" },
  financial_summary: { label: "סיכום פיננסי", icon: "💰", color: "text-green-300" },
  hr_summary: { label: "סיכום משאבי אנוש", icon: "👥", color: "text-violet-300" },
  inventory_summary: { label: "סיכום מלאי", icon: "📦", color: "text-amber-300" },
  production_summary: { label: "סיכום ייצור", icon: "🏭", color: "text-orange-300" },
  sales_summary: { label: "סיכום מכירות", icon: "💼", color: "text-emerald-300" },
  purchasing_summary: { label: "סיכום רכש", icon: "🛒", color: "text-teal-300" },
  crm_pipeline: { label: "Pipeline מכירות", icon: "📈", color: "text-indigo-300" },
  agent_health_check: { label: "בריאות סוכנים", icon: "🤖", color: "text-cyan-200" },
  workflow_report: { label: "דוח Workflows", icon: "⚙️", color: "text-blue-200" },
  validate_all_entities: { label: "בדיקת כל הישויות", icon: "✅", color: "text-green-200" },
  api_documentation: { label: "תיעוד API", icon: "📚", color: "text-purple-200" },
  backup_check: { label: "בדיקת גיבוי", icon: "💾", color: "text-gray-300" },
  module_coverage: { label: "כיסוי מודולים", icon: "📊", color: "text-rose-300" },
  recent_activity: { label: "פעילות אחרונה", icon: "🕐", color: "text-yellow-200" },
};
