-- ============================================================
-- FILE: supabase/migrations/00038_merged_sources_menu_additions.sql
-- Purpose:
--   Add menu entries for pages discovered when merging additional
--   source archives (technokoluzi-erp, AI-Task-Manager, Location-Finder,
--   GPS-Connect, Invoice-Ledger, erp-upload, files-*).
--
--   Routes already present in the menu (from 00034/00035/00036) are
--   NOT re-inserted. Duplicates are guarded by a pre-delete on route.
--
-- Post-00036 category ids:
--   1 דשבורד | 2 מכירות | 3 רכש | 4 פרויקטים | 5 מלאי | 6 כספים
--   7 מיסוי | 8 כ״א ושכר | 9 תקשורת | 10 מסמכים | 11 AI
--   12 Compliance | 13 תשתיות | 14 אינטגרציות | 15 מערכת
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- Category 2: מכירות ולקוחות — 11 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/crm/agent-control-dashboard',
  '/crm/behavioral-analytics',
  '/crm/communication-intelligence',
  '/crm/crm-communications-hub',
  '/crm/decision-engine',
  '/crm/intelligence-engine',
  '/crm/nurture-sequences',
  '/crm/pipeline-financial',
  '/crm/predictive-forecasting',
  '/crm/relationship-graph',
  '/sales/quote360'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Agent Control Dashboard', '/crm/agent-control-dashboard', '💼', 2, 700),
  ('Behavioral Analytics', '/crm/behavioral-analytics', '💼', 2, 701),
  ('Communication Intelligence', '/crm/communication-intelligence', '💼', 2, 702),
  ('Crm Communications Hub', '/crm/crm-communications-hub', '💼', 2, 703),
  ('Decision Engine', '/crm/decision-engine', '💼', 2, 704),
  ('Intelligence Engine', '/crm/intelligence-engine', '💼', 2, 705),
  ('Nurture Sequences', '/crm/nurture-sequences', '💼', 2, 706),
  ('Pipeline Financial', '/crm/pipeline-financial', '💼', 2, 707),
  ('Predictive Forecasting', '/crm/predictive-forecasting', '💼', 2, 708),
  ('Relationship Graph', '/crm/relationship-graph', '💼', 2, 709),
  ('Quote360', '/sales/quote360', '💼', 2, 710);

-- ──────────────────────────────────────────────────────────────
-- Category 3: רכש וספקים — 32 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/procurement/competitor-analysis',
  '/procurement/delivery-documents',
  '/procurement/documents-signatures',
  '/procurement/inventory-sync',
  '/procurement/logistics-tracking',
  '/procurement/po-approvals',
  '/procurement/price-management',
  '/procurement/procurement-alerts',
  '/procurement/procurement-compliance',
  '/procurement/procurement-exceptions',
  '/procurement/procurement-profit-impact',
  '/procurement/procurement-settings',
  '/procurement/procurement-simulation',
  '/procurement/products/product-bom',
  '/procurement/products/product-costing',
  '/procurement/products/products-dashboard',
  '/procurement/products/products-list',
  '/procurement/profitability-dashboard',
  '/procurement/purchase-orders',
  '/procurement/quality-control',
  '/procurement/raw-materials/cost-analysis',
  '/procurement/raw-materials/raw-material-stock',
  '/procurement/raw-materials/raw-materials-dashboard',
  '/procurement/raw-materials/raw-materials-list',
  '/procurement/raw-materials/scrap-waste',
  '/procurement/raw-materials/weight-calculator',
  '/procurement/risk-hedging',
  '/procurement/supplier-dependency',
  '/procurement/supplier-management',
  '/procurement/supplier-portal',
  '/procurement/supplier-returns',
  '/procurement/vendor-negotiation'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Competitor Analysis', '/procurement/competitor-analysis', '🧾', 3, 800),
  ('Delivery Documents', '/procurement/delivery-documents', '🧾', 3, 801),
  ('Documents Signatures', '/procurement/documents-signatures', '🧾', 3, 802),
  ('Inventory Sync', '/procurement/inventory-sync', '🧾', 3, 803),
  ('Logistics Tracking', '/procurement/logistics-tracking', '🧾', 3, 804),
  ('Po Approvals', '/procurement/po-approvals', '🧾', 3, 805),
  ('Price Management', '/procurement/price-management', '🧾', 3, 806),
  ('Procurement Alerts', '/procurement/procurement-alerts', '🧾', 3, 807),
  ('Procurement Compliance', '/procurement/procurement-compliance', '🧾', 3, 808),
  ('Procurement Exceptions', '/procurement/procurement-exceptions', '🧾', 3, 809),
  ('Procurement Profit Impact', '/procurement/procurement-profit-impact', '🧾', 3, 810),
  ('Procurement Settings', '/procurement/procurement-settings', '🧾', 3, 811),
  ('Procurement Simulation', '/procurement/procurement-simulation', '🧾', 3, 812),
  ('Product Bom', '/procurement/products/product-bom', '🧾', 3, 813),
  ('Product Costing', '/procurement/products/product-costing', '🧾', 3, 814),
  ('Products Dashboard', '/procurement/products/products-dashboard', '🧾', 3, 815),
  ('Products List', '/procurement/products/products-list', '🧾', 3, 816),
  ('Profitability Dashboard', '/procurement/profitability-dashboard', '🧾', 3, 817),
  ('Purchase Orders', '/procurement/purchase-orders', '🧾', 3, 818),
  ('Quality Control', '/procurement/quality-control', '🧾', 3, 819),
  ('Cost Analysis', '/procurement/raw-materials/cost-analysis', '🧾', 3, 820),
  ('Raw Material Stock', '/procurement/raw-materials/raw-material-stock', '🧾', 3, 821),
  ('Raw Materials Dashboard', '/procurement/raw-materials/raw-materials-dashboard', '🧾', 3, 822),
  ('Raw Materials List', '/procurement/raw-materials/raw-materials-list', '🧾', 3, 823),
  ('Scrap Waste', '/procurement/raw-materials/scrap-waste', '🧾', 3, 824),
  ('Weight Calculator', '/procurement/raw-materials/weight-calculator', '🧾', 3, 825),
  ('Risk Hedging', '/procurement/risk-hedging', '🧾', 3, 826),
  ('Supplier Dependency', '/procurement/supplier-dependency', '🧾', 3, 827),
  ('Supplier Management', '/procurement/supplier-management', '🧾', 3, 828),
  ('Supplier Portal', '/procurement/supplier-portal', '🧾', 3, 829),
  ('Supplier Returns', '/procurement/supplier-returns', '🧾', 3, 830),
  ('Vendor Negotiation', '/procurement/vendor-negotiation', '🧾', 3, 831);

-- ──────────────────────────────────────────────────────────────
-- Category 4: פרויקטים — 10 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/projects/customer-project-portal-page',
  '/projects/project-alerts',
  '/projects/project-documents-page',
  '/projects/project-events-audit',
  '/projects/project-portal-page',
  '/projects/project-production-tracking',
  '/projects/project-settings',
  '/projects/project-templates-page',
  '/projects/project-workflow',
  '/projects/risk-dashboard-page'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Customer Project Portal Page', '/projects/customer-project-portal-page', '📐', 4, 900),
  ('Project Alerts', '/projects/project-alerts', '📐', 4, 901),
  ('Project Documents Page', '/projects/project-documents-page', '📐', 4, 902),
  ('Project Events Audit', '/projects/project-events-audit', '📐', 4, 903),
  ('Project Portal Page', '/projects/project-portal-page', '📐', 4, 904),
  ('Project Production Tracking', '/projects/project-production-tracking', '📐', 4, 905),
  ('Project Settings', '/projects/project-settings', '📐', 4, 906),
  ('Project Templates Page', '/projects/project-templates-page', '📐', 4, 907),
  ('Project Workflow', '/projects/project-workflow', '📐', 4, 908),
  ('Risk Dashboard Page', '/projects/risk-dashboard-page', '📐', 4, 909);

-- ──────────────────────────────────────────────────────────────
-- Category 5: מלאי ומחסן — 15 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/assets/assets-dashboard',
  '/assets/equipment-insurance',
  '/assets/leasing',
  '/assets/tools-dies',
  '/inventory/inventory-alerts',
  '/inventory/inventory-ultra-dashboard',
  '/inventory/stock-items-management',
  '/inventory/vmi-supplier-portal',
  '/inventory/warehouses-management',
  '/inventory/wms-analytics',
  '/inventory/wms-consignment',
  '/inventory/wms-expiry-dashboard',
  '/inventory/wms-kits',
  '/inventory/wms-location-hierarchy',
  '/inventory/wms-valuation'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Assets Dashboard', '/assets/assets-dashboard', '🚗', 5, 1000),
  ('Equipment Insurance', '/assets/equipment-insurance', '🚗', 5, 1001),
  ('Leasing', '/assets/leasing', '🚗', 5, 1002),
  ('Tools Dies', '/assets/tools-dies', '🚗', 5, 1003),
  ('Inventory Alerts', '/inventory/inventory-alerts', '📦', 5, 1004),
  ('Inventory Ultra Dashboard', '/inventory/inventory-ultra-dashboard', '📦', 5, 1005),
  ('Stock Items Management', '/inventory/stock-items-management', '📦', 5, 1006),
  ('Vmi Supplier Portal', '/inventory/vmi-supplier-portal', '📦', 5, 1007),
  ('Warehouses Management', '/inventory/warehouses-management', '📦', 5, 1008),
  ('Wms Analytics', '/inventory/wms-analytics', '📦', 5, 1009),
  ('Wms Consignment', '/inventory/wms-consignment', '📦', 5, 1010),
  ('Wms Expiry Dashboard', '/inventory/wms-expiry-dashboard', '📦', 5, 1011),
  ('Wms Kits', '/inventory/wms-kits', '📦', 5, 1012),
  ('Wms Location Hierarchy', '/inventory/wms-location-hierarchy', '📦', 5, 1013),
  ('Wms Valuation', '/inventory/wms-valuation', '📦', 5, 1014);

-- ──────────────────────────────────────────────────────────────
-- Category 6: כספים וחשבונאות — 16 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/finance/accounting-export',
  '/finance/contractor-payment-decision-model',
  '/finance/fin-control-center',
  '/finance/finance-alerts',
  '/finance/finance-fixed-assets',
  '/finance/financial-analytics',
  '/finance/institutional/financial-statements',
  '/finance/institutional/monte-carlo-engine',
  '/finance/institutional/ratio-dashboard',
  '/finance/institutional/risk-dashboard',
  '/finance/institutional/treasury-dashboard',
  '/finance/israeli-integrations',
  '/finance/masav-management',
  '/finance/payables-dashboard',
  '/finance/payment-operations',
  '/finance/profitability-feedback-loop'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Accounting Export', '/finance/accounting-export', '💰', 6, 1100),
  ('Contractor Payment Decision Model', '/finance/contractor-payment-decision-model', '💰', 6, 1101),
  ('Fin Control Center', '/finance/fin-control-center', '💰', 6, 1102),
  ('Finance Alerts', '/finance/finance-alerts', '💰', 6, 1103),
  ('Finance Fixed Assets', '/finance/finance-fixed-assets', '💰', 6, 1104),
  ('Financial Analytics', '/finance/financial-analytics', '💰', 6, 1105),
  ('Financial Statements', '/finance/institutional/financial-statements', '💰', 6, 1106),
  ('Monte Carlo Engine', '/finance/institutional/monte-carlo-engine', '💰', 6, 1107),
  ('Ratio Dashboard', '/finance/institutional/ratio-dashboard', '💰', 6, 1108),
  ('Risk Dashboard', '/finance/institutional/risk-dashboard', '💰', 6, 1109),
  ('Treasury Dashboard', '/finance/institutional/treasury-dashboard', '💰', 6, 1110),
  ('Israeli Integrations', '/finance/israeli-integrations', '💰', 6, 1111),
  ('Masav Management', '/finance/masav-management', '💰', 6, 1112),
  ('Payables Dashboard', '/finance/payables-dashboard', '💰', 6, 1113),
  ('Payment Operations', '/finance/payment-operations', '💰', 6, 1114),
  ('Profitability Feedback Loop', '/finance/profitability-feedback-loop', '💰', 6, 1115);

-- ──────────────────────────────────────────────────────────────
-- Category 8: כוח אדם ושכר — 12 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/hr/compliance-dashboard',
  '/hr/disciplinary-incidents',
  '/hr/employment-history',
  '/hr/feedback-360',
  '/hr/hr-alerts',
  '/hr/hr-analytics',
  '/hr/hr-settings',
  '/hr/labor-cost-allocation',
  '/hr/offboarding-retirement',
  '/hr/payroll-engine',
  '/hr/training-management',
  '/workforce/employee360'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Compliance Dashboard', '/hr/compliance-dashboard', '👥', 8, 1300),
  ('Disciplinary Incidents', '/hr/disciplinary-incidents', '👥', 8, 1301),
  ('Employment History', '/hr/employment-history', '👥', 8, 1302),
  ('Feedback 360', '/hr/feedback-360', '👥', 8, 1303),
  ('Hr Alerts', '/hr/hr-alerts', '👥', 8, 1304),
  ('Hr Analytics', '/hr/hr-analytics', '👥', 8, 1305),
  ('Hr Settings', '/hr/hr-settings', '👥', 8, 1306),
  ('Labor Cost Allocation', '/hr/labor-cost-allocation', '👥', 8, 1307),
  ('Offboarding Retirement', '/hr/offboarding-retirement', '👥', 8, 1308),
  ('Payroll Engine', '/hr/payroll-engine', '👥', 8, 1309),
  ('Training Management', '/hr/training-management', '👥', 8, 1310),
  ('Employee360', '/workforce/employee360', '👥', 8, 1311);

-- ──────────────────────────────────────────────────────────────
-- Category 9: תקשורת — 4 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/customer-service/complaints',
  '/customer-service/rma',
  '/customer-service/service-dashboard',
  '/customer-service/warranty-management'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Complaints', '/customer-service/complaints', '💬', 9, 1400),
  ('Rma', '/customer-service/rma', '💬', 9, 1401),
  ('Service Dashboard', '/customer-service/service-dashboard', '💬', 9, 1402),
  ('Warranty Management', '/customer-service/warranty-management', '💬', 9, 1403);

-- ──────────────────────────────────────────────────────────────
-- Category 10: מסמכים — 20 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/contracts/contract-ai-analysis',
  '/contracts/contract-analytics-dashboard',
  '/contracts/contract-risk-scoring',
  '/contracts/contract-templates',
  '/contracts/contracts-dashboard',
  '/contracts/contracts-management',
  '/contracts/nda-agreements',
  '/contracts/service-agreements',
  '/documents/bulk-operations',
  '/documents/document-control',
  '/documents/document-permissions',
  '/documents/document-registry',
  '/documents/document-search',
  '/documents/document-settings',
  '/documents/incoming-documents',
  '/documents/module-documents',
  '/documents/ocr-processing',
  '/documents/outgoing-documents',
  '/documents/retention-compliance',
  '/documents/version-control'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Contract Ai Analysis', '/contracts/contract-ai-analysis', '📄', 10, 1500),
  ('Contract Analytics Dashboard', '/contracts/contract-analytics-dashboard', '📄', 10, 1501),
  ('Contract Risk Scoring', '/contracts/contract-risk-scoring', '📄', 10, 1502),
  ('Contract Templates', '/contracts/contract-templates', '📄', 10, 1503),
  ('Contracts Dashboard', '/contracts/contracts-dashboard', '📄', 10, 1504),
  ('Contracts Management', '/contracts/contracts-management', '📄', 10, 1505),
  ('Nda Agreements', '/contracts/nda-agreements', '📄', 10, 1506),
  ('Service Agreements', '/contracts/service-agreements', '📄', 10, 1507),
  ('Bulk Operations', '/documents/bulk-operations', '📄', 10, 1508),
  ('Document Control', '/documents/document-control', '📄', 10, 1509),
  ('Document Permissions', '/documents/document-permissions', '📄', 10, 1510),
  ('Document Registry', '/documents/document-registry', '📄', 10, 1511),
  ('Document Search', '/documents/document-search', '📄', 10, 1512),
  ('Document Settings', '/documents/document-settings', '📄', 10, 1513),
  ('Incoming Documents', '/documents/incoming-documents', '📄', 10, 1514),
  ('Module Documents', '/documents/module-documents', '📄', 10, 1515),
  ('Ocr Processing', '/documents/ocr-processing', '📄', 10, 1516),
  ('Outgoing Documents', '/documents/outgoing-documents', '📄', 10, 1517),
  ('Retention Compliance', '/documents/retention-compliance', '📄', 10, 1518),
  ('Version Control', '/documents/version-control', '📄', 10, 1519);

-- ──────────────────────────────────────────────────────────────
-- Category 11: AI & אינטליגנציה — 42 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/advanced/anomaly-detection',
  '/advanced/digital-twin-factory',
  '/advanced/graph-analytics',
  '/advanced/nl-query-assistant',
  '/advanced/predictive-forecasting',
  '/ai-engine/ai-customer-service',
  '/ai-engine/bash44-agent-config',
  '/ai-engine/bash44-agent-runs',
  '/ai-engine/bash44-alerts-center',
  '/ai-engine/bash44-approval-queue',
  '/ai-engine/bash44-control-center',
  '/ai-engine/bash44-executive-brief',
  '/ai-engine/bash44-knowledge-contexts',
  '/ai-engine/bash44-recommendations',
  '/ai-engine/employee-chatbot',
  '/ai-engine/kobi-prompts',
  '/ai-engine/ml-training-pipeline',
  '/bi/bi-hub',
  '/bi/comparative-analytics',
  '/bi/custom-dashboards',
  '/bi/data-explorer',
  '/bi/scheduled-reports',
  '/builder/business-rules-builder',
  '/builder/scheduled-tasks',
  '/builder/visual-workflow-designer',
  '/builder/webhook-management',
  '/command-center/causal-impact-viewer',
  '/command-center/command-center',
  '/command-center/operations-control-room',
  '/command-center/procurement-control-room',
  '/command-center/workforce-control-room',
  '/reports/bi-financial-statements',
  '/reports/bi-hr-analytics',
  '/reports/bi-inventory-analytics',
  '/reports/bi-production-analytics',
  '/reports/bi-sales-analytics',
  '/reports/financial/report-customer-aging',
  '/reports/financial/report-executive-summary',
  '/reports/financial/report-fiscal',
  '/reports/financial/report-invoice-analysis',
  '/reports/financial/report-vat',
  '/reports/financial/report-vendor-aging'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Anomaly Detection', '/advanced/anomaly-detection', '🤖', 11, 1600),
  ('Digital Twin Factory', '/advanced/digital-twin-factory', '🤖', 11, 1601),
  ('Graph Analytics', '/advanced/graph-analytics', '🤖', 11, 1602),
  ('Nl Query Assistant', '/advanced/nl-query-assistant', '🤖', 11, 1603),
  ('Predictive Forecasting', '/advanced/predictive-forecasting', '🤖', 11, 1604),
  ('Ai Customer Service', '/ai-engine/ai-customer-service', '🤖', 11, 1605),
  ('Bash44 Agent Config', '/ai-engine/bash44-agent-config', '🤖', 11, 1606),
  ('Bash44 Agent Runs', '/ai-engine/bash44-agent-runs', '🤖', 11, 1607),
  ('Bash44 Alerts Center', '/ai-engine/bash44-alerts-center', '🤖', 11, 1608),
  ('Bash44 Approval Queue', '/ai-engine/bash44-approval-queue', '🤖', 11, 1609),
  ('Bash44 Control Center', '/ai-engine/bash44-control-center', '🤖', 11, 1610),
  ('Bash44 Executive Brief', '/ai-engine/bash44-executive-brief', '🤖', 11, 1611),
  ('Bash44 Knowledge Contexts', '/ai-engine/bash44-knowledge-contexts', '🤖', 11, 1612),
  ('Bash44 Recommendations', '/ai-engine/bash44-recommendations', '🤖', 11, 1613),
  ('Employee Chatbot', '/ai-engine/employee-chatbot', '🤖', 11, 1614),
  ('Kobi Prompts', '/ai-engine/kobi-prompts', '🤖', 11, 1615),
  ('Ml Training Pipeline', '/ai-engine/ml-training-pipeline', '🤖', 11, 1616),
  ('Bi Hub', '/bi/bi-hub', '🤖', 11, 1617),
  ('Comparative Analytics', '/bi/comparative-analytics', '🤖', 11, 1618),
  ('Custom Dashboards', '/bi/custom-dashboards', '🤖', 11, 1619),
  ('Data Explorer', '/bi/data-explorer', '🤖', 11, 1620),
  ('Scheduled Reports', '/bi/scheduled-reports', '🤖', 11, 1621),
  ('Business Rules Builder', '/builder/business-rules-builder', '🤖', 11, 1622),
  ('Scheduled Tasks', '/builder/scheduled-tasks', '🤖', 11, 1623),
  ('Visual Workflow Designer', '/builder/visual-workflow-designer', '🤖', 11, 1624),
  ('Webhook Management', '/builder/webhook-management', '🤖', 11, 1625),
  ('Causal Impact Viewer', '/command-center/causal-impact-viewer', '🤖', 11, 1626),
  ('Command Center', '/command-center/command-center', '🤖', 11, 1627),
  ('Operations Control Room', '/command-center/operations-control-room', '🤖', 11, 1628),
  ('Procurement Control Room', '/command-center/procurement-control-room', '🤖', 11, 1629),
  ('Workforce Control Room', '/command-center/workforce-control-room', '🤖', 11, 1630),
  ('Bi Financial Statements', '/reports/bi-financial-statements', '📊', 11, 1631),
  ('Bi Hr Analytics', '/reports/bi-hr-analytics', '📊', 11, 1632),
  ('Bi Inventory Analytics', '/reports/bi-inventory-analytics', '📊', 11, 1633),
  ('Bi Production Analytics', '/reports/bi-production-analytics', '📊', 11, 1634),
  ('Bi Sales Analytics', '/reports/bi-sales-analytics', '📊', 11, 1635),
  ('Report Customer Aging', '/reports/financial/report-customer-aging', '📊', 11, 1636),
  ('Report Executive Summary', '/reports/financial/report-executive-summary', '📊', 11, 1637),
  ('Report Fiscal', '/reports/financial/report-fiscal', '📊', 11, 1638),
  ('Report Invoice Analysis', '/reports/financial/report-invoice-analysis', '📊', 11, 1639),
  ('Report Vat', '/reports/financial/report-vat', '📊', 11, 1640),
  ('Report Vendor Aging', '/reports/financial/report-vendor-aging', '📊', 11, 1641);

-- ──────────────────────────────────────────────────────────────
-- Category 12: רגולציה וציות — 9 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/security/backup-dr',
  '/security/encryption-management',
  '/security/tabs/api-keys-security',
  '/security/tabs/cors-management',
  '/security/tabs/geo-blocking',
  '/security/tabs/ip-management',
  '/security/tabs/rate-limit-config',
  '/security/tabs/vulnerability-tracker',
  '/security/tabs/webhook-secrets'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Backup Dr', '/security/backup-dr', '🛡️', 12, 1700),
  ('Encryption Management', '/security/encryption-management', '🛡️', 12, 1701),
  ('Api Keys Security', '/security/tabs/api-keys-security', '🛡️', 12, 1702),
  ('Cors Management', '/security/tabs/cors-management', '🛡️', 12, 1703),
  ('Geo Blocking', '/security/tabs/geo-blocking', '🛡️', 12, 1704),
  ('Ip Management', '/security/tabs/ip-management', '🛡️', 12, 1705),
  ('Rate Limit Config', '/security/tabs/rate-limit-config', '🛡️', 12, 1706),
  ('Vulnerability Tracker', '/security/tabs/vulnerability-tracker', '🛡️', 12, 1707),
  ('Webhook Secrets', '/security/tabs/webhook-secrets', '🛡️', 12, 1708);

-- ──────────────────────────────────────────────────────────────
-- Category 14: אינטגרציות — 9 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/api-hub',
  '/integrations/auth-tokens',
  '/integrations/integration-alerts',
  '/integrations/integration-audit',
  '/integrations/integration-settings',
  '/integrations/payload-validation',
  '/integrations/rate-limits',
  '/integrations/retries-dlq',
  '/integrations/transformation-engine'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Api Hub', '/api-hub', '🔌', 14, 1900),
  ('Auth Tokens', '/integrations/auth-tokens', '🔌', 14, 1901),
  ('Integration Alerts', '/integrations/integration-alerts', '🔌', 14, 1902),
  ('Integration Audit', '/integrations/integration-audit', '🔌', 14, 1903),
  ('Integration Settings', '/integrations/integration-settings', '🔌', 14, 1904),
  ('Payload Validation', '/integrations/payload-validation', '🔌', 14, 1905),
  ('Rate Limits', '/integrations/rate-limits', '🔌', 14, 1906),
  ('Retries Dlq', '/integrations/retries-dlq', '🔌', 14, 1907),
  ('Transformation Engine', '/integrations/transformation-engine', '🔌', 14, 1908);

-- ──────────────────────────────────────────────────────────────
-- Category 15: מערכת וניהול — 201 new routes
-- ──────────────────────────────────────────────────────────────
delete from public.app_menu where route in (
  '/data-fabric/data-fabric-overview',
  '/data-fabric/data-products',
  '/data-fabric/data-quality-dashboard',
  '/data-fabric/identity-resolution',
  '/data-fabric/lineage-graph',
  '/data-migration',
  '/data-platform/canonical-explorer',
  '/data-platform/platform-observatory',
  '/data-platform/quarantine-browser',
  '/ehs/annual-safety-report',
  '/ehs/emergency-preparedness',
  '/ehs/energy-management',
  '/ehs/israeli-regulatory',
  '/ehs/ppe-management',
  '/ehs/risk-assessment',
  '/ehs/safety-inspections',
  '/ehs/safety-training-certs',
  '/ehs/waste-management',
  '/ehs/work-permits',
  '/engineering/design-reviews',
  '/engineering/drawing-management',
  '/engineering/engineering-alerts',
  '/engineering/engineering-analytics',
  '/engineering/engineering-calculations',
  '/engineering/engineering-command-center',
  '/engineering/engineering-documents',
  '/engineering/engineering-office',
  '/engineering/engineering-projects',
  '/engineering/engineering-settings',
  '/engineering/engineering-standards',
  '/engineering/material-specifications',
  '/engineering/product-catalog',
  '/engineering/prototype-testing',
  '/executive/bi-command-center',
  '/executive/executive-command-center',
  '/executive/executive-scorecard',
  '/fabrication/fab-accessories',
  '/fabrication/fab-assembly-orders',
  '/fabrication/fab-coating-orders',
  '/fabrication/fab-cutting-lists',
  '/fabrication/fab-finishes-colors',
  '/fabrication/fab-glass-catalog',
  '/fabrication/fab-glazing-orders',
  '/fabrication/fab-installation-orders',
  '/fabrication/fab-packing-lists',
  '/fabrication/fab-profiles',
  '/fabrication/fab-service-tickets',
  '/fabrication/fab-systems',
  '/fabrication/fab-transport-orders',
  '/fabrication/fab-welding-orders',
  '/fabrication/fab-workflow-tracker',
  '/fin/fin-accounting',
  '/fin/fin-credit-clearing',
  '/fin/fin-dashboard',
  '/fin/fin-document-create',
  '/fin/fin-document-details',
  '/fin/fin-documents-list',
  '/fin/fin-recurring',
  '/fin/fin-standing-orders',
  '/import/containers-packages',
  '/import/customs-clearance',
  '/import/foreign-suppliers',
  '/import/import-analytics',
  '/import/import-approvals',
  '/import/import-dashboard',
  '/import/import-documents',
  '/import/import-purchase-orders',
  '/import/import-receiving',
  '/import/import-risk-alerts',
  '/import/import-settings',
  '/import/import-shipments',
  '/import/import-tracking',
  '/import/landed-cost-calculator',
  '/import/shipping-forwarders',
  '/installation/customer-handover',
  '/installation/equipment-tools',
  '/installation/field-exceptions',
  '/installation/installation-alerts',
  '/installation/installation-cost-tracking',
  '/installation/installation-documents',
  '/installation/installation-management',
  '/installation/installation-orders',
  '/installation/installation-profitability',
  '/installation/installation-progress',
  '/installation/installation-quality-control',
  '/installation/installation-settings',
  '/installation/installer-profiles',
  '/installation/loading-dispatch',
  '/installation/return-service-calls',
  '/installations/gps-map',
  '/integration-hub',
  '/knowledge/faq-management',
  '/knowledge/knowledge-base',
  '/knowledge/knowledge-command-center',
  '/knowledge/lessons-learned',
  '/knowledge/sop-procedures',
  '/logistics/barcode-rfid',
  '/logistics/cross-border',
  '/logistics/customer-tracking-portal',
  '/logistics/delivery-cost-analysis',
  '/logistics/delivery-scheduling',
  '/logistics/fleet-alerts',
  '/logistics/fleet-delivery',
  '/logistics/freight',
  '/logistics/freight-audit',
  '/logistics/fuel-management',
  '/logistics/loading-dock',
  '/logistics/logistics-dashboard',
  '/logistics/packaging',
  '/logistics/proof-of-delivery',
  '/logistics/reverse-logistics',
  '/logistics/vehicle-registry',
  '/notification-settings/delivery-dashboard',
  '/notification-settings/email-templates',
  '/operations/cost-per-unit',
  '/palantir/actions-studio',
  '/palantir/aip-agent-studio',
  '/palantir/code-workspace',
  '/palantir/dossier-page',
  '/palantir/map-geospatial',
  '/palantir/pipeline-builder',
  '/palantir/timeline-analysis',
  '/platform/notifications-center',
  '/platform/security-audit',
  '/portal/customer-portal-login',
  '/pricing/actual-vs-estimated',
  '/pricing/labor-operations-cost',
  '/pricing/landed-cost-source',
  '/pricing/material-price-pull',
  '/pricing/pricing-approvals',
  '/pricing/pricing-cost-builder',
  '/pricing/pricing-cost-calculator',
  '/pricing/pricing-dashboard',
  '/pricing/pricing-price-lists',
  '/pricing/pricing-requests-list',
  '/pricing/pricing-versions',
  '/pricing/project-pricing-details',
  '/pricing/recommended-price',
  '/pricing/risk-margin-target',
  '/pricing/stock-vs-buy-decision',
  '/pricing/supplier-comparison-project',
  '/product-dev/product-certifications',
  '/product-dev/product-design',
  '/product-dev/product-dev-command-center',
  '/product-dev/product-launches',
  '/production/assembly-jobs',
  '/production/cut-jobs',
  '/production/finishing-jobs',
  '/production/labor-control',
  '/production/labor-time-tracking',
  '/production/maintenance-downtime',
  '/production/master-production-schedule',
  '/production/material-issuance',
  '/production/production-alerts',
  '/production/production-analytics',
  '/production/production-cost-tracking',
  '/production/production-exceptions',
  '/production/production-orders',
  '/production/quality-defects-rework',
  '/production/shortages-page',
  '/production/welding-jobs',
  '/production/work-stations',
  '/quality/calibration',
  '/quality/document-control',
  '/quality/test-certificates',
  '/safety/safety-procedures',
  '/safety/safety-training',
  '/service/service-analytics',
  '/service/service-cases',
  '/service/service-cost-tracking',
  '/settings/api-connection-hub',
  '/settings/api-keys',
  '/settings/israeli-integrations',
  '/settings/sections/mfa-settings',
  '/settings/sections/session-management',
  '/settings/sections/sso-settings',
  '/supplier-mgmt/supplier-development',
  '/supplier-mgmt/supplier-portal-dashboard',
  '/supplier-mgmt/supplier-scorecards',
  '/supplier-mgmt/supplier360',
  '/supplier-mgmt/supply-chain-risk',
  '/supplier-mgmt/vendor-compliance',
  '/supply-chain/bom-comparison',
  '/supply-chain/bom-cost-rollup',
  '/supply-chain/bom-templates',
  '/supply-chain/bom-versions',
  '/supply-chain/edi-admin',
  '/supply-chain/supply-chain-alerts',
  '/supply-chain/supply-chain-analytics',
  '/supply-chain/supply-chain-command-center',
  '/supply-chain/supply-chain-settings',
  '/supply-chain/supply-chain-visibility',
  '/support/support-dashboard',
  '/system/role-card',
  '/system/user-card',
  '/system/user-permission-override',
  '/system/user-role-assignment',
  '/tenders/tender-alerts',
  '/tenders/tender-analytics',
  '/tenders/tender-competitors',
  '/tenders/tender-timeline'
);

insert into public.app_menu (label, route, icon, parent_id, order_index) values
  ('Data Fabric Overview', '/data-fabric/data-fabric-overview', '📁', 15, 2000),
  ('Data Products', '/data-fabric/data-products', '📁', 15, 2001),
  ('Data Quality Dashboard', '/data-fabric/data-quality-dashboard', '📁', 15, 2002),
  ('Identity Resolution', '/data-fabric/identity-resolution', '📁', 15, 2003),
  ('Lineage Graph', '/data-fabric/lineage-graph', '📁', 15, 2004),
  ('Data Migration', '/data-migration', '📁', 15, 2005),
  ('Canonical Explorer', '/data-platform/canonical-explorer', '📁', 15, 2006),
  ('Platform Observatory', '/data-platform/platform-observatory', '📁', 15, 2007),
  ('Quarantine Browser', '/data-platform/quarantine-browser', '📁', 15, 2008),
  ('Annual Safety Report', '/ehs/annual-safety-report', '📁', 15, 2009),
  ('Emergency Preparedness', '/ehs/emergency-preparedness', '📁', 15, 2010),
  ('Energy Management', '/ehs/energy-management', '📁', 15, 2011),
  ('Israeli Regulatory', '/ehs/israeli-regulatory', '📁', 15, 2012),
  ('Ppe Management', '/ehs/ppe-management', '📁', 15, 2013),
  ('Risk Assessment', '/ehs/risk-assessment', '📁', 15, 2014),
  ('Safety Inspections', '/ehs/safety-inspections', '📁', 15, 2015),
  ('Safety Training Certs', '/ehs/safety-training-certs', '📁', 15, 2016),
  ('Waste Management', '/ehs/waste-management', '📁', 15, 2017),
  ('Work Permits', '/ehs/work-permits', '📁', 15, 2018),
  ('Design Reviews', '/engineering/design-reviews', '📁', 15, 2019),
  ('Drawing Management', '/engineering/drawing-management', '📁', 15, 2020),
  ('Engineering Alerts', '/engineering/engineering-alerts', '📁', 15, 2021),
  ('Engineering Analytics', '/engineering/engineering-analytics', '📁', 15, 2022),
  ('Engineering Calculations', '/engineering/engineering-calculations', '📁', 15, 2023),
  ('Engineering Command Center', '/engineering/engineering-command-center', '📁', 15, 2024),
  ('Engineering Documents', '/engineering/engineering-documents', '📁', 15, 2025),
  ('Engineering Office', '/engineering/engineering-office', '📁', 15, 2026),
  ('Engineering Projects', '/engineering/engineering-projects', '📁', 15, 2027),
  ('Engineering Settings', '/engineering/engineering-settings', '📁', 15, 2028),
  ('Engineering Standards', '/engineering/engineering-standards', '📁', 15, 2029),
  ('Material Specifications', '/engineering/material-specifications', '📁', 15, 2030),
  ('Product Catalog', '/engineering/product-catalog', '📁', 15, 2031),
  ('Prototype Testing', '/engineering/prototype-testing', '📁', 15, 2032),
  ('Bi Command Center', '/executive/bi-command-center', '📁', 15, 2033),
  ('Executive Command Center', '/executive/executive-command-center', '📁', 15, 2034),
  ('Executive Scorecard', '/executive/executive-scorecard', '📁', 15, 2035),
  ('Fab Accessories', '/fabrication/fab-accessories', '📁', 15, 2036),
  ('Fab Assembly Orders', '/fabrication/fab-assembly-orders', '📁', 15, 2037),
  ('Fab Coating Orders', '/fabrication/fab-coating-orders', '📁', 15, 2038),
  ('Fab Cutting Lists', '/fabrication/fab-cutting-lists', '📁', 15, 2039),
  ('Fab Finishes Colors', '/fabrication/fab-finishes-colors', '📁', 15, 2040),
  ('Fab Glass Catalog', '/fabrication/fab-glass-catalog', '📁', 15, 2041),
  ('Fab Glazing Orders', '/fabrication/fab-glazing-orders', '📁', 15, 2042),
  ('Fab Installation Orders', '/fabrication/fab-installation-orders', '📁', 15, 2043),
  ('Fab Packing Lists', '/fabrication/fab-packing-lists', '📁', 15, 2044),
  ('Fab Profiles', '/fabrication/fab-profiles', '📁', 15, 2045),
  ('Fab Service Tickets', '/fabrication/fab-service-tickets', '📁', 15, 2046),
  ('Fab Systems', '/fabrication/fab-systems', '📁', 15, 2047),
  ('Fab Transport Orders', '/fabrication/fab-transport-orders', '📁', 15, 2048),
  ('Fab Welding Orders', '/fabrication/fab-welding-orders', '📁', 15, 2049),
  ('Fab Workflow Tracker', '/fabrication/fab-workflow-tracker', '📁', 15, 2050),
  ('Fin Accounting', '/fin/fin-accounting', '📁', 15, 2051),
  ('Fin Credit Clearing', '/fin/fin-credit-clearing', '📁', 15, 2052),
  ('Fin Dashboard', '/fin/fin-dashboard', '📁', 15, 2053),
  ('Fin Document Create', '/fin/fin-document-create', '📁', 15, 2054),
  ('Fin Document Details', '/fin/fin-document-details', '📁', 15, 2055),
  ('Fin Documents List', '/fin/fin-documents-list', '📁', 15, 2056),
  ('Fin Recurring', '/fin/fin-recurring', '📁', 15, 2057),
  ('Fin Standing Orders', '/fin/fin-standing-orders', '📁', 15, 2058),
  ('Containers Packages', '/import/containers-packages', '📁', 15, 2059),
  ('Customs Clearance', '/import/customs-clearance', '📁', 15, 2060),
  ('Foreign Suppliers', '/import/foreign-suppliers', '📁', 15, 2061),
  ('Import Analytics', '/import/import-analytics', '📁', 15, 2062),
  ('Import Approvals', '/import/import-approvals', '📁', 15, 2063),
  ('Import Dashboard', '/import/import-dashboard', '📁', 15, 2064),
  ('Import Documents', '/import/import-documents', '📁', 15, 2065),
  ('Import Purchase Orders', '/import/import-purchase-orders', '📁', 15, 2066),
  ('Import Receiving', '/import/import-receiving', '📁', 15, 2067),
  ('Import Risk Alerts', '/import/import-risk-alerts', '📁', 15, 2068),
  ('Import Settings', '/import/import-settings', '📁', 15, 2069),
  ('Import Shipments', '/import/import-shipments', '📁', 15, 2070),
  ('Import Tracking', '/import/import-tracking', '📁', 15, 2071),
  ('Landed Cost Calculator', '/import/landed-cost-calculator', '📁', 15, 2072),
  ('Shipping Forwarders', '/import/shipping-forwarders', '📁', 15, 2073),
  ('Customer Handover', '/installation/customer-handover', '📁', 15, 2074),
  ('Equipment Tools', '/installation/equipment-tools', '📁', 15, 2075),
  ('Field Exceptions', '/installation/field-exceptions', '📁', 15, 2076),
  ('Installation Alerts', '/installation/installation-alerts', '📁', 15, 2077),
  ('Installation Cost Tracking', '/installation/installation-cost-tracking', '📁', 15, 2078),
  ('Installation Documents', '/installation/installation-documents', '📁', 15, 2079),
  ('Installation Management', '/installation/installation-management', '📁', 15, 2080),
  ('Installation Orders', '/installation/installation-orders', '📁', 15, 2081),
  ('Installation Profitability', '/installation/installation-profitability', '📁', 15, 2082),
  ('Installation Progress', '/installation/installation-progress', '📁', 15, 2083),
  ('Installation Quality Control', '/installation/installation-quality-control', '📁', 15, 2084),
  ('Installation Settings', '/installation/installation-settings', '📁', 15, 2085),
  ('Installer Profiles', '/installation/installer-profiles', '📁', 15, 2086),
  ('Loading Dispatch', '/installation/loading-dispatch', '📁', 15, 2087),
  ('Return Service Calls', '/installation/return-service-calls', '📁', 15, 2088),
  ('Gps Map', '/installations/gps-map', '📁', 15, 2089),
  ('Integration Hub', '/integration-hub', '📁', 15, 2090),
  ('Faq Management', '/knowledge/faq-management', '📁', 15, 2091),
  ('Knowledge Base', '/knowledge/knowledge-base', '📁', 15, 2092),
  ('Knowledge Command Center', '/knowledge/knowledge-command-center', '📁', 15, 2093),
  ('Lessons Learned', '/knowledge/lessons-learned', '📁', 15, 2094),
  ('Sop Procedures', '/knowledge/sop-procedures', '📁', 15, 2095),
  ('Barcode Rfid', '/logistics/barcode-rfid', '📁', 15, 2096),
  ('Cross Border', '/logistics/cross-border', '📁', 15, 2097),
  ('Customer Tracking Portal', '/logistics/customer-tracking-portal', '📁', 15, 2098),
  ('Delivery Cost Analysis', '/logistics/delivery-cost-analysis', '📁', 15, 2099),
  ('Delivery Scheduling', '/logistics/delivery-scheduling', '📁', 15, 2100),
  ('Fleet Alerts', '/logistics/fleet-alerts', '📁', 15, 2101),
  ('Fleet Delivery', '/logistics/fleet-delivery', '📁', 15, 2102),
  ('Freight', '/logistics/freight', '📁', 15, 2103),
  ('Freight Audit', '/logistics/freight-audit', '📁', 15, 2104),
  ('Fuel Management', '/logistics/fuel-management', '📁', 15, 2105),
  ('Loading Dock', '/logistics/loading-dock', '📁', 15, 2106),
  ('Logistics Dashboard', '/logistics/logistics-dashboard', '📁', 15, 2107),
  ('Packaging', '/logistics/packaging', '📁', 15, 2108),
  ('Proof Of Delivery', '/logistics/proof-of-delivery', '📁', 15, 2109),
  ('Reverse Logistics', '/logistics/reverse-logistics', '📁', 15, 2110),
  ('Vehicle Registry', '/logistics/vehicle-registry', '📁', 15, 2111),
  ('Delivery Dashboard', '/notification-settings/delivery-dashboard', '📁', 15, 2112),
  ('Email Templates', '/notification-settings/email-templates', '📁', 15, 2113),
  ('Cost Per Unit', '/operations/cost-per-unit', '📁', 15, 2114),
  ('Actions Studio', '/palantir/actions-studio', '📁', 15, 2115),
  ('Aip Agent Studio', '/palantir/aip-agent-studio', '📁', 15, 2116),
  ('Code Workspace', '/palantir/code-workspace', '📁', 15, 2117),
  ('Dossier Page', '/palantir/dossier-page', '📁', 15, 2118),
  ('Map Geospatial', '/palantir/map-geospatial', '📁', 15, 2119),
  ('Pipeline Builder', '/palantir/pipeline-builder', '📁', 15, 2120),
  ('Timeline Analysis', '/palantir/timeline-analysis', '📁', 15, 2121),
  ('Notifications Center', '/platform/notifications-center', '📁', 15, 2122),
  ('Security Audit', '/platform/security-audit', '📁', 15, 2123),
  ('Customer Portal Login', '/portal/customer-portal-login', '📁', 15, 2124),
  ('Actual Vs Estimated', '/pricing/actual-vs-estimated', '📁', 15, 2125),
  ('Labor Operations Cost', '/pricing/labor-operations-cost', '📁', 15, 2126),
  ('Landed Cost Source', '/pricing/landed-cost-source', '📁', 15, 2127),
  ('Material Price Pull', '/pricing/material-price-pull', '📁', 15, 2128),
  ('Pricing Approvals', '/pricing/pricing-approvals', '📁', 15, 2129),
  ('Pricing Cost Builder', '/pricing/pricing-cost-builder', '📁', 15, 2130),
  ('Pricing Cost Calculator', '/pricing/pricing-cost-calculator', '📁', 15, 2131),
  ('Pricing Dashboard', '/pricing/pricing-dashboard', '📁', 15, 2132),
  ('Pricing Price Lists', '/pricing/pricing-price-lists', '📁', 15, 2133),
  ('Pricing Requests List', '/pricing/pricing-requests-list', '📁', 15, 2134),
  ('Pricing Versions', '/pricing/pricing-versions', '📁', 15, 2135),
  ('Project Pricing Details', '/pricing/project-pricing-details', '📁', 15, 2136),
  ('Recommended Price', '/pricing/recommended-price', '📁', 15, 2137),
  ('Risk Margin Target', '/pricing/risk-margin-target', '📁', 15, 2138),
  ('Stock Vs Buy Decision', '/pricing/stock-vs-buy-decision', '📁', 15, 2139),
  ('Supplier Comparison Project', '/pricing/supplier-comparison-project', '📁', 15, 2140),
  ('Product Certifications', '/product-dev/product-certifications', '📁', 15, 2141),
  ('Product Design', '/product-dev/product-design', '📁', 15, 2142),
  ('Product Dev Command Center', '/product-dev/product-dev-command-center', '📁', 15, 2143),
  ('Product Launches', '/product-dev/product-launches', '📁', 15, 2144),
  ('Assembly Jobs', '/production/assembly-jobs', '📁', 15, 2145),
  ('Cut Jobs', '/production/cut-jobs', '📁', 15, 2146),
  ('Finishing Jobs', '/production/finishing-jobs', '📁', 15, 2147),
  ('Labor Control', '/production/labor-control', '📁', 15, 2148),
  ('Labor Time Tracking', '/production/labor-time-tracking', '📁', 15, 2149),
  ('Maintenance Downtime', '/production/maintenance-downtime', '📁', 15, 2150),
  ('Master Production Schedule', '/production/master-production-schedule', '📁', 15, 2151),
  ('Material Issuance', '/production/material-issuance', '📁', 15, 2152),
  ('Production Alerts', '/production/production-alerts', '📁', 15, 2153),
  ('Production Analytics', '/production/production-analytics', '📁', 15, 2154),
  ('Production Cost Tracking', '/production/production-cost-tracking', '📁', 15, 2155),
  ('Production Exceptions', '/production/production-exceptions', '📁', 15, 2156),
  ('Production Orders', '/production/production-orders', '📁', 15, 2157),
  ('Quality Defects Rework', '/production/quality-defects-rework', '📁', 15, 2158),
  ('Shortages Page', '/production/shortages-page', '📁', 15, 2159),
  ('Welding Jobs', '/production/welding-jobs', '📁', 15, 2160),
  ('Work Stations', '/production/work-stations', '📁', 15, 2161),
  ('Calibration', '/quality/calibration', '📁', 15, 2162),
  ('Document Control', '/quality/document-control', '📁', 15, 2163),
  ('Test Certificates', '/quality/test-certificates', '📁', 15, 2164),
  ('Safety Procedures', '/safety/safety-procedures', '📁', 15, 2165),
  ('Safety Training', '/safety/safety-training', '📁', 15, 2166),
  ('Service Analytics', '/service/service-analytics', '📁', 15, 2167),
  ('Service Cases', '/service/service-cases', '📁', 15, 2168),
  ('Service Cost Tracking', '/service/service-cost-tracking', '📁', 15, 2169),
  ('Api Connection Hub', '/settings/api-connection-hub', '🛠️', 15, 2170),
  ('Api Keys', '/settings/api-keys', '🛠️', 15, 2171),
  ('Israeli Integrations', '/settings/israeli-integrations', '🛠️', 15, 2172),
  ('Mfa Settings', '/settings/sections/mfa-settings', '🛠️', 15, 2173),
  ('Session Management', '/settings/sections/session-management', '🛠️', 15, 2174),
  ('Sso Settings', '/settings/sections/sso-settings', '🛠️', 15, 2175),
  ('Supplier Development', '/supplier-mgmt/supplier-development', '📁', 15, 2176),
  ('Supplier Portal Dashboard', '/supplier-mgmt/supplier-portal-dashboard', '📁', 15, 2177),
  ('Supplier Scorecards', '/supplier-mgmt/supplier-scorecards', '📁', 15, 2178),
  ('Supplier360', '/supplier-mgmt/supplier360', '📁', 15, 2179),
  ('Supply Chain Risk', '/supplier-mgmt/supply-chain-risk', '📁', 15, 2180),
  ('Vendor Compliance', '/supplier-mgmt/vendor-compliance', '📁', 15, 2181),
  ('Bom Comparison', '/supply-chain/bom-comparison', '📁', 15, 2182),
  ('Bom Cost Rollup', '/supply-chain/bom-cost-rollup', '📁', 15, 2183),
  ('Bom Templates', '/supply-chain/bom-templates', '📁', 15, 2184),
  ('Bom Versions', '/supply-chain/bom-versions', '📁', 15, 2185),
  ('Edi Admin', '/supply-chain/edi-admin', '📁', 15, 2186),
  ('Supply Chain Alerts', '/supply-chain/supply-chain-alerts', '📁', 15, 2187),
  ('Supply Chain Analytics', '/supply-chain/supply-chain-analytics', '📁', 15, 2188),
  ('Supply Chain Command Center', '/supply-chain/supply-chain-command-center', '📁', 15, 2189),
  ('Supply Chain Settings', '/supply-chain/supply-chain-settings', '📁', 15, 2190),
  ('Supply Chain Visibility', '/supply-chain/supply-chain-visibility', '📁', 15, 2191),
  ('Support Dashboard', '/support/support-dashboard', '📁', 15, 2192),
  ('Role Card', '/system/role-card', '🛠️', 15, 2193),
  ('User Card', '/system/user-card', '🛠️', 15, 2194),
  ('User Permission Override', '/system/user-permission-override', '🛠️', 15, 2195),
  ('User Role Assignment', '/system/user-role-assignment', '🛠️', 15, 2196),
  ('Tender Alerts', '/tenders/tender-alerts', '📁', 15, 2197),
  ('Tender Analytics', '/tenders/tender-analytics', '📁', 15, 2198),
  ('Tender Competitors', '/tenders/tender-competitors', '📁', 15, 2199),
  ('Tender Timeline', '/tenders/tender-timeline', '📁', 15, 2200);

-- ============================================================
-- Total new menu entries added: 381
-- ============================================================
