export const STATUS_LABELS: Record<string, string> = {
  completed: "הושלם",
  in_progress: "בביצוע",
  planned: "מתוכנן",
  pending: "ממתין",
  cancelled: "בוטל",
  active: "פעיל",
  inactive: "לא פעיל",
  draft: "טיוטה",
  approved: "אושר",
  rejected: "נדחה",
  overdue: "באיחור",
  "on-hold": "מושהה",
  open: "פתוח",
  closed: "סגור",
  invoiced: "חויב",
  paid: "שולם",
  partial: "חלקי",
  shipped: "נשלח",
  delivered: "נמסר",
  processing: "בעיבוד",
  "in-transit": "במעבר",
  returned: "הוחזר",
  archived: "בארכיון",
  suspended: "מושעה",
  expired: "פג תוקף",
  signed: "חתום",
  unsigned: "לא חתום",
  review: "בבדיקה",
  "under-review": "בבדיקה",
  negotiation: "במשא ומתן",
  executed: "בוצע",
  terminated: "הופסק",
  renewed: "חודש",
  planning: "בתכנון",
  "on_hold": "מושהה",
  sent: "נשלח",
  accepted: "התקבל",
  investigating: "בחקירה",
  "in-progress": "בביצוע",
  "not-started": "טרם החל",
  "not_started": "טרם החל",
  done: "הושלם",
  failed: "נכשל",
  paused: "מושהה",
  blocked: "חסום",
};

export function translateStatus(status: string | undefined | null): string {
  if (!status) return "—";
  return STATUS_LABELS[status] || STATUS_LABELS[status.toLowerCase()] || status;
}
